/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiKeysDelete } from "../../funcs/apiKeysDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteApiKeyRequest$inboundSchema,
};

export const tool$apiKeysDelete: ToolDefinition<typeof args> = {
  name: "api-keys-delete",
  description: `Delete API Key

Delete an existing API Key. Once deleted, the API Key can no longer be used to access the API.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await apiKeysDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
