/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiKeysList } from "../../funcs/apiKeysList.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$apiKeysList: ToolDefinition = {
  name: "api-keys-list",
  description: `List API Keys

Returns a list of all API keys from the team members
`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await apiKeysList(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
