/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { baselinesPreviewGetBaseline } from "../../funcs/baselinesPreviewGetBaseline.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetBaselineRequest$inboundSchema,
};

export const tool$baselinesPreviewGetBaseline: ToolDefinition<typeof args> = {
  name: "baselines-(preview)-get-baseline",
  description: `Retrieve baseline

**Preview.** Available to teams with the \`baselines_api\` feature flag.

Retrieve a single baseline.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await baselinesPreviewGetBaseline(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
