/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { blockStoragePostStorageVolumesUnmap } from "../../funcs/blockStoragePostStorageVolumesUnmap.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostStorageVolumesUnmapRequest$inboundSchema,
};

export const tool$blockStoragePostStorageVolumesUnmap: ToolDefinition<
  typeof args
> = {
  name: "block-storage-post-storage-volumes-unmap",
  description: `Unmap volume from server

Unmaps a high performance volume from the server it is currently mapped to.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await blockStoragePostStorageVolumesUnmap(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
