/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { blockStorageDeleteStorageVolumes } from "../../funcs/blockStorageDeleteStorageVolumes.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteStorageVolumesRequest$inboundSchema,
};

export const tool$blockStorageDeleteStorageVolumes: ToolDefinition<
  typeof args
> = {
  name: "block-storage-delete-storage-volumes",
  description: `Delete volume

Allows you to remove a volume from a project.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await blockStorageDeleteStorageVolumes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
