/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { elasticIpsUpdateElasticIp } from "../../funcs/elasticIpsUpdateElasticIp.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateElasticIpRequest$inboundSchema,
};

export const tool$elasticIpsUpdateElasticIp: ToolDefinition<typeof args> = {
  name: "elastic-ips-update-elastic-ip",
  description: `Move an Elastic IP

Moves an Elastic IP to a different server within the same project and site. The reassignment is performed asynchronously. The Elastic IP must be in \`active\` status, the target server must belong to the same project, and the target server must be in the same site as the currently assigned server.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await elasticIpsUpdateElasticIp(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
