/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { firewallsGetAllFirewallAssignments } from "../../funcs/firewallsGetAllFirewallAssignments.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAllFirewallAssignmentsRequest$inboundSchema.optional(),
};

export const tool$firewallsGetAllFirewallAssignments: ToolDefinition<
  typeof args
> = {
  name: "firewalls-get-all-firewall-assignments",
  description: `List All Firewall Assignments

List all firewall assignments`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await firewallsGetAllFirewallAssignments(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
