/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { managedDatabasesShowManagedDatabase } from "../../funcs/managedDatabasesShowManagedDatabase.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ShowManagedDatabaseRequest$inboundSchema,
};

export const tool$managedDatabasesShowManagedDatabase: ToolDefinition<
  typeof args
> = {
  name: "managed-databases-show-managed-database",
  description: `Show a managed database`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await managedDatabasesShowManagedDatabase(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
