/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { managedDatabasesListManagedDatabaseBackups } from "../../funcs/managedDatabasesListManagedDatabaseBackups.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListManagedDatabaseBackupsRequest$inboundSchema,
};

export const tool$managedDatabasesListManagedDatabaseBackups: ToolDefinition<
  typeof args
> = {
  name: "managed-databases-list-managed-database-backups",
  description: `List managed database backups`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await managedDatabasesListManagedDatabaseBackups(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
