/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { objectStorageGetStorageBucketMetrics } from "../../funcs/objectStorageGetStorageBucketMetrics.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetStorageBucketMetricsRequest$inboundSchema,
};

export const tool$objectStorageGetStorageBucketMetrics: ToolDefinition<
  typeof args
> = {
  name: "object-storage-get-storage-bucket-metrics",
  description: `Retrieve bucket metrics

Retrieves usage metrics for a specific object storage bucket, including storage consumption and estimated cost for the current billing period.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await objectStorageGetStorageBucketMetrics(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
