/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansGetContainersPlan } from "../../funcs/plansGetContainersPlan.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetContainersPlanRequest$inboundSchema,
};

export const tool$plansGetContainersPlan: ToolDefinition<typeof args> = {
  name: "plans-get-containers-plan",
  description: `Retrieve container plan

Retrieve a container plan.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await plansGetContainersPlan(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
