/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publicNetworksUpdatePublicNetworkIp } from "../../funcs/publicNetworksUpdatePublicNetworkIp.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdatePublicNetworkIpRequest$inboundSchema,
};

export const tool$publicNetworksUpdatePublicNetworkIp: ToolDefinition<
  typeof args
> = {
  name: "public-networks-update-public-network-ip",
  description: `Update a network IP

**Preview.** Available at locations where the \`public_network\` feature is enabled.

Reserve an available address of a network for your own use, so servers are never attached to the network with it, or release an address you reserved.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await publicNetworksUpdatePublicNetworkIp(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
