/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publicNetworksGetPublicNetwork } from "../../funcs/publicNetworksGetPublicNetwork.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetPublicNetworkRequest$inboundSchema,
};

export const tool$publicNetworksGetPublicNetwork: ToolDefinition<typeof args> =
  {
    name: "public-networks-get-public-network",
    description: `Retrieve a network

Retrieve a customer network`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await publicNetworksGetPublicNetwork(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
