/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversUnlock } from "../../funcs/serversUnlock.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ServerUnlockRequest$inboundSchema,
};

export const tool$serversUnlock: ToolDefinition<typeof args> = {
  name: "servers-unlock",
  description: `Unlock server

Unlocks the server. A locked server cannot be deleted or modified and no actions can be performed on it.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await serversUnlock(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
