/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversStartRescueMode } from "../../funcs/serversStartRescueMode.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ServerStartRescueModeRequest$inboundSchema,
};

export const tool$serversStartRescueMode: ToolDefinition<typeof args> = {
  name: "servers-start-rescue-mode",
  description: `Put server in rescue mode

Starts rescue mode on a given server.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await serversStartRescueMode(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
