/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sshKeysUpdate } from "../../funcs/sshKeysUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PutSshKeyRequest$inboundSchema,
};

export const tool$sshKeysUpdate: ToolDefinition<typeof args> = {
  name: "SSH-keys-update",
  description: `Update a SSH Key

Allows you update SSH Key in a project. These keys can be used to access servers after deploy and reinstall actions.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sshKeysUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
