/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storageGetStorageVolumes } from "../../funcs/storageGetStorageVolumes.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetStorageVolumesRequest$inboundSchema.optional(),
};

export const tool$storageGetStorageVolumes: ToolDefinition<typeof args> = {
  name: "storage-get-storage-volumes",
  description: `List volumes

Lists all the volumes from a team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await storageGetStorageVolumes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
