/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storageUpdateFilesystem } from "../../funcs/storageUpdateFilesystem.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PatchStorageFilesystemsRequest$inboundSchema,
};

export const tool$storageUpdateFilesystem: ToolDefinition<typeof args> = {
  name: "storage-update-filesystem",
  description: `Update a filesystem for a project

Allow you to upgrade the size of a filesystem.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await storageUpdateFilesystem(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
