/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storageDeleteFilesystem } from "../../funcs/storageDeleteFilesystem.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteStorageFilesystemsRequest$inboundSchema,
};

export const tool$storageDeleteFilesystem: ToolDefinition<typeof args> = {
  name: "storage-delete-filesystem",
  description: `Delete filesystem

Allows you to remove persistent storage from a project.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await storageDeleteFilesystem(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
