/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userDataUpdateForProject } from "../../funcs/userDataUpdateForProject.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PutProjectUserDataRequest$inboundSchema,
};

export const tool$userDataUpdateForProject: ToolDefinition<typeof args> = {
  name: "user-data-update-for-project",
  description: `Update Project user data

Allow you update User Data in a project.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await userDataUpdateForProject(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
