/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userDataUpdate } from "../../funcs/userDataUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PatchUserDataRequest$inboundSchema,
};

export const tool$userDataUpdate: ToolDefinition<typeof args> = {
  name: "user-data-update",
  description: `Update an User Data

Allow you update User Data in a team.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await userDataUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
