/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachinesShowVirtualMachineMetrics } from "../../funcs/virtualMachinesShowVirtualMachineMetrics.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ShowVirtualMachineMetricsRequest$inboundSchema,
};

export const tool$virtualMachinesShowVirtualMachineMetrics: ToolDefinition<
  typeof args
> = {
  name: "virtual-machines-show-virtual-machine-metrics",
  description: `Retrieve VM metrics

Retrieve a time series for a single metric of a Virtual Machine.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await virtualMachinesShowVirtualMachineMetrics(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
