/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachineRestoresListForVirtualMachineBackup } from "../../funcs/virtualMachineRestoresListForVirtualMachineBackup.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListVirtualMachineScopedRestoresRequest$inboundSchema,
};

export const tool$virtualMachineRestoresListForVirtualMachineBackup:
  ToolDefinition<typeof args> = {
    name: "virtual-machine-restores-list-for-virtual-machine-backup",
    description: `List a backup's restores

Lists the restores created from the given backup.
`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await virtualMachineRestoresListForVirtualMachineBackup(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
