/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachineBackupsDelete } from "../../funcs/virtualMachineBackupsDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteVirtualMachineBackupRequest$inboundSchema,
};

export const tool$virtualMachineBackupsDelete: ToolDefinition<typeof args> = {
  name: "virtual-machine-backups-delete",
  description: `Delete VM backup

Archives and deletes a Virtual Machine backup. Work runs asynchronously and returns 202 Accepted. Only \`Ready\` or \`Failed\` backups can be deleted, and not while a restore from the backup is in progress.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await virtualMachineBackupsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
