/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { vpnSessionsCreate } from "../../funcs/vpnSessionsCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostVpnSessionRequest$inboundSchema,
};

export const tool$vpnSessionsCreate: ToolDefinition<typeof args> = {
  name: "vpn-sessions-create",
  description: `Create a VPN Session

Creates a new VPN Session.
\`NOTE:\` The VPN credentials are only listed ONCE upon creation. They can however be refreshed or deleted.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await vpnSessionsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
