// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/models/operations"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPostAuthAPIKeys(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "post-api-key-Created[0]":
			dir.HandlerFunc("post-api-key", testPostAPIKeyPostAPIKeyCreated0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testPostAPIKeyPostAPIKeyCreated0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, ""); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/vnd.api+json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *operations.PostAPIKeyResponseBody = &operations.PostAPIKeyResponseBody{
		Data: &components.APIKey{
			ID:   types.String("tok_ez2A3DVldnawP"),
			Type: components.APIKeyTypeAPIKeys.ToPointer(),
			Attributes: &components.APIKeyAttributes{
				Name:           types.String("App Token"),
				APIVersion:     types.String("2023-06-01"),
				TokenLastSlice: types.String("4d063"),
				ReadOnly:       types.Bool(false),
				AllowedIps:     []string{},
				LastUsedAt:     nil,
				User: &components.APIKeyUser{
					ID:    types.String("user_pVkpyK2aoVUlax6Zzx1pfrGe4wr"),
					Email: types.String("nathanael@bartoletti-streich.test"),
				},
				CreatedAt: types.MustNewTimeFromString("2026-01-14T15:56:29+00:00"),
				UpdatedAt: types.MustNewTimeFromString("2026-01-14T15:56:29+00:00"),
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/vnd.api+json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}
