// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPatchTagsTagID(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "update-tag-Success[0]":
			dir.HandlerFunc("update-tag", testUpdateTagUpdateTagSuccess0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testUpdateTagUpdateTagSuccess0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, ""); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/vnd.api+json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.CustomTag = &components.CustomTag{
		Data: &components.CustomTagData{
			ID:   types.String("tag_XBlke2r5RyiyVpG9LPK8tWjalLL"),
			Type: components.CustomTagDataTypeTags.ToPointer(),
			Attributes: &components.CustomTagDataAttributes{
				Name:        types.String("Tag Name"),
				Slug:        types.String("tag-name"),
				Description: types.String("Aliquam ducimus atque et."),
				Color:       types.String("#73ba73"),
				Team: &components.TeamInclude{
					ID:          types.String("team_GplL3jvZnNS2BXLAmWQpf8z354ll"),
					Name:        types.String("633 Team"),
					Slug:        types.String("633-team"),
					Description: types.String("633 Team"),
					Address:     types.String("2092 Loreta Summit, West Hershelmouth, WY 97161-6201"),
					Currency:    &components.Currency{},
					Status:      types.String("verified"),
				},
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/vnd.api+json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
