// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathPostFirewalls(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "create-firewall-Created[0]":
			dir.HandlerFunc("create-firewall", testCreateFirewallCreateFirewallCreated0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testCreateFirewallCreateFirewallCreated0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, ""); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.ContentType(req, "application/json", true); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/vnd.api+json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.Firewall = &components.Firewall{
		Data: &components.FirewallData{
			ID:   types.String("fw_w5AEmq7XDBkWX"),
			Type: components.FirewallDataTypeFirewalls.ToPointer(),
			Attributes: &components.FirewallDataAttributes{
				Name: types.String("my-firewall"),
				Rules: []components.Rule{
					components.Rule{
						From:     types.String("ANY"),
						To:       types.String("ANY"),
						Port:     types.String("22"),
						Protocol: types.String("TCP"),
					},
					components.Rule{
						From:     types.String("192.168.42.73"),
						To:       types.String("192.168.43.51"),
						Port:     types.String("80"),
						Protocol: types.String("TCP"),
					},
					components.Rule{
						From:     types.String("192.168.1.16"),
						To:       types.String("192.168.1.30"),
						Port:     types.String("80"),
						Protocol: types.String("TCP"),
					},
					components.Rule{
						From:     types.String("192.168.1.10"),
						To:       types.String("192.168.1.20"),
						Port:     types.String("3000-4000"),
						Protocol: types.String("UDP"),
					},
				},
				Project: &components.FirewallDataProject{
					ID:   types.String("proj_RLYV8DZ2D5QoE"),
					Slug: types.String("heavy-duty-copper-watch"),
					Name: types.String("Heavy Duty Copper Watch"),
				},
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/vnd.api+json")
	w.WriteHeader(http.StatusCreated)
	_, _ = w.Write(respBodyBytes)
}
