// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetVirtualNetworks(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "get-virtual-networks-Success[0]":
			dir.HandlerFunc("get-virtual-networks", testGetVirtualNetworksGetVirtualNetworksSuccess0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testGetVirtualNetworksGetVirtualNetworksSuccess0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, ""); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/vnd.api+json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.VirtualNetworks = &components.VirtualNetworks{
		Data: []components.VirtualNetworkData{
			components.VirtualNetworkData{
				ID:   types.String("vlan_AW6Q2D9lqKLpr"),
				Type: components.VirtualNetworkDataTypeVirtualNetworks.ToPointer(),
				Attributes: &components.VirtualNetworkDataAttributes{
					Vid:         types.Int64(2040),
					Description: types.String("Consequatur quo aut quia."),
					Project: &components.ProjectInclude{
						ID:             types.String("proj_W6Q2D9ordKLpr"),
						Name:           types.String("Sleek Leather Hat"),
						Slug:           types.String("sleek-leather-hat"),
						Description:    types.String("Enormous Copper Lamp"),
						BillingType:    types.String("Normal"),
						BillingMethod:  types.String("Normal"),
						BandwidthAlert: types.Bool(false),
						Environment:    nil,
						Billing: &components.ProjectIncludeBilling{
							SubscriptionID: nil,
							Type:           types.String("Normal"),
							Method:         types.String("Normal"),
						},
						Stats: &components.ProjectIncludeStats{
							IPAddresses: types.Int64(2),
							Prefixes:    types.Int64(0),
							Servers:     types.Int64(1),
							Vlans:       types.Int64(2),
						},
					},
					Region: &components.VirtualNetworkDataRegion{
						City:    types.String("Sydney 243"),
						Country: types.String("Australia 253"),
						Site: &components.VirtualNetworkDataSite{
							ID:       types.String("loc_1ZJrdxnWDg4LV"),
							Facility: types.String("Sydney 243"),
							Name:     types.String("Sydney 243"),
							Slug:     types.String("SYD204"),
						},
					},
					CreatedAt:        nil,
					AssignmentsCount: types.Int64(1),
					Tags: []components.Tag{
						components.Tag{
							ID:          types.String("tag_rNk62XV5ewSV52K5oAv5FbENl1R"),
							Name:        types.String("tag1"),
							Description: types.String("Quia quia natus numquam."),
							Color:       types.String("#ead6ea"),
						},
					},
				},
			},
		},
		Meta: &components.VirtualNetworksMeta{},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/vnd.api+json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
