// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetProjectsProjectIDUserDataUserDataID(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "get-project-user-data-Success[0]":
			dir.HandlerFunc("get-project-user-data", testGetProjectUserDataGetProjectUserDataSuccess0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testGetProjectUserDataGetProjectUserDataSuccess0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, ""); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/vnd.api+json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.UserDataObject = &components.UserDataObject{
		Data: &components.UserDataProperties{
			ID:   types.String("ud_VLMmAD8EOwop2"),
			Type: components.UserDataPropertiesTypeUserData,
			Attributes: &components.UserDataPropertiesAttributes{
				Description: types.String("Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."),
				Content:     types.String("Q3JlYW15IG1hc2NhcnBvbmUgY2hlZXNlIGFuZCBjdXN0YXJkIGxheWVyZWQgYmV0d2VlbiBlc3ByZXNzbyBhbmQgcnVtIHNvYWtlZCBob3VzZS1tYWRlIGxhZHlmaW5nZXJzLCB0b3BwZWQgd2l0aCBWYWxyaG9uYSBjb2NvYSBwb3dkZXIu"),
				Project: &components.ProjectInclude{
					ID:               types.String("proj_e8pKq0GYdWAob"),
					Name:             types.String("Enormous Silk Car"),
					Slug:             types.String("enormous-silk-car"),
					Description:      types.String("Aerodynamic Granite Bag"),
					BillingType:      types.String("Normal"),
					ProvisioningType: types.String("on_demand"),
					BillingMethod:    types.String("Normal"),
					BandwidthAlert:   types.Bool(false),
					Environment:      nil,
					Billing:          &components.ProjectIncludeBilling{},
					Stats: &components.ProjectIncludeStats{
						IPAddresses: types.Int64(0),
						Prefixes:    types.Int64(0),
						Servers:     types.Int64(0),
						Vlans:       types.Int64(0),
					},
				},
				CreatedAt: types.String("2026-01-14T15:56:43+00:00"),
				UpdatedAt: types.String("2026-01-14T15:56:43+00:00"),
			},
		},
		Meta: &components.UserDataObjectMeta{},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/vnd.api+json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
