// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetProjects(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "get-projects-Success[0]":
			dir.HandlerFunc("get-projects", testGetProjectsGetProjectsSuccess0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testGetProjectsGetProjectsSuccess0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, ""); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/vnd.api+json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.Projects = &components.Projects{
		Data: []components.Project{
			components.Project{
				ID: types.String("proj_WeGoqAanqP7nz"),
				Attributes: &components.ProjectAttributes{
					Name:          types.String("Durable Iron Gloves"),
					Slug:          types.String("durable-iron-gloves"),
					Description:   types.String("Heavy Duty Steel Computer"),
					BillingType:   components.BillingTypeHourly.ToPointer(),
					BillingMethod: components.BillingMethodNormal.ToPointer(),
					Cost:          nil,
					Environment:   nil,
					Stats: &components.ProjectStats{
						IPAddresses: types.Float64(0),
						Prefixes:    types.Float64(0),
						Servers:     types.Float64(0),
						Vlans:       types.Float64(0),
					},
					Billing: &components.ProjectBilling{},
					Team: &components.TeamInclude{
						ID:           types.String("team_w03a5zVl9XsXVybw2gz7SNr1el2"),
						Name:         types.String("176 Team"),
						Slug:         types.String("176-team"),
						Description:  types.String("176 Team"),
						Address:      types.String("3253 VonRueden Creek, Jcbury, NV 21576"),
						Currency:     &components.Currency{},
						Status:       types.String("verified"),
						FeatureFlags: []string{},
					},
					CreatedAt: types.String("2026-01-14T15:56:39+00:00"),
					UpdatedAt: types.String("2026-01-14T15:56:39+00:00"),
				},
			},
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/vnd.api+json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
