/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Latitudesh } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Assignments Create Firewall Assignment Created", async () => {
  const testHttpClient = createTestHTTPClient(
    "create-firewall-assignment-Created",
  );

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.firewalls.assignments.create({
    firewallId: "fw_Ee8pKq05DWAob",
    requestBody: {
      data: {
        type: "firewall_assignments",
        attributes: {
          serverId: "sv_aKXgRdR3qv9k5",
        },
      },
    },
  });
  expect(result).toBeDefined();
});
