/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Latitudesh } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Privatenetworks Get Virtual Networks Success", async () => {
  const testHttpClient = createTestHTTPClient("get-virtual-networks-Success");

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.privateNetworks.list({
    filterTags:
      "tag_BZWAJKePr2Fx9kRyyaARImQlXmW,tag_X8yMgb8AZPFrX72lQgrwhBVnPN2",
  });
  expect(result).toBeDefined();
});

test("Privatenetworks Create Virtual Network Created", async () => {
  const testHttpClient = createTestHTTPClient("create-virtual-network-Created");

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.privateNetworks.create({
    data: {
      type: "virtual_network",
      attributes: {
        description: "São Paulo VLAN",
        site: "MIA",
        project: "ergonomic-steel-bag",
      },
    },
  });
  expect(result).toBeDefined();
});

test("Privatenetworks Get Virtual Network Success", async () => {
  const testHttpClient = createTestHTTPClient("get-virtual-network-Success");

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.privateNetworks.get({
    vlanId: "vlan_W6Q2D9ordKLpr",
  });
  expect(result).toBeDefined();
});

test("Privatenetworks Update Virtual Network Success", async () => {
  const testHttpClient = createTestHTTPClient("update-virtual-network-Success");

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.privateNetworks.update({
    vlanId: "vlan_VaNmodjeObE8W",
    requestBody: {
      data: {
        id: "vlan_VaNmodjeObE8W",
        type: "virtual_networks",
        attributes: {
          tags: [
            "tag_RjLvG6oe84IAw7BxxEGaFAXK4l4",
            "tag_lpPQ21kXEYfb9az3jRoVIVw4RBk",
          ],
        },
      },
    },
  });
  expect(result).toBeDefined();
});

test("Privatenetworks Get Virtual Networks Assignments Success", async () => {
  const testHttpClient = createTestHTTPClient(
    "get-virtual-networks-assignments-Success",
  );

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.privateNetworks.listAssignments({});
  expect(result).toBeDefined();
});

test("Privatenetworks Assign Server Virtual Network Created", async () => {
  const testHttpClient = createTestHTTPClient(
    "assign-server-virtual-network-Created",
  );

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.privateNetworks.assign({
    data: {
      type: "virtual_network_assignment",
      attributes: {
        serverId: "sv_5xyZOn5vDWM0l",
        virtualNetworkId: "vlan_Z8rodmpGO1jLB",
      },
    },
  });
  expect(result).toBeDefined();
});
