/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { expect, test } from "vitest";
import { Latitudesh } from "../index.js";
import { createTestHTTPClient } from "./testclient.js";

test("Ssh Keys Get Project Ssh Keys Success", async () => {
  const testHttpClient = createTestHTTPClient("get-project-ssh-keys-Success");

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.sshKeys.list({
    projectId: "proj_5AEmq7wMqBkWX",
    filterTags:
      "tag_5wKQ2Y9eoAi5plr4zlQ6tjl6rEw,tag_8GKKZ6B9MbtYl4K09gj4fXy9Nneg",
  });
  expect(result).toBeDefined();
});

test("Ssh Keys Get Project Ssh Key Success", async () => {
  const testHttpClient = createTestHTTPClient("get-project-ssh-key-Success");

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.sshKeys.get({
    projectId: "proj_kjQwdE0XOYNVP",
    sshKeyId: "ssh_zGr47qlMDAg0m",
  });
  expect(result).toBeDefined();
});

test("Ssh Keys Put Project Ssh Key Success", async () => {
  const testHttpClient = createTestHTTPClient("put-project-ssh-key-Success");

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.sshKeys.modifyProjectKey({
    projectId: "proj_v9BVDaR3ORm1W",
    sshKeyId: "ssh_zlkg1DegdvZE5",
    requestBody: {
      data: {
        id: "ssh_zlkg1DegdvZE5",
        type: "ssh_keys",
        attributes: {
          tags: [
            "tag_rB7B21L1QbiJ6yWYxQLmHWJE3GmR",
            "tag_57nzyG0Bn3c5wooyYyeLH1w9kmN",
          ],
        },
      },
    },
  });
  expect(result).toBeDefined();
});

test("Ssh Keys Get Ssh Keys Success", async () => {
  const testHttpClient = createTestHTTPClient("get-ssh-keys-Success");

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.sshKeys.listAll({
    filterTags:
      "tag_A06EMPEmKXhKBNKgWrv0CRZMN5a,tag_P7xlGZzYNZF4w3YXRrYMU7AjQEAX",
  });
  expect(result).toBeDefined();
});

test("Ssh Keys Post Ssh Key Created", async () => {
  const testHttpClient = createTestHTTPClient("post-ssh-key-Created");

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.sshKeys.create({
    data: {
      type: "ssh_keys",
      attributes: {
        name: "SSH Key",
        project: "proj_z2A3DV4wdnawP",
        publicKey:
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOLFnjGP3Jsh1usHNS2EILgfqZNC9pOvNqBZqxH+qNAdZdQCzy2csMuiq+ZwLA8Mm4Vo5CvSgBHs/kuZRUKyTl+79YUMZIj8PhHzL4XbdqX1ZnAIklHWcJaveB0+UXLEPKGzFIFq+FkuwtiXQsVe5NnSpIDYgpzhqEs38NsnXvsubKphGUdARDhaxvMdUUl4YsAtLHKMzSyIvE6xwfTtIVwA9bZt/8GoBzrn9px9PEcf25Rgd2NhOYs3WYcZuwvRmfcFdi2vGhVqTPqL9n16R/n5jknxHYrTyqWNxJdpdvg2YqXpN7vnFNoOjYFD6EahJ0pF/+WL4tPCIkLfoaVaSx",
      },
    },
  });
  expect(result).toBeDefined();
});

test("Ssh Keys Get Ssh Key Success", async () => {
  const testHttpClient = createTestHTTPClient("get-ssh-key-Success");

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.sshKeys.retrieve({
    sshKeyId: "ssh_LYV8DZ12q5QoE",
  });
  expect(result).toBeDefined();
});

test("Ssh Keys Put Ssh Key Success", async () => {
  const testHttpClient = createTestHTTPClient("put-ssh-key-Success");

  const latitudesh = new Latitudesh({
    serverURL: process.env["TEST_SERVER_URL"] ?? "http://localhost:18080",
    httpClient: testHttpClient,
    bearer: process.env["LATITUDESH_BEARER"] ?? "value",
  });

  const result = await latitudesh.sshKeys.update({
    sshKeyId: "ssh_GnzRD5xAqM5yw",
    requestBody: {
      data: {
        id: "ssh_GnzRD5xAqM5yw",
        type: "ssh_keys",
        attributes: {
          tags: [
            "tag_JLA906BzyKHLyVJbJr8NH3QQbev",
            "tag_Yy7PJ68y22FoQyBppnW7FjNGX1k",
          ],
        },
      },
    },
  });
  expect(result).toBeDefined();
});
