/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { firewallsAssignmentsCreate } from "../funcs/firewallsAssignmentsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Assignments extends ClientSDK {
  /**
   * Assign server to firewall
   *
   * @remarks
   * Assigns a server to a firewall by its ID.
   */
  async create(
    request: operations.CreateFirewallAssignmentRequest,
    options?: RequestOptions,
  ): Promise<models.FirewallServer> {
    return unwrapAsync(firewallsAssignmentsCreate(
      this,
      request,
      options,
    ));
  }
}
