/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { baselinesPreviewCreateBaseline } from "../funcs/baselinesPreviewCreateBaseline.js";
import { baselinesPreviewDestroyBaseline } from "../funcs/baselinesPreviewDestroyBaseline.js";
import { baselinesPreviewGetBaseline } from "../funcs/baselinesPreviewGetBaseline.js";
import { baselinesPreviewGetBaselines } from "../funcs/baselinesPreviewGetBaselines.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class BaselinesPreview extends ClientSDK {
  /**
   * List baselines
   *
   * @remarks
   * **Preview.** Available to teams with the `baselines_api` feature flag. The shape of this
   * endpoint may change before general availability.
   *
   * List all baselines in the team. A baseline records the configuration you expect your
   * servers to be delivered with — plan, SSH keys, user data, disk layout and BIOS settings.
   */
  async getBaselines(
    options?: RequestOptions,
  ): Promise<models.Baselines> {
    return unwrapAsync(baselinesPreviewGetBaselines(
      this,
      options,
    ));
  }

  /**
   * Create baseline
   *
   * @remarks
   * **Preview.** Available to teams with the `baselines_api` feature flag.
   *
   * Create a baseline in the team. A baseline can target all servers, a custom set (when the
   * plan is not yet known), or one or more specific platforms. When it targets platforms, the
   * disk layout is validated by the same rules a deploy applies — against the smallest of the
   * selected platforms — so a baseline that saves here can be dispatched verbatim.
   */
  async createBaseline(
    request: operations.CreateBaselineRequest,
    options?: RequestOptions,
  ): Promise<models.Baseline> {
    return unwrapAsync(baselinesPreviewCreateBaseline(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve baseline
   *
   * @remarks
   * **Preview.** Available to teams with the `baselines_api` feature flag.
   *
   * Retrieve a single baseline.
   */
  async getBaseline(
    request: operations.GetBaselineRequest,
    options?: RequestOptions,
  ): Promise<models.Baseline> {
    return unwrapAsync(baselinesPreviewGetBaseline(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete baseline
   *
   * @remarks
   * **Preview.** Available to teams with the `baselines_api` feature flag.
   *
   * Delete a baseline.
   */
  async destroyBaseline(
    request: operations.DestroyBaselineRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(baselinesPreviewDestroyBaseline(
      this,
      request,
      options,
    ));
  }
}
