/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { lksCreateLKSCluster } from "../funcs/lksCreateLKSCluster.js";
import { lksCreateLKSNodePool } from "../funcs/lksCreateLKSNodePool.js";
import { lksDeleteLKSCluster } from "../funcs/lksDeleteLKSCluster.js";
import { lksDeleteLKSNodePool } from "../funcs/lksDeleteLKSNodePool.js";
import { lksGetLKSCluster } from "../funcs/lksGetLKSCluster.js";
import { lksGetLKSClusterKubeconfig } from "../funcs/lksGetLKSClusterKubeconfig.js";
import { lksGetLKSNodePool } from "../funcs/lksGetLKSNodePool.js";
import { lksListLKSAvailableVersions } from "../funcs/lksListLKSAvailableVersions.js";
import { lksListLKSClusters } from "../funcs/lksListLKSClusters.js";
import { lksListLKSNodePools } from "../funcs/lksListLKSNodePools.js";
import { lksListLKSSites } from "../funcs/lksListLKSSites.js";
import { lksUpdateLKSCluster } from "../funcs/lksUpdateLKSCluster.js";
import { lksUpdateLKSNodePool } from "../funcs/lksUpdateLKSNodePool.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Lks extends ClientSDK {
  /**
   * List LKS clusters
   *
   * @remarks
   * Lists every LKS cluster of a project. The response is not paginated; `meta.total` is the number of clusters returned.
   */
  async listLksClusters(
    request: operations.ListLksClustersRequest,
    options?: RequestOptions,
  ): Promise<models.LksClusters> {
    return unwrapAsync(lksListLKSClusters(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an LKS cluster
   *
   * @remarks
   * Creates an LKS cluster. The cluster is the control plane only — worker capacity is added separately through node pools (`POST /lks/clusters/{cluster_id}/nodepools`).
   *
   * `site` must be one of the slugs returned by `GET /lks/sites`, and `kubernetes_version` must be a patch listed by `GET /lks/available_versions` with `available_for_creation: true`.
   *
   * The cluster is returned immediately with `status: "provisioning"`. Poll `GET /lks/clusters/{id}` until `status` is `ready`, then fetch the kubeconfig.
   */
  async createLksCluster(
    request: models.CreateLksCluster,
    options?: RequestOptions,
  ): Promise<models.LksCluster> {
    return unwrapAsync(lksCreateLKSCluster(
      this,
      request,
      options,
    ));
  }

  /**
   * Get an LKS cluster
   *
   * @remarks
   * Retrieves a single LKS cluster.
   *
   * `status` is an open enum sourced from the platform controller — `provisioning`, `ready`, `updating`, `scaling`, `upgrading`, `paused`, `deleting` and `deleted` are the values in use today, and new ones may appear without notice. `reason` and `message` carry the machine-readable and human-readable detail behind the current `status`.
   */
  async getLksCluster(
    request: operations.GetLksClusterRequest,
    options?: RequestOptions,
  ): Promise<models.LksCluster> {
    return unwrapAsync(lksGetLKSCluster(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an LKS cluster
   *
   * @remarks
   * Marks the cluster for deletion. The call returns as soon as the tombstone is written; the platform then tears the cluster and its node pools down asynchronously. A cluster that is already deleted, or that is paused, rejects the request.
   */
  async deleteLksCluster(
    request: operations.DeleteLksClusterRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(lksDeleteLKSCluster(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an LKS cluster
   *
   * @remarks
   * Renames a cluster, edits its description, or upgrades the control plane. At least one of `name`, `description` or `kubernetes_version` must be provided.
   *
   * Setting a newer `kubernetes_version` consents to a control-plane upgrade; the value must be a patch listed by `GET /lks/available_versions` with `available_for_upgrade: true` and must not be lower than the current one. Node pools are upgraded separately and must never run a patch newer than the control plane.
   *
   * The cluster must be idle: a cluster that is provisioning, updating, scaling, upgrading, paused or deleting rejects the request with 409.
   */
  async updateLksCluster(
    request: operations.UpdateLksClusterRequest,
    options?: RequestOptions,
  ): Promise<models.LksCluster> {
    return unwrapAsync(lksUpdateLKSCluster(
      this,
      request,
      options,
    ));
  }

  /**
   * Get the cluster kubeconfig
   *
   * @remarks
   * Returns the kubeconfig for the cluster. It only exists once the control plane is up, so this endpoint answers 409 `NOT_READY` while the cluster is still provisioning — poll `GET /lks/clusters/{id}` until `kubeconfig_url` is set.
   */
  async getLksClusterKubeconfig(
    request: operations.GetLksClusterKubeconfigRequest,
    options?: RequestOptions,
  ): Promise<models.LksClusterKubeconfig> {
    return unwrapAsync(lksGetLKSClusterKubeconfig(
      this,
      request,
      options,
    ));
  }

  /**
   * List node pools
   *
   * @remarks
   * Lists every node pool of an LKS cluster. The response is not paginated; `meta.total` is the number of node pools returned.
   */
  async listLksNodePools(
    request: operations.ListLksNodePoolsRequest,
    options?: RequestOptions,
  ): Promise<models.LksNodePools> {
    return unwrapAsync(lksListLKSNodePools(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a node pool
   *
   * @remarks
   * Adds a node pool to an LKS cluster. The platform provisions `count` servers of `plan` from stock, so both fields are required.
   *
   * `kubernetes_version` defaults to the control-plane patch and may never be newer than it. `max_pods_per_node` is set once, here — it cannot be changed later.
   */
  async createLksNodePool(
    request: operations.CreateLksNodePoolRequest,
    options?: RequestOptions,
  ): Promise<models.LksNodePool> {
    return unwrapAsync(lksCreateLKSNodePool(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a node pool
   *
   * @remarks
   * Retrieves a single node pool of an LKS cluster. `ready_nodes` reports how many of the pool's `count` nodes have joined the cluster.
   */
  async getLksNodePool(
    request: operations.GetLksNodePoolRequest,
    options?: RequestOptions,
  ): Promise<models.LksNodePool> {
    return unwrapAsync(lksGetLKSNodePool(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a node pool
   *
   * @remarks
   * Marks the node pool for deletion. The call returns as soon as the tombstone is written; the platform then drains and releases the nodes asynchronously.
   */
  async deleteLksNodePool(
    request: operations.DeleteLksNodePoolRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(lksDeleteLKSNodePool(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a node pool
   *
   * @remarks
   * Scales, renames, upgrades or re-labels a node pool. At least one attribute must be provided.
   *
   * `labels` and `taints` are declarative replacements, not merges: omit the field to leave it untouched, send the whole map/list to replace it, or send `{}` / `[]` to clear it.
   *
   * A newer `kubernetes_version` rolls a node-recreating upgrade; it must not be lower than the pool's current patch nor newer than the control-plane patch. `max_pods_per_node` is immutable — a PATCH that carries it is rejected with 422 even if the value is unchanged.
   *
   * The node pool must be idle: one that is provisioning, updating, scaling, upgrading, paused or deleting rejects the request with 409.
   */
  async updateLksNodePool(
    request: operations.UpdateLksNodePoolRequest,
    options?: RequestOptions,
  ): Promise<models.LksNodePool> {
    return unwrapAsync(lksUpdateLKSNodePool(
      this,
      request,
      options,
    ));
  }

  /**
   * List available Kubernetes versions
   *
   * @remarks
   * Lists the Kubernetes patches the platform offers, with their lifecycle flags. Use a version with `available_for_creation: true` when creating a cluster or a node pool, and one with `available_for_upgrade: true` when upgrading. Exactly one entry has `default: true`.
   */
  async listLksAvailableVersions(
    options?: RequestOptions,
  ): Promise<models.LksKubernetesVersions> {
    return unwrapAsync(lksListLKSAvailableVersions(
      this,
      options,
    ));
  }

  /**
   * List sites available for LKS
   *
   * @remarks
   * Lists the sites that can host an LKS cluster, one entry per site. Pass an entry's `id` (the site slug) as `site` when creating a cluster. `country` is null when the underlying site has no region assigned.
   */
  async listLksSites(
    options?: RequestOptions,
  ): Promise<models.LksSites> {
    return unwrapAsync(lksListLKSSites(
      this,
      options,
    ));
  }
}
