/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsCreate } from "../funcs/projectsCreate.js";
import { projectsDelete } from "../funcs/projectsDelete.js";
import { projectsList } from "../funcs/projectsList.js";
import { projectsUpdate } from "../funcs/projectsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";
import { ProjectsSshKeys } from "./projectssshkeys.js";

export class Projects extends ClientSDK {
  private _sshKeys?: ProjectsSshKeys;
  get sshKeys(): ProjectsSshKeys {
    return (this._sshKeys ??= new ProjectsSshKeys(this._options));
  }

  /**
   * List all Projects
   *
   * @remarks
   * Returns a list of all projects for the current team
   */
  async list(
    request?: operations.GetProjectsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetProjectsResponse, { page: number }>> {
    return unwrapResultIterator(projectsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a Project
   */
  async create(
    request: operations.CreateProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateProjectResponse> {
    return unwrapAsync(projectsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a Project
   */
  async delete(
    request: operations.DeleteProjectRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(projectsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a Project
   */
  async update(
    request: operations.UpdateProjectRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateProjectResponse> {
    return unwrapAsync(projectsUpdate(
      this,
      request,
      options,
    ));
  }
}
