/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sshKeysCreate } from "../funcs/sshKeysCreate.js";
import { sshKeysDelete } from "../funcs/sshKeysDelete.js";
import { sshKeysGet } from "../funcs/sshKeysGet.js";
import { sshKeysList } from "../funcs/sshKeysList.js";
import { sshKeysListAll } from "../funcs/sshKeysListAll.js";
import { sshKeysModifyProjectKey } from "../funcs/sshKeysModifyProjectKey.js";
import { sshKeysRemoveFromProject } from "../funcs/sshKeysRemoveFromProject.js";
import { sshKeysRetrieve } from "../funcs/sshKeysRetrieve.js";
import { sshKeysUpdate } from "../funcs/sshKeysUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SSHKeys extends ClientSDK {
  /**
   * List SSH keys
   *
   * @remarks
   * List SSH keys in the project. These keys can be used to access servers after deploy and reinstall actions.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async list(
    request: operations.GetProjectSshKeysRequest,
    options?: RequestOptions,
  ): Promise<models.SshKeys> {
    return unwrapAsync(sshKeysList(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a Project SSH Key
   *
   * @remarks
   * List all SSH Keys in the project. These keys can be used to access servers after deploy and reinstall actions.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async get(
    request: operations.GetProjectSshKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.GetProjectSshKeyResponse> {
    return unwrapAsync(sshKeysGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a Project SSH Key
   *
   * @remarks
   * Allow you remove SSH Keys in a project. Remove a SSH Key from the project won't revoke the SSH Keys access for previously deploy and reinstall actions.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async removeFromProject(
    request: operations.DeleteProjectSshKeyRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sshKeysRemoveFromProject(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a Project SSH Key
   *
   * @remarks
   * Allow you update SSH Key in a project. These keys can be used to access servers after deploy and reinstall actions.
   *
   * @deprecated method: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  async modifyProjectKey(
    request: operations.PutProjectSshKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.PutProjectSshKeyResponse> {
    return unwrapAsync(sshKeysModifyProjectKey(
      this,
      request,
      options,
    ));
  }

  /**
   * List SSH Keys
   *
   * @remarks
   * List all SSH Keys in the project. These keys can be used to access servers after deploy and reinstall actions.
   */
  async listAll(
    request?: operations.GetSshKeysRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.SshKeys> {
    return unwrapAsync(sshKeysListAll(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a SSH Key
   *
   * @remarks
   * Allows you create SSH Keys. These keys can be used to access servers after deploy and reinstall actions.
   */
  async create(
    request: operations.PostSshKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.PostSshKeyResponse> {
    return unwrapAsync(sshKeysCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a SSH Key
   *
   * @remarks
   * List all SSH Keys in the project. These keys can be used to access servers after deploy and reinstall actions.
   */
  async retrieve(
    request: operations.GetSshKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSshKeyResponse> {
    return unwrapAsync(sshKeysRetrieve(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a SSH Key
   *
   * @remarks
   * Allows you remove SSH Keys in a project. Remove a SSH Key from the project won't revoke the SSH Keys access for previously deploy and reinstall actions.
   */
  async delete(
    request: operations.DeleteSshKeyRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sshKeysDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a SSH Key
   *
   * @remarks
   * Allows you update SSH Key in a project. These keys can be used to access servers after deploy and reinstall actions.
   */
  async update(
    request: operations.PutSshKeyRequest,
    options?: RequestOptions,
  ): Promise<operations.PutSshKeyResponse> {
    return unwrapAsync(sshKeysUpdate(
      this,
      request,
      options,
    ));
  }
}
