/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trafficGet } from "../funcs/trafficGet.js";
import { trafficGetQuota } from "../funcs/trafficGetQuota.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Traffic extends ClientSDK {
  /**
   * Retrieve Traffic consumption
   */
  async get(
    request: operations.GetTrafficConsumptionRequest,
    options?: RequestOptions,
  ): Promise<models.Traffic> {
    return unwrapAsync(trafficGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve Traffic Quota
   */
  async getQuota(
    request?: operations.GetTrafficQuotaRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.TrafficQuota> {
    return unwrapAsync(trafficGetQuota(
      this,
      request,
      options,
    ));
  }
}
