/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansVmList } from "../funcs/plansVmList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Vm extends ClientSDK {
  /**
   * List all Virtual Machines Plans
   */
  async list(
    options?: RequestOptions,
  ): Promise<models.VirtualMachinePlans> {
    return unwrapAsync(plansVmList(
      this,
      options,
    ));
  }
}
