// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
)

type CreateFirewallType2 string

const (
	CreateFirewallType2Firewalls CreateFirewallType2 = "firewalls"
)

func (e CreateFirewallType2) ToPointer() *CreateFirewallType2 {
	return &e
}
func (e *CreateFirewallType2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "firewalls":
		*e = CreateFirewallType2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateFirewallType2: %v", v)
	}
}

type CreateFirewallProtocol2 string

const (
	CreateFirewallProtocol2TCP CreateFirewallProtocol2 = "TCP"
	CreateFirewallProtocol2UDP CreateFirewallProtocol2 = "UDP"
)

func (e CreateFirewallProtocol2) ToPointer() *CreateFirewallProtocol2 {
	return &e
}
func (e *CreateFirewallProtocol2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TCP":
		fallthrough
	case "UDP":
		*e = CreateFirewallProtocol2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateFirewallProtocol2: %v", v)
	}
}

type CreateFirewallRule2 struct {
	// Source IP address, IP range in CIDR notation, or 'ANY' (e.g., "192.168.1.1", "192.168.1.0/24", "ANY")
	From *string `json:"from,omitempty"`
	// Destination IP address, IP range in CIDR notation, or 'ANY' (e.g., "192.168.1.1", "192.168.1.0/24", "ANY")
	To       *string                  `json:"to,omitempty"`
	Protocol *CreateFirewallProtocol2 `json:"protocol,omitempty"`
	// Port number or range (e.g., "80", "80-443")
	Port *string `json:"port,omitempty"`
}

func (o *CreateFirewallRule2) GetFrom() *string {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *CreateFirewallRule2) GetTo() *string {
	if o == nil {
		return nil
	}
	return o.To
}

func (o *CreateFirewallRule2) GetProtocol() *CreateFirewallProtocol2 {
	if o == nil {
		return nil
	}
	return o.Protocol
}

func (o *CreateFirewallRule2) GetPort() *string {
	if o == nil {
		return nil
	}
	return o.Port
}

type CreateFirewallAttributes2 struct {
	Name    string                `json:"name"`
	Project string                `json:"project"`
	Rules   []CreateFirewallRule2 `json:"rules,omitempty"`
}

func (o *CreateFirewallAttributes2) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateFirewallAttributes2) GetProject() string {
	if o == nil {
		return ""
	}
	return o.Project
}

func (o *CreateFirewallAttributes2) GetRules() []CreateFirewallRule2 {
	if o == nil {
		return nil
	}
	return o.Rules
}

type CreateFirewallData2 struct {
	Type       CreateFirewallType2        `json:"type"`
	Attributes *CreateFirewallAttributes2 `json:"attributes,omitempty"`
}

func (o *CreateFirewallData2) GetType() CreateFirewallType2 {
	if o == nil {
		return CreateFirewallType2("")
	}
	return o.Type
}

func (o *CreateFirewallData2) GetAttributes() *CreateFirewallAttributes2 {
	if o == nil {
		return nil
	}
	return o.Attributes
}

type CreateFirewallRequest struct {
	Data CreateFirewallData2 `json:"data"`
}

func (o *CreateFirewallRequest) GetData() CreateFirewallData2 {
	if o == nil {
		return CreateFirewallData2{}
	}
	return o.Data
}

type CreateFirewallResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	Firewall *components.Firewall
}

func (o *CreateFirewallResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateFirewallResponse) GetFirewall() *components.Firewall {
	if o == nil {
		return nil
	}
	return o.Firewall
}
