// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetAPIKeysResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	APIKeys *components.APIKeys
}

func (o *GetAPIKeysResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAPIKeysResponse) GetAPIKeys() *components.APIKeys {
	if o == nil {
		return nil
	}
	return o.APIKeys
}
