// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetTagsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	CustomTags *components.CustomTags
}

func (o *GetTagsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTagsResponse) GetCustomTags() *components.CustomTags {
	if o == nil {
		return nil
	}
	return o.CustomTags
}
