// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type GetVMPlansRequest struct {
	// Filter plans by GPU availability
	FilterGpu *bool `queryParam:"style=form,explode=true,name=filter[gpu]"`
}

func (o *GetVMPlansRequest) GetFilterGpu() *bool {
	if o == nil {
		return nil
	}
	return o.FilterGpu
}

type GetVMPlansResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	VirtualMachinePlans *components.VirtualMachinePlans
}

func (o *GetVMPlansResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetVMPlansResponse) GetVirtualMachinePlans() *components.VirtualMachinePlans {
	if o == nil {
		return nil
	}
	return o.VirtualMachinePlans
}
