// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/utils"
)

type PatchCurrentTeamType2 string

const (
	PatchCurrentTeamType2Teams PatchCurrentTeamType2 = "teams"
)

func (e PatchCurrentTeamType2) ToPointer() *PatchCurrentTeamType2 {
	return &e
}
func (e *PatchCurrentTeamType2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "teams":
		*e = PatchCurrentTeamType2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PatchCurrentTeamType2: %v", v)
	}
}

type PatchCurrentTeamCurrency2 string

const (
	PatchCurrentTeamCurrency2Usd PatchCurrentTeamCurrency2 = "USD"
	PatchCurrentTeamCurrency2Brl PatchCurrentTeamCurrency2 = "BRL"
)

func (e PatchCurrentTeamCurrency2) ToPointer() *PatchCurrentTeamCurrency2 {
	return &e
}
func (e *PatchCurrentTeamCurrency2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "USD":
		fallthrough
	case "BRL":
		*e = PatchCurrentTeamCurrency2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PatchCurrentTeamCurrency2: %v", v)
	}
}

type PatchCurrentTeamAttributes2 struct {
	Address      *string                    `json:"address,omitempty"`
	Name         *string                    `json:"name,omitempty"`
	Currency     *PatchCurrentTeamCurrency2 `default:"USD" json:"currency"`
	ReferredCode *string                    `json:"referred_code,omitempty"`
}

func (p PatchCurrentTeamAttributes2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatchCurrentTeamAttributes2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *PatchCurrentTeamAttributes2) GetAddress() *string {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *PatchCurrentTeamAttributes2) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *PatchCurrentTeamAttributes2) GetCurrency() *PatchCurrentTeamCurrency2 {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *PatchCurrentTeamAttributes2) GetReferredCode() *string {
	if o == nil {
		return nil
	}
	return o.ReferredCode
}

type PatchCurrentTeamData2 struct {
	ID         string                       `json:"id"`
	Type       PatchCurrentTeamType2        `json:"type"`
	Attributes *PatchCurrentTeamAttributes2 `json:"attributes,omitempty"`
}

func (o *PatchCurrentTeamData2) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PatchCurrentTeamData2) GetType() PatchCurrentTeamType2 {
	if o == nil {
		return PatchCurrentTeamType2("")
	}
	return o.Type
}

func (o *PatchCurrentTeamData2) GetAttributes() *PatchCurrentTeamAttributes2 {
	if o == nil {
		return nil
	}
	return o.Attributes
}

type PatchCurrentTeamRequestBody2 struct {
	Data PatchCurrentTeamData2 `json:"data"`
}

func (o *PatchCurrentTeamRequestBody2) GetData() PatchCurrentTeamData2 {
	if o == nil {
		return PatchCurrentTeamData2{}
	}
	return o.Data
}

type PatchCurrentTeamRequest struct {
	TeamID string                       `pathParam:"style=simple,explode=false,name=team_id"`
	Body   PatchCurrentTeamRequestBody2 `request:"mediaType=application/json"`
}

func (o *PatchCurrentTeamRequest) GetTeamID() string {
	if o == nil {
		return ""
	}
	return o.TeamID
}

func (o *PatchCurrentTeamRequest) GetBody() PatchCurrentTeamRequestBody2 {
	if o == nil {
		return PatchCurrentTeamRequestBody2{}
	}
	return o.Body
}

// PatchCurrentTeamResponseBody - Success
type PatchCurrentTeamResponseBody struct {
	Data *components.Team `json:"data,omitempty"`
}

func (o *PatchCurrentTeamResponseBody) GetData() *components.Team {
	if o == nil {
		return nil
	}
	return o.Data
}

type PatchCurrentTeamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *PatchCurrentTeamResponseBody
}

func (o *PatchCurrentTeamResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PatchCurrentTeamResponse) GetObject() *PatchCurrentTeamResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
