// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"mockserver/internal/sdk/models/components"
)

type UpdatePlansBandwidthType2 string

const (
	UpdatePlansBandwidthType2BandwidthPackages UpdatePlansBandwidthType2 = "bandwidth_packages"
)

func (e UpdatePlansBandwidthType2) ToPointer() *UpdatePlansBandwidthType2 {
	return &e
}
func (e *UpdatePlansBandwidthType2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "bandwidth_packages":
		*e = UpdatePlansBandwidthType2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdatePlansBandwidthType2: %v", v)
	}
}

type UpdatePlansBandwidthAttributes2 struct {
	// The project (ID or Slug) to add bandwidth
	Project *string `json:"project,omitempty"`
	// The total amount you want to have
	Quantity *int64 `json:"quantity,omitempty"`
	// The region to add bandwidth
	RegionSlug *string `json:"region_slug,omitempty"`
}

func (o *UpdatePlansBandwidthAttributes2) GetProject() *string {
	if o == nil {
		return nil
	}
	return o.Project
}

func (o *UpdatePlansBandwidthAttributes2) GetQuantity() *int64 {
	if o == nil {
		return nil
	}
	return o.Quantity
}

func (o *UpdatePlansBandwidthAttributes2) GetRegionSlug() *string {
	if o == nil {
		return nil
	}
	return o.RegionSlug
}

type UpdatePlansBandwidthData2 struct {
	Type       *UpdatePlansBandwidthType2       `json:"type,omitempty"`
	Attributes *UpdatePlansBandwidthAttributes2 `json:"attributes,omitempty"`
}

func (o *UpdatePlansBandwidthData2) GetType() *UpdatePlansBandwidthType2 {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *UpdatePlansBandwidthData2) GetAttributes() *UpdatePlansBandwidthAttributes2 {
	if o == nil {
		return nil
	}
	return o.Attributes
}

type UpdatePlansBandwidthRequest struct {
	Data *UpdatePlansBandwidthData2 `json:"data,omitempty"`
}

func (o *UpdatePlansBandwidthRequest) GetData() *UpdatePlansBandwidthData2 {
	if o == nil {
		return nil
	}
	return o.Data
}

type UpdatePlansBandwidthResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	BandwidthPackages *components.BandwidthPackages
}

func (o *UpdatePlansBandwidthResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdatePlansBandwidthResponse) GetBandwidthPackages() *components.BandwidthPackages {
	if o == nil {
		return nil
	}
	return o.BandwidthPackages
}
