workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Latitudesh-OAS:
        inputs:
            - location: registry.speakeasyapi.dev/latitude/latitude/latitudesh-oas@sha256:fcf9998c0ad491e3876f04f5b2480c95f5a4f8e98bac2906a98f94ebe59d0d8a
        registry:
            location: registry.speakeasyapi.dev/latitude/latitude/latitudesh-oas
targets:
    latitudesh:
        target: typescript
        source: Latitudesh-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/latitude/latitude/latitudesh-oas-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
