workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Latitudesh-OAS:
        inputs:
            - location: registry.speakeasyapi.dev/latitude/latitude/latitudesh-oas:main
        registry:
            location: registry.speakeasyapi.dev/latitude/latitude/latitudesh-oas
targets:
    latitudesh:
        target: typescript
        source: Latitudesh-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/latitude/latitude/latitudesh-oas-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
        testing:
            enabled: true
