/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const CreateBaselineType2 = {
  Baselines: "baselines",
} as const;
export type CreateBaselineType2 = ClosedEnum<typeof CreateBaselineType2>;

/**
 * Expected BIOS settings, keyed by setting id
 */
export type Bios2 = {};

export type CreateBaselineAttributes2 = {
  /**
   * Name of the baseline
   */
  name?: string | undefined;
  /**
   * Description of the baseline
   */
  description?: string | null | undefined;
  /**
   * Slug of the plan this baseline applies to
   */
  plan?: string | undefined;
  /**
   * SSH keys the baseline expects on the server
   */
  sshKeyIds?: Array<string> | undefined;
  /**
   * User data the baseline expects to run on first boot
   */
  userDataId?: string | null | undefined;
  /**
   * Expected disk layout
   */
  diskLayout?: Array<models.BaselineDiskLayoutGroup> | undefined;
  /**
   * Expected BIOS settings, keyed by setting id
   */
  bios?: Bios2 | undefined;
};

export type CreateBaselineData2 = {
  type?: CreateBaselineType2 | undefined;
  attributes?: CreateBaselineAttributes2 | undefined;
};

export type CreateBaselineRequest = {
  data?: CreateBaselineData2 | undefined;
};

/** @internal */
export const CreateBaselineType2$inboundSchema: z.ZodNativeEnum<
  typeof CreateBaselineType2
> = z.nativeEnum(CreateBaselineType2);
/** @internal */
export const CreateBaselineType2$outboundSchema: z.ZodNativeEnum<
  typeof CreateBaselineType2
> = CreateBaselineType2$inboundSchema;

/** @internal */
export const Bios2$inboundSchema: z.ZodType<Bios2, z.ZodTypeDef, unknown> = z
  .object({});
/** @internal */
export type Bios2$Outbound = {};

/** @internal */
export const Bios2$outboundSchema: z.ZodType<
  Bios2$Outbound,
  z.ZodTypeDef,
  Bios2
> = z.object({});

export function bios2ToJSON(bios2: Bios2): string {
  return JSON.stringify(Bios2$outboundSchema.parse(bios2));
}
export function bios2FromJSON(
  jsonString: string,
): SafeParseResult<Bios2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Bios2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Bios2' from JSON`,
  );
}

/** @internal */
export const CreateBaselineAttributes2$inboundSchema: z.ZodType<
  CreateBaselineAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  plan: z.string().optional(),
  ssh_key_ids: z.array(z.string()).optional(),
  user_data_id: z.nullable(z.string()).optional(),
  disk_layout: z.array(models.BaselineDiskLayoutGroup$inboundSchema).optional(),
  bios: z.lazy(() => Bios2$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "ssh_key_ids": "sshKeyIds",
    "user_data_id": "userDataId",
    "disk_layout": "diskLayout",
  });
});
/** @internal */
export type CreateBaselineAttributes2$Outbound = {
  name?: string | undefined;
  description?: string | null | undefined;
  plan?: string | undefined;
  ssh_key_ids?: Array<string> | undefined;
  user_data_id?: string | null | undefined;
  disk_layout?: Array<models.BaselineDiskLayoutGroup$Outbound> | undefined;
  bios?: Bios2$Outbound | undefined;
};

/** @internal */
export const CreateBaselineAttributes2$outboundSchema: z.ZodType<
  CreateBaselineAttributes2$Outbound,
  z.ZodTypeDef,
  CreateBaselineAttributes2
> = z.object({
  name: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  plan: z.string().optional(),
  sshKeyIds: z.array(z.string()).optional(),
  userDataId: z.nullable(z.string()).optional(),
  diskLayout: z.array(models.BaselineDiskLayoutGroup$outboundSchema).optional(),
  bios: z.lazy(() => Bios2$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    sshKeyIds: "ssh_key_ids",
    userDataId: "user_data_id",
    diskLayout: "disk_layout",
  });
});

export function createBaselineAttributes2ToJSON(
  createBaselineAttributes2: CreateBaselineAttributes2,
): string {
  return JSON.stringify(
    CreateBaselineAttributes2$outboundSchema.parse(createBaselineAttributes2),
  );
}
export function createBaselineAttributes2FromJSON(
  jsonString: string,
): SafeParseResult<CreateBaselineAttributes2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBaselineAttributes2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBaselineAttributes2' from JSON`,
  );
}

/** @internal */
export const CreateBaselineData2$inboundSchema: z.ZodType<
  CreateBaselineData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: CreateBaselineType2$inboundSchema.optional(),
  attributes: z.lazy(() => CreateBaselineAttributes2$inboundSchema).optional(),
});
/** @internal */
export type CreateBaselineData2$Outbound = {
  type?: string | undefined;
  attributes?: CreateBaselineAttributes2$Outbound | undefined;
};

/** @internal */
export const CreateBaselineData2$outboundSchema: z.ZodType<
  CreateBaselineData2$Outbound,
  z.ZodTypeDef,
  CreateBaselineData2
> = z.object({
  type: CreateBaselineType2$outboundSchema.optional(),
  attributes: z.lazy(() => CreateBaselineAttributes2$outboundSchema).optional(),
});

export function createBaselineData2ToJSON(
  createBaselineData2: CreateBaselineData2,
): string {
  return JSON.stringify(
    CreateBaselineData2$outboundSchema.parse(createBaselineData2),
  );
}
export function createBaselineData2FromJSON(
  jsonString: string,
): SafeParseResult<CreateBaselineData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBaselineData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBaselineData2' from JSON`,
  );
}

/** @internal */
export const CreateBaselineRequest$inboundSchema: z.ZodType<
  CreateBaselineRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => CreateBaselineData2$inboundSchema).optional(),
});
/** @internal */
export type CreateBaselineRequest$Outbound = {
  data?: CreateBaselineData2$Outbound | undefined;
};

/** @internal */
export const CreateBaselineRequest$outboundSchema: z.ZodType<
  CreateBaselineRequest$Outbound,
  z.ZodTypeDef,
  CreateBaselineRequest
> = z.object({
  data: z.lazy(() => CreateBaselineData2$outboundSchema).optional(),
});

export function createBaselineRequestToJSON(
  createBaselineRequest: CreateBaselineRequest,
): string {
  return JSON.stringify(
    CreateBaselineRequest$outboundSchema.parse(createBaselineRequest),
  );
}
export function createBaselineRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateBaselineRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBaselineRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBaselineRequest' from JSON`,
  );
}
