/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CreateServerReinstallType2 = {
  Reinstalls: "reinstalls",
} as const;
export type CreateServerReinstallType2 = ClosedEnum<
  typeof CreateServerReinstallType2
>;

/**
 * The OS selected for the reinstall process
 */
export const CreateServerReinstallOperatingSystem2 = {
  Centos74X64: "centos_7_4_x64",
  Centos8X64: "centos_8_x64",
  Debian10: "debian_10",
  Debian11: "debian_11",
  Debian12: "debian_12",
  Ipxe: "ipxe",
  Rhel8: "rhel8",
  Rockylinux8: "rockylinux_8",
  Ubuntu22MlInABox: "ubuntu22_ml_in_a_box",
  Ubuntu24MlInABox: "ubuntu24_ml_in_a_box",
  Ubuntu2004X64Lts: "ubuntu_20_04_x64_lts",
  Ubuntu2204X64Lts: "ubuntu_22_04_x64_lts",
  Ubuntu2404X64Lts: "ubuntu_24_04_x64_lts",
  Windows2022Std: "windows_2022_std",
  WindowsServer2019StdV1: "windows_server_2019_std_v1",
} as const;
/**
 * The OS selected for the reinstall process
 */
export type CreateServerReinstallOperatingSystem2 = ClosedEnum<
  typeof CreateServerReinstallOperatingSystem2
>;

export type CreateServerReinstallPartition2 = {
  sizeInGb?: number | undefined;
  path?: string | undefined;
  filesystemType?: string | undefined;
};

/**
 * RAID mode for the server. Set to 'raid-0' for RAID 0, 'raid-1' for RAID 1, or omit/null for no RAID configuration
 */
export const CreateServerReinstallRaid2 = {
  Raid0: "raid-0",
  Raid1: "raid-1",
} as const;
/**
 * RAID mode for the server. Set to 'raid-0' for RAID 0, 'raid-1' for RAID 1, or omit/null for no RAID configuration
 */
export type CreateServerReinstallRaid2 = ClosedEnum<
  typeof CreateServerReinstallRaid2
>;

export type CreateServerReinstallAttributes2 = {
  /**
   * The OS selected for the reinstall process
   */
  operatingSystem?: CreateServerReinstallOperatingSystem2 | undefined;
  /**
   * The server hostname to set upon reinstall
   */
  hostname?: string | undefined;
  partitions?: Array<CreateServerReinstallPartition2> | undefined;
  /**
   * SSH Key IDs to set upon reinstall
   */
  sshKeys?: Array<string> | undefined;
  /**
   * User data ID to set upon reinstall
   */
  userData?: string | undefined;
  /**
   * RAID mode for the server. Set to 'raid-0' for RAID 0, 'raid-1' for RAID 1, or omit/null for no RAID configuration
   */
  raid?: CreateServerReinstallRaid2 | undefined;
  /**
   * URL where iPXE script is stored on, OR the iPXE script encoded in base64. This attribute is required when operating system iPXE is selected.
   */
  ipxe?: string | undefined;
};

export type CreateServerReinstallData2 = {
  type: CreateServerReinstallType2;
  attributes?: CreateServerReinstallAttributes2 | undefined;
};

export type CreateServerReinstallRequestBody2 = {
  data: CreateServerReinstallData2;
};

export type CreateServerReinstallRequest = {
  serverId: string;
  requestBody: CreateServerReinstallRequestBody2;
};

/** @internal */
export const CreateServerReinstallType2$inboundSchema: z.ZodNativeEnum<
  typeof CreateServerReinstallType2
> = z.nativeEnum(CreateServerReinstallType2);
/** @internal */
export const CreateServerReinstallType2$outboundSchema: z.ZodNativeEnum<
  typeof CreateServerReinstallType2
> = CreateServerReinstallType2$inboundSchema;

/** @internal */
export const CreateServerReinstallOperatingSystem2$inboundSchema:
  z.ZodNativeEnum<typeof CreateServerReinstallOperatingSystem2> = z.nativeEnum(
    CreateServerReinstallOperatingSystem2,
  );
/** @internal */
export const CreateServerReinstallOperatingSystem2$outboundSchema:
  z.ZodNativeEnum<typeof CreateServerReinstallOperatingSystem2> =
    CreateServerReinstallOperatingSystem2$inboundSchema;

/** @internal */
export const CreateServerReinstallPartition2$inboundSchema: z.ZodType<
  CreateServerReinstallPartition2,
  z.ZodTypeDef,
  unknown
> = z.object({
  size_in_gb: z.number().int().optional(),
  path: z.string().optional(),
  filesystem_type: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "size_in_gb": "sizeInGb",
    "filesystem_type": "filesystemType",
  });
});
/** @internal */
export type CreateServerReinstallPartition2$Outbound = {
  size_in_gb?: number | undefined;
  path?: string | undefined;
  filesystem_type?: string | undefined;
};

/** @internal */
export const CreateServerReinstallPartition2$outboundSchema: z.ZodType<
  CreateServerReinstallPartition2$Outbound,
  z.ZodTypeDef,
  CreateServerReinstallPartition2
> = z.object({
  sizeInGb: z.number().int().optional(),
  path: z.string().optional(),
  filesystemType: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    sizeInGb: "size_in_gb",
    filesystemType: "filesystem_type",
  });
});

export function createServerReinstallPartition2ToJSON(
  createServerReinstallPartition2: CreateServerReinstallPartition2,
): string {
  return JSON.stringify(
    CreateServerReinstallPartition2$outboundSchema.parse(
      createServerReinstallPartition2,
    ),
  );
}
export function createServerReinstallPartition2FromJSON(
  jsonString: string,
): SafeParseResult<CreateServerReinstallPartition2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateServerReinstallPartition2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateServerReinstallPartition2' from JSON`,
  );
}

/** @internal */
export const CreateServerReinstallRaid2$inboundSchema: z.ZodNativeEnum<
  typeof CreateServerReinstallRaid2
> = z.nativeEnum(CreateServerReinstallRaid2);
/** @internal */
export const CreateServerReinstallRaid2$outboundSchema: z.ZodNativeEnum<
  typeof CreateServerReinstallRaid2
> = CreateServerReinstallRaid2$inboundSchema;

/** @internal */
export const CreateServerReinstallAttributes2$inboundSchema: z.ZodType<
  CreateServerReinstallAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  operating_system: CreateServerReinstallOperatingSystem2$inboundSchema
    .optional(),
  hostname: z.string().optional(),
  partitions: z.array(
    z.lazy(() => CreateServerReinstallPartition2$inboundSchema),
  ).optional(),
  ssh_keys: z.array(z.string()).optional(),
  user_data: z.string().optional(),
  raid: CreateServerReinstallRaid2$inboundSchema.optional(),
  ipxe: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "operating_system": "operatingSystem",
    "ssh_keys": "sshKeys",
    "user_data": "userData",
  });
});
/** @internal */
export type CreateServerReinstallAttributes2$Outbound = {
  operating_system?: string | undefined;
  hostname?: string | undefined;
  partitions?: Array<CreateServerReinstallPartition2$Outbound> | undefined;
  ssh_keys?: Array<string> | undefined;
  user_data?: string | undefined;
  raid?: string | undefined;
  ipxe?: string | undefined;
};

/** @internal */
export const CreateServerReinstallAttributes2$outboundSchema: z.ZodType<
  CreateServerReinstallAttributes2$Outbound,
  z.ZodTypeDef,
  CreateServerReinstallAttributes2
> = z.object({
  operatingSystem: CreateServerReinstallOperatingSystem2$outboundSchema
    .optional(),
  hostname: z.string().optional(),
  partitions: z.array(
    z.lazy(() => CreateServerReinstallPartition2$outboundSchema),
  ).optional(),
  sshKeys: z.array(z.string()).optional(),
  userData: z.string().optional(),
  raid: CreateServerReinstallRaid2$outboundSchema.optional(),
  ipxe: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    operatingSystem: "operating_system",
    sshKeys: "ssh_keys",
    userData: "user_data",
  });
});

export function createServerReinstallAttributes2ToJSON(
  createServerReinstallAttributes2: CreateServerReinstallAttributes2,
): string {
  return JSON.stringify(
    CreateServerReinstallAttributes2$outboundSchema.parse(
      createServerReinstallAttributes2,
    ),
  );
}
export function createServerReinstallAttributes2FromJSON(
  jsonString: string,
): SafeParseResult<CreateServerReinstallAttributes2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateServerReinstallAttributes2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateServerReinstallAttributes2' from JSON`,
  );
}

/** @internal */
export const CreateServerReinstallData2$inboundSchema: z.ZodType<
  CreateServerReinstallData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: CreateServerReinstallType2$inboundSchema,
  attributes: z.lazy(() => CreateServerReinstallAttributes2$inboundSchema)
    .optional(),
});
/** @internal */
export type CreateServerReinstallData2$Outbound = {
  type: string;
  attributes?: CreateServerReinstallAttributes2$Outbound | undefined;
};

/** @internal */
export const CreateServerReinstallData2$outboundSchema: z.ZodType<
  CreateServerReinstallData2$Outbound,
  z.ZodTypeDef,
  CreateServerReinstallData2
> = z.object({
  type: CreateServerReinstallType2$outboundSchema,
  attributes: z.lazy(() => CreateServerReinstallAttributes2$outboundSchema)
    .optional(),
});

export function createServerReinstallData2ToJSON(
  createServerReinstallData2: CreateServerReinstallData2,
): string {
  return JSON.stringify(
    CreateServerReinstallData2$outboundSchema.parse(createServerReinstallData2),
  );
}
export function createServerReinstallData2FromJSON(
  jsonString: string,
): SafeParseResult<CreateServerReinstallData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateServerReinstallData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateServerReinstallData2' from JSON`,
  );
}

/** @internal */
export const CreateServerReinstallRequestBody2$inboundSchema: z.ZodType<
  CreateServerReinstallRequestBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => CreateServerReinstallData2$inboundSchema),
});
/** @internal */
export type CreateServerReinstallRequestBody2$Outbound = {
  data: CreateServerReinstallData2$Outbound;
};

/** @internal */
export const CreateServerReinstallRequestBody2$outboundSchema: z.ZodType<
  CreateServerReinstallRequestBody2$Outbound,
  z.ZodTypeDef,
  CreateServerReinstallRequestBody2
> = z.object({
  data: z.lazy(() => CreateServerReinstallData2$outboundSchema),
});

export function createServerReinstallRequestBody2ToJSON(
  createServerReinstallRequestBody2: CreateServerReinstallRequestBody2,
): string {
  return JSON.stringify(
    CreateServerReinstallRequestBody2$outboundSchema.parse(
      createServerReinstallRequestBody2,
    ),
  );
}
export function createServerReinstallRequestBody2FromJSON(
  jsonString: string,
): SafeParseResult<CreateServerReinstallRequestBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateServerReinstallRequestBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateServerReinstallRequestBody2' from JSON`,
  );
}

/** @internal */
export const CreateServerReinstallRequest$inboundSchema: z.ZodType<
  CreateServerReinstallRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  server_id: z.string(),
  RequestBody: z.lazy(() => CreateServerReinstallRequestBody2$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "server_id": "serverId",
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type CreateServerReinstallRequest$Outbound = {
  server_id: string;
  RequestBody: CreateServerReinstallRequestBody2$Outbound;
};

/** @internal */
export const CreateServerReinstallRequest$outboundSchema: z.ZodType<
  CreateServerReinstallRequest$Outbound,
  z.ZodTypeDef,
  CreateServerReinstallRequest
> = z.object({
  serverId: z.string(),
  requestBody: z.lazy(() => CreateServerReinstallRequestBody2$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    serverId: "server_id",
    requestBody: "RequestBody",
  });
});

export function createServerReinstallRequestToJSON(
  createServerReinstallRequest: CreateServerReinstallRequest,
): string {
  return JSON.stringify(
    CreateServerReinstallRequest$outboundSchema.parse(
      createServerReinstallRequest,
    ),
  );
}
export function createServerReinstallRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateServerReinstallRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateServerReinstallRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateServerReinstallRequest' from JSON`,
  );
}
