/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CreateVirtualMachineActionType2 = {
  VirtualMachines: "virtual_machines",
} as const;
export type CreateVirtualMachineActionType2 = ClosedEnum<
  typeof CreateVirtualMachineActionType2
>;

/**
 * The action to perform on the virtual machine
 */
export const CreateVirtualMachineActionAction2 = {
  PowerOn: "power_on",
  PowerOff: "power_off",
  Reboot: "reboot",
} as const;
/**
 * The action to perform on the virtual machine
 */
export type CreateVirtualMachineActionAction2 = ClosedEnum<
  typeof CreateVirtualMachineActionAction2
>;

export type CreateVirtualMachineActionAttributes2 = {
  /**
   * The action to perform on the virtual machine
   */
  action: CreateVirtualMachineActionAction2;
};

export type CreateVirtualMachineActionRequestBody2 = {
  id: string;
  type: CreateVirtualMachineActionType2;
  attributes: CreateVirtualMachineActionAttributes2;
};

export type CreateVirtualMachineActionRequest = {
  virtualMachineId: string;
  requestBody: CreateVirtualMachineActionRequestBody2;
};

/** @internal */
export const CreateVirtualMachineActionType2$inboundSchema: z.ZodNativeEnum<
  typeof CreateVirtualMachineActionType2
> = z.nativeEnum(CreateVirtualMachineActionType2);
/** @internal */
export const CreateVirtualMachineActionType2$outboundSchema: z.ZodNativeEnum<
  typeof CreateVirtualMachineActionType2
> = CreateVirtualMachineActionType2$inboundSchema;

/** @internal */
export const CreateVirtualMachineActionAction2$inboundSchema: z.ZodNativeEnum<
  typeof CreateVirtualMachineActionAction2
> = z.nativeEnum(CreateVirtualMachineActionAction2);
/** @internal */
export const CreateVirtualMachineActionAction2$outboundSchema: z.ZodNativeEnum<
  typeof CreateVirtualMachineActionAction2
> = CreateVirtualMachineActionAction2$inboundSchema;

/** @internal */
export const CreateVirtualMachineActionAttributes2$inboundSchema: z.ZodType<
  CreateVirtualMachineActionAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  action: CreateVirtualMachineActionAction2$inboundSchema,
});
/** @internal */
export type CreateVirtualMachineActionAttributes2$Outbound = {
  action: string;
};

/** @internal */
export const CreateVirtualMachineActionAttributes2$outboundSchema: z.ZodType<
  CreateVirtualMachineActionAttributes2$Outbound,
  z.ZodTypeDef,
  CreateVirtualMachineActionAttributes2
> = z.object({
  action: CreateVirtualMachineActionAction2$outboundSchema,
});

export function createVirtualMachineActionAttributes2ToJSON(
  createVirtualMachineActionAttributes2: CreateVirtualMachineActionAttributes2,
): string {
  return JSON.stringify(
    CreateVirtualMachineActionAttributes2$outboundSchema.parse(
      createVirtualMachineActionAttributes2,
    ),
  );
}
export function createVirtualMachineActionAttributes2FromJSON(
  jsonString: string,
): SafeParseResult<CreateVirtualMachineActionAttributes2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateVirtualMachineActionAttributes2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateVirtualMachineActionAttributes2' from JSON`,
  );
}

/** @internal */
export const CreateVirtualMachineActionRequestBody2$inboundSchema: z.ZodType<
  CreateVirtualMachineActionRequestBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: CreateVirtualMachineActionType2$inboundSchema,
  attributes: z.lazy(() => CreateVirtualMachineActionAttributes2$inboundSchema),
});
/** @internal */
export type CreateVirtualMachineActionRequestBody2$Outbound = {
  id: string;
  type: string;
  attributes: CreateVirtualMachineActionAttributes2$Outbound;
};

/** @internal */
export const CreateVirtualMachineActionRequestBody2$outboundSchema: z.ZodType<
  CreateVirtualMachineActionRequestBody2$Outbound,
  z.ZodTypeDef,
  CreateVirtualMachineActionRequestBody2
> = z.object({
  id: z.string(),
  type: CreateVirtualMachineActionType2$outboundSchema,
  attributes: z.lazy(() =>
    CreateVirtualMachineActionAttributes2$outboundSchema
  ),
});

export function createVirtualMachineActionRequestBody2ToJSON(
  createVirtualMachineActionRequestBody2:
    CreateVirtualMachineActionRequestBody2,
): string {
  return JSON.stringify(
    CreateVirtualMachineActionRequestBody2$outboundSchema.parse(
      createVirtualMachineActionRequestBody2,
    ),
  );
}
export function createVirtualMachineActionRequestBody2FromJSON(
  jsonString: string,
): SafeParseResult<CreateVirtualMachineActionRequestBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateVirtualMachineActionRequestBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateVirtualMachineActionRequestBody2' from JSON`,
  );
}

/** @internal */
export const CreateVirtualMachineActionRequest$inboundSchema: z.ZodType<
  CreateVirtualMachineActionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  virtual_machine_id: z.string(),
  RequestBody: z.lazy(() =>
    CreateVirtualMachineActionRequestBody2$inboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    "virtual_machine_id": "virtualMachineId",
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type CreateVirtualMachineActionRequest$Outbound = {
  virtual_machine_id: string;
  RequestBody: CreateVirtualMachineActionRequestBody2$Outbound;
};

/** @internal */
export const CreateVirtualMachineActionRequest$outboundSchema: z.ZodType<
  CreateVirtualMachineActionRequest$Outbound,
  z.ZodTypeDef,
  CreateVirtualMachineActionRequest
> = z.object({
  virtualMachineId: z.string(),
  requestBody: z.lazy(() =>
    CreateVirtualMachineActionRequestBody2$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    virtualMachineId: "virtual_machine_id",
    requestBody: "RequestBody",
  });
});

export function createVirtualMachineActionRequestToJSON(
  createVirtualMachineActionRequest: CreateVirtualMachineActionRequest,
): string {
  return JSON.stringify(
    CreateVirtualMachineActionRequest$outboundSchema.parse(
      createVirtualMachineActionRequest,
    ),
  );
}
export function createVirtualMachineActionRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateVirtualMachineActionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateVirtualMachineActionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateVirtualMachineActionRequest' from JSON`,
  );
}
