/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CreateServerType2 = {
  Servers: "servers",
} as const;
export type CreateServerType2 = ClosedEnum<typeof CreateServerType2>;

/**
 * The plan slug to choose server from, defining the specs the server will have
 */
export const Plan2 = {
  C2LargeX86: "c2-large-x86",
  C2MediumX86: "c2-medium-x86",
  C2SmallX86: "c2-small-x86",
  C3LargeX86: "c3-large-x86",
  C3MediumX86: "c3-medium-x86",
  C3SmallX86: "c3-small-x86",
  C3XlargeX86: "c3-xlarge-x86",
  G3Gh200: "g3-gh200",
  G3LargeX86: "g3-large-x86",
  G3MediumX86: "g3-medium-x86",
  G3SmallX86: "g3-small-x86",
  G3XlargeX86: "g3-xlarge-x86",
  G4Rtx6kproLarge: "g4-rtx6kpro-large",
  M3LargeX86: "m3-large-x86",
  M4MetalLarge: "m4-metal-large",
  M4MetalSmall: "m4-metal-small",
  Rs4MetalXlarge: "rs4-metal-xlarge",
  S2SmallX86: "s2-small-x86",
  S3LargeX86: "s3-large-x86",
} as const;
/**
 * The plan slug to choose server from, defining the specs the server will have
 */
export type Plan2 = ClosedEnum<typeof Plan2>;

/**
 * The site slug to deploy the server
 */
export const CreateServerSite2 = {
  Ash: "ASH",
  Bue: "BUE",
  Chi: "CHI",
  Dal: "DAL",
  Fra: "FRA",
  Lax: "LAX",
  Lon: "LON",
  Mex: "MEX",
  Mex2: "MEX2",
  Mia: "MIA",
  Mia2: "MIA2",
  Nyc: "NYC",
  Sao: "SAO",
  Sao2: "SAO2",
  Sgp: "SGP",
  Syd: "SYD",
  Tyo: "TYO",
  Tyo2: "TYO2",
} as const;
/**
 * The site slug to deploy the server
 */
export type CreateServerSite2 = ClosedEnum<typeof CreateServerSite2>;

/**
 * The operating system slug for the new server
 */
export const CreateServerOperatingSystem2 = {
  Centos74X64: "centos_7_4_x64",
  Centos8X64: "centos_8_x64",
  Debian10: "debian_10",
  Debian11: "debian_11",
  Debian12: "debian_12",
  Ipxe: "ipxe",
  Rhel8: "rhel8",
  Rockylinux8: "rockylinux_8",
  Ubuntu22MlInABox: "ubuntu22_ml_in_a_box",
  Ubuntu24MlInABox: "ubuntu24_ml_in_a_box",
  Ubuntu2004X64Lts: "ubuntu_20_04_x64_lts",
  Ubuntu2204X64Lts: "ubuntu_22_04_x64_lts",
  Ubuntu2404X64Lts: "ubuntu_24_04_x64_lts",
  Windows2022Std: "windows_2022_std",
  WindowsServer2019StdV1: "windows_server_2019_std_v1",
} as const;
/**
 * The operating system slug for the new server
 */
export type CreateServerOperatingSystem2 = ClosedEnum<
  typeof CreateServerOperatingSystem2
>;

/**
 * RAID mode for the server. Set to 'raid-0' for RAID 0, 'raid-1' for RAID 1, or omit/null for no RAID configuration
 */
export const CreateServerRaid2 = {
  Raid0: "raid-0",
  Raid1: "raid-1",
} as const;
/**
 * RAID mode for the server. Set to 'raid-0' for RAID 0, 'raid-1' for RAID 1, or omit/null for no RAID configuration
 */
export type CreateServerRaid2 = ClosedEnum<typeof CreateServerRaid2>;

/**
 * The server billing type. Accepts `hourly` and `monthly` for on demand projects and `yearly` for reserved projects.
 */
export const CreateServerBilling2 = {
  Hourly: "hourly",
  Monthly: "monthly",
  Yearly: "yearly",
} as const;
/**
 * The server billing type. Accepts `hourly` and `monthly` for on demand projects and `yearly` for reserved projects.
 */
export type CreateServerBilling2 = ClosedEnum<typeof CreateServerBilling2>;

export type CreateServerAttributes2 = {
  /**
   * The project (ID or Slug) to deploy the server
   */
  project?: string | undefined;
  /**
   * The plan slug to choose server from, defining the specs the server will have
   */
  plan?: Plan2 | undefined;
  /**
   * The site slug to deploy the server
   */
  site?: CreateServerSite2 | undefined;
  /**
   * The operating system slug for the new server
   */
  operatingSystem?: CreateServerOperatingSystem2 | undefined;
  /**
   * The server hostname
   */
  hostname?: string | undefined;
  /**
   * SSH Keys to set on the server
   */
  sshKeys?: Array<string> | undefined;
  /**
   * User data ID to set on the server. This is a custom script that will run after the deploy
   */
  userData?: string | undefined;
  /**
   * RAID mode for the server. Set to 'raid-0' for RAID 0, 'raid-1' for RAID 1, or omit/null for no RAID configuration
   */
  raid?: CreateServerRaid2 | undefined;
  /**
   * URL where iPXE script is stored on, OR the iPXE script encoded in base64. This attribute is required when iPXE is selected as operating system.
   */
  ipxe?: string | undefined;
  /**
   * The server billing type. Accepts `hourly` and `monthly` for on demand projects and `yearly` for reserved projects.
   */
  billing?: CreateServerBilling2 | undefined;
};

export type CreateServerData2 = {
  type: CreateServerType2;
  attributes?: CreateServerAttributes2 | undefined;
};

export type CreateServerRequest = {
  data?: CreateServerData2 | undefined;
};

/** @internal */
export const CreateServerType2$inboundSchema: z.ZodNativeEnum<
  typeof CreateServerType2
> = z.nativeEnum(CreateServerType2);
/** @internal */
export const CreateServerType2$outboundSchema: z.ZodNativeEnum<
  typeof CreateServerType2
> = CreateServerType2$inboundSchema;

/** @internal */
export const Plan2$inboundSchema: z.ZodNativeEnum<typeof Plan2> = z.nativeEnum(
  Plan2,
);
/** @internal */
export const Plan2$outboundSchema: z.ZodNativeEnum<typeof Plan2> =
  Plan2$inboundSchema;

/** @internal */
export const CreateServerSite2$inboundSchema: z.ZodNativeEnum<
  typeof CreateServerSite2
> = z.nativeEnum(CreateServerSite2);
/** @internal */
export const CreateServerSite2$outboundSchema: z.ZodNativeEnum<
  typeof CreateServerSite2
> = CreateServerSite2$inboundSchema;

/** @internal */
export const CreateServerOperatingSystem2$inboundSchema: z.ZodNativeEnum<
  typeof CreateServerOperatingSystem2
> = z.nativeEnum(CreateServerOperatingSystem2);
/** @internal */
export const CreateServerOperatingSystem2$outboundSchema: z.ZodNativeEnum<
  typeof CreateServerOperatingSystem2
> = CreateServerOperatingSystem2$inboundSchema;

/** @internal */
export const CreateServerRaid2$inboundSchema: z.ZodNativeEnum<
  typeof CreateServerRaid2
> = z.nativeEnum(CreateServerRaid2);
/** @internal */
export const CreateServerRaid2$outboundSchema: z.ZodNativeEnum<
  typeof CreateServerRaid2
> = CreateServerRaid2$inboundSchema;

/** @internal */
export const CreateServerBilling2$inboundSchema: z.ZodNativeEnum<
  typeof CreateServerBilling2
> = z.nativeEnum(CreateServerBilling2);
/** @internal */
export const CreateServerBilling2$outboundSchema: z.ZodNativeEnum<
  typeof CreateServerBilling2
> = CreateServerBilling2$inboundSchema;

/** @internal */
export const CreateServerAttributes2$inboundSchema: z.ZodType<
  CreateServerAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  project: z.string().optional(),
  plan: Plan2$inboundSchema.optional(),
  site: CreateServerSite2$inboundSchema.optional(),
  operating_system: CreateServerOperatingSystem2$inboundSchema.optional(),
  hostname: z.string().optional(),
  ssh_keys: z.array(z.string()).optional(),
  user_data: z.string().optional(),
  raid: CreateServerRaid2$inboundSchema.optional(),
  ipxe: z.string().optional(),
  billing: CreateServerBilling2$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "operating_system": "operatingSystem",
    "ssh_keys": "sshKeys",
    "user_data": "userData",
  });
});
/** @internal */
export type CreateServerAttributes2$Outbound = {
  project?: string | undefined;
  plan?: string | undefined;
  site?: string | undefined;
  operating_system?: string | undefined;
  hostname?: string | undefined;
  ssh_keys?: Array<string> | undefined;
  user_data?: string | undefined;
  raid?: string | undefined;
  ipxe?: string | undefined;
  billing?: string | undefined;
};

/** @internal */
export const CreateServerAttributes2$outboundSchema: z.ZodType<
  CreateServerAttributes2$Outbound,
  z.ZodTypeDef,
  CreateServerAttributes2
> = z.object({
  project: z.string().optional(),
  plan: Plan2$outboundSchema.optional(),
  site: CreateServerSite2$outboundSchema.optional(),
  operatingSystem: CreateServerOperatingSystem2$outboundSchema.optional(),
  hostname: z.string().optional(),
  sshKeys: z.array(z.string()).optional(),
  userData: z.string().optional(),
  raid: CreateServerRaid2$outboundSchema.optional(),
  ipxe: z.string().optional(),
  billing: CreateServerBilling2$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    operatingSystem: "operating_system",
    sshKeys: "ssh_keys",
    userData: "user_data",
  });
});

export function createServerAttributes2ToJSON(
  createServerAttributes2: CreateServerAttributes2,
): string {
  return JSON.stringify(
    CreateServerAttributes2$outboundSchema.parse(createServerAttributes2),
  );
}
export function createServerAttributes2FromJSON(
  jsonString: string,
): SafeParseResult<CreateServerAttributes2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateServerAttributes2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateServerAttributes2' from JSON`,
  );
}

/** @internal */
export const CreateServerData2$inboundSchema: z.ZodType<
  CreateServerData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: CreateServerType2$inboundSchema,
  attributes: z.lazy(() => CreateServerAttributes2$inboundSchema).optional(),
});
/** @internal */
export type CreateServerData2$Outbound = {
  type: string;
  attributes?: CreateServerAttributes2$Outbound | undefined;
};

/** @internal */
export const CreateServerData2$outboundSchema: z.ZodType<
  CreateServerData2$Outbound,
  z.ZodTypeDef,
  CreateServerData2
> = z.object({
  type: CreateServerType2$outboundSchema,
  attributes: z.lazy(() => CreateServerAttributes2$outboundSchema).optional(),
});

export function createServerData2ToJSON(
  createServerData2: CreateServerData2,
): string {
  return JSON.stringify(
    CreateServerData2$outboundSchema.parse(createServerData2),
  );
}
export function createServerData2FromJSON(
  jsonString: string,
): SafeParseResult<CreateServerData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateServerData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateServerData2' from JSON`,
  );
}

/** @internal */
export const CreateServerRequest$inboundSchema: z.ZodType<
  CreateServerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => CreateServerData2$inboundSchema).optional(),
});
/** @internal */
export type CreateServerRequest$Outbound = {
  data?: CreateServerData2$Outbound | undefined;
};

/** @internal */
export const CreateServerRequest$outboundSchema: z.ZodType<
  CreateServerRequest$Outbound,
  z.ZodTypeDef,
  CreateServerRequest
> = z.object({
  data: z.lazy(() => CreateServerData2$outboundSchema).optional(),
});

export function createServerRequestToJSON(
  createServerRequest: CreateServerRequest,
): string {
  return JSON.stringify(
    CreateServerRequest$outboundSchema.parse(createServerRequest),
  );
}
export function createServerRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateServerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateServerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateServerRequest' from JSON`,
  );
}
