/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteFilesystemRequest = {
  filesystemId: string;
};

/** @internal */
export const DeleteFilesystemRequest$inboundSchema: z.ZodType<
  DeleteFilesystemRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  filesystem_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "filesystem_id": "filesystemId",
  });
});
/** @internal */
export type DeleteFilesystemRequest$Outbound = {
  filesystem_id: string;
};

/** @internal */
export const DeleteFilesystemRequest$outboundSchema: z.ZodType<
  DeleteFilesystemRequest$Outbound,
  z.ZodTypeDef,
  DeleteFilesystemRequest
> = z.object({
  filesystemId: z.string(),
}).transform((v) => {
  return remap$(v, {
    filesystemId: "filesystem_id",
  });
});

export function deleteFilesystemRequestToJSON(
  deleteFilesystemRequest: DeleteFilesystemRequest,
): string {
  return JSON.stringify(
    DeleteFilesystemRequest$outboundSchema.parse(deleteFilesystemRequest),
  );
}
export function deleteFilesystemRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteFilesystemRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteFilesystemRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteFilesystemRequest' from JSON`,
  );
}
