/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteLksClusterRequest = {
  /**
   * The cluster ID (format: `lksc_<hash>`).
   */
  id: string;
};

/** @internal */
export const DeleteLksClusterRequest$inboundSchema: z.ZodType<
  DeleteLksClusterRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type DeleteLksClusterRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteLksClusterRequest$outboundSchema: z.ZodType<
  DeleteLksClusterRequest$Outbound,
  z.ZodTypeDef,
  DeleteLksClusterRequest
> = z.object({
  id: z.string(),
});

export function deleteLksClusterRequestToJSON(
  deleteLksClusterRequest: DeleteLksClusterRequest,
): string {
  return JSON.stringify(
    DeleteLksClusterRequest$outboundSchema.parse(deleteLksClusterRequest),
  );
}
export function deleteLksClusterRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteLksClusterRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteLksClusterRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteLksClusterRequest' from JSON`,
  );
}
