/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteStorageFilesystemsRequest = {
  filesystemId: string;
};

/** @internal */
export const DeleteStorageFilesystemsRequest$inboundSchema: z.ZodType<
  DeleteStorageFilesystemsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  filesystem_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "filesystem_id": "filesystemId",
  });
});
/** @internal */
export type DeleteStorageFilesystemsRequest$Outbound = {
  filesystem_id: string;
};

/** @internal */
export const DeleteStorageFilesystemsRequest$outboundSchema: z.ZodType<
  DeleteStorageFilesystemsRequest$Outbound,
  z.ZodTypeDef,
  DeleteStorageFilesystemsRequest
> = z.object({
  filesystemId: z.string(),
}).transform((v) => {
  return remap$(v, {
    filesystemId: "filesystem_id",
  });
});

export function deleteStorageFilesystemsRequestToJSON(
  deleteStorageFilesystemsRequest: DeleteStorageFilesystemsRequest,
): string {
  return JSON.stringify(
    DeleteStorageFilesystemsRequest$outboundSchema.parse(
      deleteStorageFilesystemsRequest,
    ),
  );
}
export function deleteStorageFilesystemsRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteStorageFilesystemsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteStorageFilesystemsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteStorageFilesystemsRequest' from JSON`,
  );
}
