/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteElasticIpBgpSessionRequest = {
  elasticIpId: string;
  id: string;
  force?: boolean | undefined;
};

/** @internal */
export const DeleteElasticIpBgpSessionRequest$inboundSchema: z.ZodType<
  DeleteElasticIpBgpSessionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  elastic_ip_id: z.string(),
  id: z.string(),
  force: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "elastic_ip_id": "elasticIpId",
  });
});
/** @internal */
export type DeleteElasticIpBgpSessionRequest$Outbound = {
  elastic_ip_id: string;
  id: string;
  force?: boolean | undefined;
};

/** @internal */
export const DeleteElasticIpBgpSessionRequest$outboundSchema: z.ZodType<
  DeleteElasticIpBgpSessionRequest$Outbound,
  z.ZodTypeDef,
  DeleteElasticIpBgpSessionRequest
> = z.object({
  elasticIpId: z.string(),
  id: z.string(),
  force: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    elasticIpId: "elastic_ip_id",
  });
});

export function deleteElasticIpBgpSessionRequestToJSON(
  deleteElasticIpBgpSessionRequest: DeleteElasticIpBgpSessionRequest,
): string {
  return JSON.stringify(
    DeleteElasticIpBgpSessionRequest$outboundSchema.parse(
      deleteElasticIpBgpSessionRequest,
    ),
  );
}
export function deleteElasticIpBgpSessionRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteElasticIpBgpSessionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteElasticIpBgpSessionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteElasticIpBgpSessionRequest' from JSON`,
  );
}
