/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteLksNodePoolRequest = {
  /**
   * The cluster ID (format: `lksc_<hash>`).
   */
  clusterId: string;
  /**
   * The node pool ID (format: `lksnp_<hash>`).
   */
  id: string;
};

/** @internal */
export const DeleteLksNodePoolRequest$inboundSchema: z.ZodType<
  DeleteLksNodePoolRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  cluster_id: z.string(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "cluster_id": "clusterId",
  });
});
/** @internal */
export type DeleteLksNodePoolRequest$Outbound = {
  cluster_id: string;
  id: string;
};

/** @internal */
export const DeleteLksNodePoolRequest$outboundSchema: z.ZodType<
  DeleteLksNodePoolRequest$Outbound,
  z.ZodTypeDef,
  DeleteLksNodePoolRequest
> = z.object({
  clusterId: z.string(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    clusterId: "cluster_id",
  });
});

export function deleteLksNodePoolRequestToJSON(
  deleteLksNodePoolRequest: DeleteLksNodePoolRequest,
): string {
  return JSON.stringify(
    DeleteLksNodePoolRequest$outboundSchema.parse(deleteLksNodePoolRequest),
  );
}
export function deleteLksNodePoolRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteLksNodePoolRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteLksNodePoolRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteLksNodePoolRequest' from JSON`,
  );
}
