/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DestroyTagRequest = {
  tagId: string;
};

/** @internal */
export const DestroyTagRequest$inboundSchema: z.ZodType<
  DestroyTagRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  tag_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "tag_id": "tagId",
  });
});
/** @internal */
export type DestroyTagRequest$Outbound = {
  tag_id: string;
};

/** @internal */
export const DestroyTagRequest$outboundSchema: z.ZodType<
  DestroyTagRequest$Outbound,
  z.ZodTypeDef,
  DestroyTagRequest
> = z.object({
  tagId: z.string(),
}).transform((v) => {
  return remap$(v, {
    tagId: "tag_id",
  });
});

export function destroyTagRequestToJSON(
  destroyTagRequest: DestroyTagRequest,
): string {
  return JSON.stringify(
    DestroyTagRequest$outboundSchema.parse(destroyTagRequest),
  );
}
export function destroyTagRequestFromJSON(
  jsonString: string,
): SafeParseResult<DestroyTagRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestroyTagRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestroyTagRequest' from JSON`,
  );
}
