/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DestroyVirtualNetworkRequest = {
  /**
   * The virtual network ID
   */
  vlanId: string;
};

/** @internal */
export const DestroyVirtualNetworkRequest$inboundSchema: z.ZodType<
  DestroyVirtualNetworkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  vlan_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "vlan_id": "vlanId",
  });
});
/** @internal */
export type DestroyVirtualNetworkRequest$Outbound = {
  vlan_id: string;
};

/** @internal */
export const DestroyVirtualNetworkRequest$outboundSchema: z.ZodType<
  DestroyVirtualNetworkRequest$Outbound,
  z.ZodTypeDef,
  DestroyVirtualNetworkRequest
> = z.object({
  vlanId: z.string(),
}).transform((v) => {
  return remap$(v, {
    vlanId: "vlan_id",
  });
});

export function destroyVirtualNetworkRequestToJSON(
  destroyVirtualNetworkRequest: DestroyVirtualNetworkRequest,
): string {
  return JSON.stringify(
    DestroyVirtualNetworkRequest$outboundSchema.parse(
      destroyVirtualNetworkRequest,
    ),
  );
}
export function destroyVirtualNetworkRequestFromJSON(
  jsonString: string,
): SafeParseResult<DestroyVirtualNetworkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestroyVirtualNetworkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestroyVirtualNetworkRequest' from JSON`,
  );
}
