/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DestroyTeamMemberRequest = {
  /**
   * The user ID
   */
  userId: string;
};

/** @internal */
export const DestroyTeamMemberRequest$inboundSchema: z.ZodType<
  DestroyTeamMemberRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "user_id": "userId",
  });
});
/** @internal */
export type DestroyTeamMemberRequest$Outbound = {
  user_id: string;
};

/** @internal */
export const DestroyTeamMemberRequest$outboundSchema: z.ZodType<
  DestroyTeamMemberRequest$Outbound,
  z.ZodTypeDef,
  DestroyTeamMemberRequest
> = z.object({
  userId: z.string(),
}).transform((v) => {
  return remap$(v, {
    userId: "user_id",
  });
});

export function destroyTeamMemberRequestToJSON(
  destroyTeamMemberRequest: DestroyTeamMemberRequest,
): string {
  return JSON.stringify(
    DestroyTeamMemberRequest$outboundSchema.parse(destroyTeamMemberRequest),
  );
}
export function destroyTeamMemberRequestFromJSON(
  jsonString: string,
): SafeParseResult<DestroyTeamMemberRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestroyTeamMemberRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestroyTeamMemberRequest' from JSON`,
  );
}
