/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetKubernetesClusterKubeconfigRequest = {
  /**
   * The cluster ID (format: kc_<hash>) or cluster name. Both formats are accepted for backward compatibility.
   */
  kubernetesClusterId: string;
};

/** @internal */
export const GetKubernetesClusterKubeconfigRequest$inboundSchema: z.ZodType<
  GetKubernetesClusterKubeconfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  kubernetes_cluster_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "kubernetes_cluster_id": "kubernetesClusterId",
  });
});
/** @internal */
export type GetKubernetesClusterKubeconfigRequest$Outbound = {
  kubernetes_cluster_id: string;
};

/** @internal */
export const GetKubernetesClusterKubeconfigRequest$outboundSchema: z.ZodType<
  GetKubernetesClusterKubeconfigRequest$Outbound,
  z.ZodTypeDef,
  GetKubernetesClusterKubeconfigRequest
> = z.object({
  kubernetesClusterId: z.string(),
}).transform((v) => {
  return remap$(v, {
    kubernetesClusterId: "kubernetes_cluster_id",
  });
});

export function getKubernetesClusterKubeconfigRequestToJSON(
  getKubernetesClusterKubeconfigRequest: GetKubernetesClusterKubeconfigRequest,
): string {
  return JSON.stringify(
    GetKubernetesClusterKubeconfigRequest$outboundSchema.parse(
      getKubernetesClusterKubeconfigRequest,
    ),
  );
}
export function getKubernetesClusterKubeconfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetKubernetesClusterKubeconfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetKubernetesClusterKubeconfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetKubernetesClusterKubeconfigRequest' from JSON`,
  );
}
