/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetPrefixesRequest = {
  filterProject?: string | undefined;
  filterSite?: string | undefined;
};

/** @internal */
export const GetPrefixesRequest$inboundSchema: z.ZodType<
  GetPrefixesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "filter[project]": z.string().optional(),
  "filter[site]": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "filter[project]": "filterProject",
    "filter[site]": "filterSite",
  });
});
/** @internal */
export type GetPrefixesRequest$Outbound = {
  "filter[project]"?: string | undefined;
  "filter[site]"?: string | undefined;
};

/** @internal */
export const GetPrefixesRequest$outboundSchema: z.ZodType<
  GetPrefixesRequest$Outbound,
  z.ZodTypeDef,
  GetPrefixesRequest
> = z.object({
  filterProject: z.string().optional(),
  filterSite: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    filterProject: "filter[project]",
    filterSite: "filter[site]",
  });
});

export function getPrefixesRequestToJSON(
  getPrefixesRequest: GetPrefixesRequest,
): string {
  return JSON.stringify(
    GetPrefixesRequest$outboundSchema.parse(getPrefixesRequest),
  );
}
export function getPrefixesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetPrefixesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPrefixesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPrefixesRequest' from JSON`,
  );
}
