/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetRoleIdRequest = {
  roleId: string;
};

/** @internal */
export const GetRoleIdRequest$inboundSchema: z.ZodType<
  GetRoleIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  role_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "role_id": "roleId",
  });
});
/** @internal */
export type GetRoleIdRequest$Outbound = {
  role_id: string;
};

/** @internal */
export const GetRoleIdRequest$outboundSchema: z.ZodType<
  GetRoleIdRequest$Outbound,
  z.ZodTypeDef,
  GetRoleIdRequest
> = z.object({
  roleId: z.string(),
}).transform((v) => {
  return remap$(v, {
    roleId: "role_id",
  });
});

export function getRoleIdRequestToJSON(
  getRoleIdRequest: GetRoleIdRequest,
): string {
  return JSON.stringify(
    GetRoleIdRequest$outboundSchema.parse(getRoleIdRequest),
  );
}
export function getRoleIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetRoleIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRoleIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRoleIdRequest' from JSON`,
  );
}
