/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetRolesRequest = {
  /**
   * Number of items to return per page
   */
  pageSize?: number | undefined;
  /**
   * Page number to return (starts at 1)
   */
  pageNumber?: number | undefined;
};

/**
 * Success
 */
export type GetRolesResponseBody = {
  data?: Array<models.RoleData> | undefined;
};

export type GetRolesResponse = {
  result: GetRolesResponseBody;
};

/** @internal */
export const GetRolesRequest$inboundSchema: z.ZodType<
  GetRolesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "page[size]": z.number().int().default(20),
  "page[number]": z.number().int().default(1),
}).transform((v) => {
  return remap$(v, {
    "page[size]": "pageSize",
    "page[number]": "pageNumber",
  });
});
/** @internal */
export type GetRolesRequest$Outbound = {
  "page[size]": number;
  "page[number]": number;
};

/** @internal */
export const GetRolesRequest$outboundSchema: z.ZodType<
  GetRolesRequest$Outbound,
  z.ZodTypeDef,
  GetRolesRequest
> = z.object({
  pageSize: z.number().int().default(20),
  pageNumber: z.number().int().default(1),
}).transform((v) => {
  return remap$(v, {
    pageSize: "page[size]",
    pageNumber: "page[number]",
  });
});

export function getRolesRequestToJSON(
  getRolesRequest: GetRolesRequest,
): string {
  return JSON.stringify(GetRolesRequest$outboundSchema.parse(getRolesRequest));
}
export function getRolesRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetRolesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRolesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRolesRequest' from JSON`,
  );
}

/** @internal */
export const GetRolesResponseBody$inboundSchema: z.ZodType<
  GetRolesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(models.RoleData$inboundSchema).optional(),
});
/** @internal */
export type GetRolesResponseBody$Outbound = {
  data?: Array<models.RoleData$Outbound> | undefined;
};

/** @internal */
export const GetRolesResponseBody$outboundSchema: z.ZodType<
  GetRolesResponseBody$Outbound,
  z.ZodTypeDef,
  GetRolesResponseBody
> = z.object({
  data: z.array(models.RoleData$outboundSchema).optional(),
});

export function getRolesResponseBodyToJSON(
  getRolesResponseBody: GetRolesResponseBody,
): string {
  return JSON.stringify(
    GetRolesResponseBody$outboundSchema.parse(getRolesResponseBody),
  );
}
export function getRolesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetRolesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRolesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRolesResponseBody' from JSON`,
  );
}

/** @internal */
export const GetRolesResponse$inboundSchema: z.ZodType<
  GetRolesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: z.lazy(() => GetRolesResponseBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type GetRolesResponse$Outbound = {
  Result: GetRolesResponseBody$Outbound;
};

/** @internal */
export const GetRolesResponse$outboundSchema: z.ZodType<
  GetRolesResponse$Outbound,
  z.ZodTypeDef,
  GetRolesResponse
> = z.object({
  result: z.lazy(() => GetRolesResponseBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function getRolesResponseToJSON(
  getRolesResponse: GetRolesResponse,
): string {
  return JSON.stringify(
    GetRolesResponse$outboundSchema.parse(getRolesResponse),
  );
}
export function getRolesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetRolesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRolesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRolesResponse' from JSON`,
  );
}
