/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetServersRequest = {
  /**
   * The project ID or Slug to filter by
   */
  filterProject?: string | undefined;
  /**
   * The region Slug to filter by
   */
  filterRegion?: string | undefined;
  /**
   * The hostname of server to filter by
   */
  filterHostname?: string | undefined;
  /**
   * The created at greater than equal date to filter by
   */
  filterCreatedAtGte?: string | undefined;
  /**
   * The created at less than equal date to filter by
   */
  filterCreatedAtLte?: string | undefined;
  /**
   * The label of server to filter by
   */
  filterLabel?: string | undefined;
  /**
   * The status of server to filter by
   */
  filterStatus?: string | undefined;
  /**
   * The platform/plan name of the server to filter by
   */
  filterPlan?: string | undefined;
  /**
   * Filter by the existence of an associated GPU
   */
  filterGpu?: boolean | undefined;
  /**
   * Filter servers with RAM size (in GB) equals the provided value.
   */
  filterRamEql?: number | undefined;
  /**
   * Filter servers with RAM size (in GB) greater than or equal the provided value.
   */
  filterRamGte?: number | undefined;
  /**
   * Filter servers with RAM size (in GB) less than or equal the provided value.
   */
  filterRamLte?: number | undefined;
  /**
   * The disk size in Gigabytes to filter by, should be used with the following options:
   *
   * @remarks
   *                               [eql] to filter for values equal to the provided value.
   *                               [gte] to filter for values greater than or equal to the provided value.
   *                               [lte] to filter by values lower than or equal to the provided value.
   */
  filterDisk?: number | undefined;
  /**
   * The tags IDs to filter by, separated by comma, e.g. `filter[tags]=tag_1,tag_2`will return servers with `tag_1` AND `tag_2`
   */
  filterTags?: string | undefined;
  /**
   * The `credentials` are provided as extra attributes that are lazy loaded. To request it, just set `extra_fields[servers]=credentials` in the query string.
   */
  extraFieldsServers?: string | undefined;
  /**
   * Number of items to return per page
   */
  pageSize?: number | undefined;
  /**
   * Page number to return (starts at 1)
   */
  pageNumber?: number | undefined;
};

export type GetServersResponse = {
  result: models.Servers;
};

/** @internal */
export const GetServersRequest$inboundSchema: z.ZodType<
  GetServersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "filter[project]": z.string().optional(),
  "filter[region]": z.string().optional(),
  "filter[hostname]": z.string().optional(),
  "filter[created_at_gte]": z.string().optional(),
  "filter[created_at_lte]": z.string().optional(),
  "filter[label]": z.string().optional(),
  "filter[status]": z.string().optional(),
  "filter[plan]": z.string().optional(),
  "filter[gpu]": z.boolean().optional(),
  "filter[ram][eql]": z.number().int().optional(),
  "filter[ram][gte]": z.number().int().optional(),
  "filter[ram][lte]": z.number().int().optional(),
  "filter[disk]": z.number().int().optional(),
  "filter[tags]": z.string().optional(),
  "extra_fields[servers]": z.string().optional(),
  "page[size]": z.number().int().default(20),
  "page[number]": z.number().int().default(1),
}).transform((v) => {
  return remap$(v, {
    "filter[project]": "filterProject",
    "filter[region]": "filterRegion",
    "filter[hostname]": "filterHostname",
    "filter[created_at_gte]": "filterCreatedAtGte",
    "filter[created_at_lte]": "filterCreatedAtLte",
    "filter[label]": "filterLabel",
    "filter[status]": "filterStatus",
    "filter[plan]": "filterPlan",
    "filter[gpu]": "filterGpu",
    "filter[ram][eql]": "filterRamEql",
    "filter[ram][gte]": "filterRamGte",
    "filter[ram][lte]": "filterRamLte",
    "filter[disk]": "filterDisk",
    "filter[tags]": "filterTags",
    "extra_fields[servers]": "extraFieldsServers",
    "page[size]": "pageSize",
    "page[number]": "pageNumber",
  });
});

/** @internal */
export type GetServersRequest$Outbound = {
  "filter[project]"?: string | undefined;
  "filter[region]"?: string | undefined;
  "filter[hostname]"?: string | undefined;
  "filter[created_at_gte]"?: string | undefined;
  "filter[created_at_lte]"?: string | undefined;
  "filter[label]"?: string | undefined;
  "filter[status]"?: string | undefined;
  "filter[plan]"?: string | undefined;
  "filter[gpu]"?: boolean | undefined;
  "filter[ram][eql]"?: number | undefined;
  "filter[ram][gte]"?: number | undefined;
  "filter[ram][lte]"?: number | undefined;
  "filter[disk]"?: number | undefined;
  "filter[tags]"?: string | undefined;
  "extra_fields[servers]"?: string | undefined;
  "page[size]": number;
  "page[number]": number;
};

/** @internal */
export const GetServersRequest$outboundSchema: z.ZodType<
  GetServersRequest$Outbound,
  z.ZodTypeDef,
  GetServersRequest
> = z.object({
  filterProject: z.string().optional(),
  filterRegion: z.string().optional(),
  filterHostname: z.string().optional(),
  filterCreatedAtGte: z.string().optional(),
  filterCreatedAtLte: z.string().optional(),
  filterLabel: z.string().optional(),
  filterStatus: z.string().optional(),
  filterPlan: z.string().optional(),
  filterGpu: z.boolean().optional(),
  filterRamEql: z.number().int().optional(),
  filterRamGte: z.number().int().optional(),
  filterRamLte: z.number().int().optional(),
  filterDisk: z.number().int().optional(),
  filterTags: z.string().optional(),
  extraFieldsServers: z.string().optional(),
  pageSize: z.number().int().default(20),
  pageNumber: z.number().int().default(1),
}).transform((v) => {
  return remap$(v, {
    filterProject: "filter[project]",
    filterRegion: "filter[region]",
    filterHostname: "filter[hostname]",
    filterCreatedAtGte: "filter[created_at_gte]",
    filterCreatedAtLte: "filter[created_at_lte]",
    filterLabel: "filter[label]",
    filterStatus: "filter[status]",
    filterPlan: "filter[plan]",
    filterGpu: "filter[gpu]",
    filterRamEql: "filter[ram][eql]",
    filterRamGte: "filter[ram][gte]",
    filterRamLte: "filter[ram][lte]",
    filterDisk: "filter[disk]",
    filterTags: "filter[tags]",
    extraFieldsServers: "extra_fields[servers]",
    pageSize: "page[size]",
    pageNumber: "page[number]",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetServersRequest$ {
  /** @deprecated use `GetServersRequest$inboundSchema` instead. */
  export const inboundSchema = GetServersRequest$inboundSchema;
  /** @deprecated use `GetServersRequest$outboundSchema` instead. */
  export const outboundSchema = GetServersRequest$outboundSchema;
  /** @deprecated use `GetServersRequest$Outbound` instead. */
  export type Outbound = GetServersRequest$Outbound;
}

export function getServersRequestToJSON(
  getServersRequest: GetServersRequest,
): string {
  return JSON.stringify(
    GetServersRequest$outboundSchema.parse(getServersRequest),
  );
}

export function getServersRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetServersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetServersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetServersRequest' from JSON`,
  );
}

/** @internal */
export const GetServersResponse$inboundSchema: z.ZodType<
  GetServersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.Servers$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type GetServersResponse$Outbound = {
  Result: models.Servers$Outbound;
};

/** @internal */
export const GetServersResponse$outboundSchema: z.ZodType<
  GetServersResponse$Outbound,
  z.ZodTypeDef,
  GetServersResponse
> = z.object({
  result: models.Servers$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetServersResponse$ {
  /** @deprecated use `GetServersResponse$inboundSchema` instead. */
  export const inboundSchema = GetServersResponse$inboundSchema;
  /** @deprecated use `GetServersResponse$outboundSchema` instead. */
  export const outboundSchema = GetServersResponse$outboundSchema;
  /** @deprecated use `GetServersResponse$Outbound` instead. */
  export type Outbound = GetServersResponse$Outbound;
}

export function getServersResponseToJSON(
  getServersResponse: GetServersResponse,
): string {
  return JSON.stringify(
    GetServersResponse$outboundSchema.parse(getServersResponse),
  );
}

export function getServersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetServersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetServersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetServersResponse' from JSON`,
  );
}
