/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetServerDeployConfigRequest = {
  /**
   * The Server ID
   */
  serverId: string;
};

/** @internal */
export const GetServerDeployConfigRequest$inboundSchema: z.ZodType<
  GetServerDeployConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  server_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "server_id": "serverId",
  });
});
/** @internal */
export type GetServerDeployConfigRequest$Outbound = {
  server_id: string;
};

/** @internal */
export const GetServerDeployConfigRequest$outboundSchema: z.ZodType<
  GetServerDeployConfigRequest$Outbound,
  z.ZodTypeDef,
  GetServerDeployConfigRequest
> = z.object({
  serverId: z.string(),
}).transform((v) => {
  return remap$(v, {
    serverId: "server_id",
  });
});

export function getServerDeployConfigRequestToJSON(
  getServerDeployConfigRequest: GetServerDeployConfigRequest,
): string {
  return JSON.stringify(
    GetServerDeployConfigRequest$outboundSchema.parse(
      getServerDeployConfigRequest,
    ),
  );
}
export function getServerDeployConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetServerDeployConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetServerDeployConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetServerDeployConfigRequest' from JSON`,
  );
}
