/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetStorageVolumeRequest = {
  /**
   * The volume storage ID
   */
  id: string;
};

/**
 * Success
 */
export type GetStorageVolumeResponse = {
  data?: models.VolumeData | undefined;
};

/** @internal */
export const GetStorageVolumeRequest$inboundSchema: z.ZodType<
  GetStorageVolumeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type GetStorageVolumeRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetStorageVolumeRequest$outboundSchema: z.ZodType<
  GetStorageVolumeRequest$Outbound,
  z.ZodTypeDef,
  GetStorageVolumeRequest
> = z.object({
  id: z.string(),
});

export function getStorageVolumeRequestToJSON(
  getStorageVolumeRequest: GetStorageVolumeRequest,
): string {
  return JSON.stringify(
    GetStorageVolumeRequest$outboundSchema.parse(getStorageVolumeRequest),
  );
}
export function getStorageVolumeRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetStorageVolumeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStorageVolumeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStorageVolumeRequest' from JSON`,
  );
}

/** @internal */
export const GetStorageVolumeResponse$inboundSchema: z.ZodType<
  GetStorageVolumeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.VolumeData$inboundSchema.optional(),
});
/** @internal */
export type GetStorageVolumeResponse$Outbound = {
  data?: models.VolumeData$Outbound | undefined;
};

/** @internal */
export const GetStorageVolumeResponse$outboundSchema: z.ZodType<
  GetStorageVolumeResponse$Outbound,
  z.ZodTypeDef,
  GetStorageVolumeResponse
> = z.object({
  data: models.VolumeData$outboundSchema.optional(),
});

export function getStorageVolumeResponseToJSON(
  getStorageVolumeResponse: GetStorageVolumeResponse,
): string {
  return JSON.stringify(
    GetStorageVolumeResponse$outboundSchema.parse(getStorageVolumeResponse),
  );
}
export function getStorageVolumeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetStorageVolumeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStorageVolumeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStorageVolumeResponse' from JSON`,
  );
}
