/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetTrafficQuotaRequest = {
  filterProject?: string | undefined;
};

/** @internal */
export const GetTrafficQuotaRequest$inboundSchema: z.ZodType<
  GetTrafficQuotaRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "filter[project]": z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "filter[project]": "filterProject",
  });
});
/** @internal */
export type GetTrafficQuotaRequest$Outbound = {
  "filter[project]"?: string | undefined;
};

/** @internal */
export const GetTrafficQuotaRequest$outboundSchema: z.ZodType<
  GetTrafficQuotaRequest$Outbound,
  z.ZodTypeDef,
  GetTrafficQuotaRequest
> = z.object({
  filterProject: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    filterProject: "filter[project]",
  });
});

export function getTrafficQuotaRequestToJSON(
  getTrafficQuotaRequest: GetTrafficQuotaRequest,
): string {
  return JSON.stringify(
    GetTrafficQuotaRequest$outboundSchema.parse(getTrafficQuotaRequest),
  );
}
export function getTrafficQuotaRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetTrafficQuotaRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTrafficQuotaRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTrafficQuotaRequest' from JSON`,
  );
}
