/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type GetVirtualNetworkRequest = {
  /**
   * Virtual Network ID
   */
  vlanId: string;
};

/**
 * Success
 */
export type GetVirtualNetworkResponse = {
  data?: models.VirtualNetwork | undefined;
};

/** @internal */
export const GetVirtualNetworkRequest$inboundSchema: z.ZodType<
  GetVirtualNetworkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  vlan_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "vlan_id": "vlanId",
  });
});

/** @internal */
export type GetVirtualNetworkRequest$Outbound = {
  vlan_id: string;
};

/** @internal */
export const GetVirtualNetworkRequest$outboundSchema: z.ZodType<
  GetVirtualNetworkRequest$Outbound,
  z.ZodTypeDef,
  GetVirtualNetworkRequest
> = z.object({
  vlanId: z.string(),
}).transform((v) => {
  return remap$(v, {
    vlanId: "vlan_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetVirtualNetworkRequest$ {
  /** @deprecated use `GetVirtualNetworkRequest$inboundSchema` instead. */
  export const inboundSchema = GetVirtualNetworkRequest$inboundSchema;
  /** @deprecated use `GetVirtualNetworkRequest$outboundSchema` instead. */
  export const outboundSchema = GetVirtualNetworkRequest$outboundSchema;
  /** @deprecated use `GetVirtualNetworkRequest$Outbound` instead. */
  export type Outbound = GetVirtualNetworkRequest$Outbound;
}

export function getVirtualNetworkRequestToJSON(
  getVirtualNetworkRequest: GetVirtualNetworkRequest,
): string {
  return JSON.stringify(
    GetVirtualNetworkRequest$outboundSchema.parse(getVirtualNetworkRequest),
  );
}

export function getVirtualNetworkRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetVirtualNetworkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetVirtualNetworkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetVirtualNetworkRequest' from JSON`,
  );
}

/** @internal */
export const GetVirtualNetworkResponse$inboundSchema: z.ZodType<
  GetVirtualNetworkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.VirtualNetwork$inboundSchema.optional(),
});

/** @internal */
export type GetVirtualNetworkResponse$Outbound = {
  data?: models.VirtualNetwork$Outbound | undefined;
};

/** @internal */
export const GetVirtualNetworkResponse$outboundSchema: z.ZodType<
  GetVirtualNetworkResponse$Outbound,
  z.ZodTypeDef,
  GetVirtualNetworkResponse
> = z.object({
  data: models.VirtualNetwork$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetVirtualNetworkResponse$ {
  /** @deprecated use `GetVirtualNetworkResponse$inboundSchema` instead. */
  export const inboundSchema = GetVirtualNetworkResponse$inboundSchema;
  /** @deprecated use `GetVirtualNetworkResponse$outboundSchema` instead. */
  export const outboundSchema = GetVirtualNetworkResponse$outboundSchema;
  /** @deprecated use `GetVirtualNetworkResponse$Outbound` instead. */
  export type Outbound = GetVirtualNetworkResponse$Outbound;
}

export function getVirtualNetworkResponseToJSON(
  getVirtualNetworkResponse: GetVirtualNetworkResponse,
): string {
  return JSON.stringify(
    GetVirtualNetworkResponse$outboundSchema.parse(getVirtualNetworkResponse),
  );
}

export function getVirtualNetworkResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetVirtualNetworkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetVirtualNetworkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetVirtualNetworkResponse' from JSON`,
  );
}
