/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListVirtualMachineNetworkAttachmentsRequest = {
  virtualMachineId: string;
};

/** @internal */
export const ListVirtualMachineNetworkAttachmentsRequest$inboundSchema:
  z.ZodType<
    ListVirtualMachineNetworkAttachmentsRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    virtual_machine_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "virtual_machine_id": "virtualMachineId",
    });
  });
/** @internal */
export type ListVirtualMachineNetworkAttachmentsRequest$Outbound = {
  virtual_machine_id: string;
};

/** @internal */
export const ListVirtualMachineNetworkAttachmentsRequest$outboundSchema:
  z.ZodType<
    ListVirtualMachineNetworkAttachmentsRequest$Outbound,
    z.ZodTypeDef,
    ListVirtualMachineNetworkAttachmentsRequest
  > = z.object({
    virtualMachineId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      virtualMachineId: "virtual_machine_id",
    });
  });

export function listVirtualMachineNetworkAttachmentsRequestToJSON(
  listVirtualMachineNetworkAttachmentsRequest:
    ListVirtualMachineNetworkAttachmentsRequest,
): string {
  return JSON.stringify(
    ListVirtualMachineNetworkAttachmentsRequest$outboundSchema.parse(
      listVirtualMachineNetworkAttachmentsRequest,
    ),
  );
}
export function listVirtualMachineNetworkAttachmentsRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  ListVirtualMachineNetworkAttachmentsRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListVirtualMachineNetworkAttachmentsRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListVirtualMachineNetworkAttachmentsRequest' from JSON`,
  );
}
