/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type ListFirewallsRequest = {
  filterProject?: string | undefined;
  /**
   * Number of items to return per page
   */
  pageSize?: number | undefined;
  /**
   * Page number to return (starts at 1)
   */
  pageNumber?: number | undefined;
};

export type ListFirewallsResponse = {
  result: models.Firewalls;
};

/** @internal */
export const ListFirewallsRequest$inboundSchema: z.ZodType<
  ListFirewallsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "filter[project]": z.string().optional(),
  "page[size]": z.number().int().default(20),
  "page[number]": z.number().int().default(1),
}).transform((v) => {
  return remap$(v, {
    "filter[project]": "filterProject",
    "page[size]": "pageSize",
    "page[number]": "pageNumber",
  });
});

/** @internal */
export type ListFirewallsRequest$Outbound = {
  "filter[project]"?: string | undefined;
  "page[size]": number;
  "page[number]": number;
};

/** @internal */
export const ListFirewallsRequest$outboundSchema: z.ZodType<
  ListFirewallsRequest$Outbound,
  z.ZodTypeDef,
  ListFirewallsRequest
> = z.object({
  filterProject: z.string().optional(),
  pageSize: z.number().int().default(20),
  pageNumber: z.number().int().default(1),
}).transform((v) => {
  return remap$(v, {
    filterProject: "filter[project]",
    pageSize: "page[size]",
    pageNumber: "page[number]",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListFirewallsRequest$ {
  /** @deprecated use `ListFirewallsRequest$inboundSchema` instead. */
  export const inboundSchema = ListFirewallsRequest$inboundSchema;
  /** @deprecated use `ListFirewallsRequest$outboundSchema` instead. */
  export const outboundSchema = ListFirewallsRequest$outboundSchema;
  /** @deprecated use `ListFirewallsRequest$Outbound` instead. */
  export type Outbound = ListFirewallsRequest$Outbound;
}

export function listFirewallsRequestToJSON(
  listFirewallsRequest: ListFirewallsRequest,
): string {
  return JSON.stringify(
    ListFirewallsRequest$outboundSchema.parse(listFirewallsRequest),
  );
}

export function listFirewallsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListFirewallsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListFirewallsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListFirewallsRequest' from JSON`,
  );
}

/** @internal */
export const ListFirewallsResponse$inboundSchema: z.ZodType<
  ListFirewallsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: models.Firewalls$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

/** @internal */
export type ListFirewallsResponse$Outbound = {
  Result: models.Firewalls$Outbound;
};

/** @internal */
export const ListFirewallsResponse$outboundSchema: z.ZodType<
  ListFirewallsResponse$Outbound,
  z.ZodTypeDef,
  ListFirewallsResponse
> = z.object({
  result: models.Firewalls$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListFirewallsResponse$ {
  /** @deprecated use `ListFirewallsResponse$inboundSchema` instead. */
  export const inboundSchema = ListFirewallsResponse$inboundSchema;
  /** @deprecated use `ListFirewallsResponse$outboundSchema` instead. */
  export const outboundSchema = ListFirewallsResponse$outboundSchema;
  /** @deprecated use `ListFirewallsResponse$Outbound` instead. */
  export type Outbound = ListFirewallsResponse$Outbound;
}

export function listFirewallsResponseToJSON(
  listFirewallsResponse: ListFirewallsResponse,
): string {
  return JSON.stringify(
    ListFirewallsResponse$outboundSchema.parse(listFirewallsResponse),
  );
}

export function listFirewallsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListFirewallsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListFirewallsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListFirewallsResponse' from JSON`,
  );
}
