/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListVirtualMachineScopedRestoresRequest = {
  virtualMachineId: string;
  backupId: string;
};

/** @internal */
export const ListVirtualMachineScopedRestoresRequest$inboundSchema: z.ZodType<
  ListVirtualMachineScopedRestoresRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  virtual_machine_id: z.string(),
  backup_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "virtual_machine_id": "virtualMachineId",
    "backup_id": "backupId",
  });
});
/** @internal */
export type ListVirtualMachineScopedRestoresRequest$Outbound = {
  virtual_machine_id: string;
  backup_id: string;
};

/** @internal */
export const ListVirtualMachineScopedRestoresRequest$outboundSchema: z.ZodType<
  ListVirtualMachineScopedRestoresRequest$Outbound,
  z.ZodTypeDef,
  ListVirtualMachineScopedRestoresRequest
> = z.object({
  virtualMachineId: z.string(),
  backupId: z.string(),
}).transform((v) => {
  return remap$(v, {
    virtualMachineId: "virtual_machine_id",
    backupId: "backup_id",
  });
});

export function listVirtualMachineScopedRestoresRequestToJSON(
  listVirtualMachineScopedRestoresRequest:
    ListVirtualMachineScopedRestoresRequest,
): string {
  return JSON.stringify(
    ListVirtualMachineScopedRestoresRequest$outboundSchema.parse(
      listVirtualMachineScopedRestoresRequest,
    ),
  );
}
export function listVirtualMachineScopedRestoresRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  ListVirtualMachineScopedRestoresRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListVirtualMachineScopedRestoresRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListVirtualMachineScopedRestoresRequest' from JSON`,
  );
}
