/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const MapVolumeType2 = {
  Volumes: "volumes",
} as const;
export type MapVolumeType2 = ClosedEnum<typeof MapVolumeType2>;

export type MapVolumeAttributes2 = {
  /**
   * ID of the server that will access the volume. The server must belong to the same project and location as the volume, and must be eligible for bonding.
   */
  serverId: string;
};

export type MapVolumeData2 = {
  type: MapVolumeType2;
  attributes: MapVolumeAttributes2;
};

export type MapVolumeRequestBody2 = {
  data: MapVolumeData2;
};

export type MapVolumeRequest = {
  /**
   * Volume ID
   */
  id: string;
  requestBody: MapVolumeRequestBody2;
};

export type MapVolumeMeta = {};

/**
 * Accepted
 */
export type MapVolumeResponse = {
  data?: models.VolumeData | undefined;
  meta?: MapVolumeMeta | undefined;
};

/** @internal */
export const MapVolumeType2$inboundSchema: z.ZodNativeEnum<
  typeof MapVolumeType2
> = z.nativeEnum(MapVolumeType2);
/** @internal */
export const MapVolumeType2$outboundSchema: z.ZodNativeEnum<
  typeof MapVolumeType2
> = MapVolumeType2$inboundSchema;

/** @internal */
export const MapVolumeAttributes2$inboundSchema: z.ZodType<
  MapVolumeAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  server_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "server_id": "serverId",
  });
});
/** @internal */
export type MapVolumeAttributes2$Outbound = {
  server_id: string;
};

/** @internal */
export const MapVolumeAttributes2$outboundSchema: z.ZodType<
  MapVolumeAttributes2$Outbound,
  z.ZodTypeDef,
  MapVolumeAttributes2
> = z.object({
  serverId: z.string(),
}).transform((v) => {
  return remap$(v, {
    serverId: "server_id",
  });
});

export function mapVolumeAttributes2ToJSON(
  mapVolumeAttributes2: MapVolumeAttributes2,
): string {
  return JSON.stringify(
    MapVolumeAttributes2$outboundSchema.parse(mapVolumeAttributes2),
  );
}
export function mapVolumeAttributes2FromJSON(
  jsonString: string,
): SafeParseResult<MapVolumeAttributes2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MapVolumeAttributes2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MapVolumeAttributes2' from JSON`,
  );
}

/** @internal */
export const MapVolumeData2$inboundSchema: z.ZodType<
  MapVolumeData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: MapVolumeType2$inboundSchema,
  attributes: z.lazy(() => MapVolumeAttributes2$inboundSchema),
});
/** @internal */
export type MapVolumeData2$Outbound = {
  type: string;
  attributes: MapVolumeAttributes2$Outbound;
};

/** @internal */
export const MapVolumeData2$outboundSchema: z.ZodType<
  MapVolumeData2$Outbound,
  z.ZodTypeDef,
  MapVolumeData2
> = z.object({
  type: MapVolumeType2$outboundSchema,
  attributes: z.lazy(() => MapVolumeAttributes2$outboundSchema),
});

export function mapVolumeData2ToJSON(mapVolumeData2: MapVolumeData2): string {
  return JSON.stringify(MapVolumeData2$outboundSchema.parse(mapVolumeData2));
}
export function mapVolumeData2FromJSON(
  jsonString: string,
): SafeParseResult<MapVolumeData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MapVolumeData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MapVolumeData2' from JSON`,
  );
}

/** @internal */
export const MapVolumeRequestBody2$inboundSchema: z.ZodType<
  MapVolumeRequestBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => MapVolumeData2$inboundSchema),
});
/** @internal */
export type MapVolumeRequestBody2$Outbound = {
  data: MapVolumeData2$Outbound;
};

/** @internal */
export const MapVolumeRequestBody2$outboundSchema: z.ZodType<
  MapVolumeRequestBody2$Outbound,
  z.ZodTypeDef,
  MapVolumeRequestBody2
> = z.object({
  data: z.lazy(() => MapVolumeData2$outboundSchema),
});

export function mapVolumeRequestBody2ToJSON(
  mapVolumeRequestBody2: MapVolumeRequestBody2,
): string {
  return JSON.stringify(
    MapVolumeRequestBody2$outboundSchema.parse(mapVolumeRequestBody2),
  );
}
export function mapVolumeRequestBody2FromJSON(
  jsonString: string,
): SafeParseResult<MapVolumeRequestBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MapVolumeRequestBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MapVolumeRequestBody2' from JSON`,
  );
}

/** @internal */
export const MapVolumeRequest$inboundSchema: z.ZodType<
  MapVolumeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  RequestBody: z.lazy(() => MapVolumeRequestBody2$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type MapVolumeRequest$Outbound = {
  id: string;
  RequestBody: MapVolumeRequestBody2$Outbound;
};

/** @internal */
export const MapVolumeRequest$outboundSchema: z.ZodType<
  MapVolumeRequest$Outbound,
  z.ZodTypeDef,
  MapVolumeRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => MapVolumeRequestBody2$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function mapVolumeRequestToJSON(
  mapVolumeRequest: MapVolumeRequest,
): string {
  return JSON.stringify(
    MapVolumeRequest$outboundSchema.parse(mapVolumeRequest),
  );
}
export function mapVolumeRequestFromJSON(
  jsonString: string,
): SafeParseResult<MapVolumeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MapVolumeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MapVolumeRequest' from JSON`,
  );
}

/** @internal */
export const MapVolumeMeta$inboundSchema: z.ZodType<
  MapVolumeMeta,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type MapVolumeMeta$Outbound = {};

/** @internal */
export const MapVolumeMeta$outboundSchema: z.ZodType<
  MapVolumeMeta$Outbound,
  z.ZodTypeDef,
  MapVolumeMeta
> = z.object({});

export function mapVolumeMetaToJSON(mapVolumeMeta: MapVolumeMeta): string {
  return JSON.stringify(MapVolumeMeta$outboundSchema.parse(mapVolumeMeta));
}
export function mapVolumeMetaFromJSON(
  jsonString: string,
): SafeParseResult<MapVolumeMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MapVolumeMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MapVolumeMeta' from JSON`,
  );
}

/** @internal */
export const MapVolumeResponse$inboundSchema: z.ZodType<
  MapVolumeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.VolumeData$inboundSchema.optional(),
  meta: z.lazy(() => MapVolumeMeta$inboundSchema).optional(),
});
/** @internal */
export type MapVolumeResponse$Outbound = {
  data?: models.VolumeData$Outbound | undefined;
  meta?: MapVolumeMeta$Outbound | undefined;
};

/** @internal */
export const MapVolumeResponse$outboundSchema: z.ZodType<
  MapVolumeResponse$Outbound,
  z.ZodTypeDef,
  MapVolumeResponse
> = z.object({
  data: models.VolumeData$outboundSchema.optional(),
  meta: z.lazy(() => MapVolumeMeta$outboundSchema).optional(),
});

export function mapVolumeResponseToJSON(
  mapVolumeResponse: MapVolumeResponse,
): string {
  return JSON.stringify(
    MapVolumeResponse$outboundSchema.parse(mapVolumeResponse),
  );
}
export function mapVolumeResponseFromJSON(
  jsonString: string,
): SafeParseResult<MapVolumeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MapVolumeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MapVolumeResponse' from JSON`,
  );
}
