/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const PatchUserProfileType2 = {
  Users: "users",
} as const;
export type PatchUserProfileType2 = ClosedEnum<typeof PatchUserProfileType2>;

export const PatchUserProfileRole2 = {
  Administrator: "administrator",
  Billing: "billing",
  Collaborator: "collaborator",
  Owner: "owner",
} as const;
export type PatchUserProfileRole2 = ClosedEnum<typeof PatchUserProfileRole2>;

export type PatchUserProfileAttributes2 = {
  firstName?: string | undefined;
  lastName?: string | undefined;
  role?: PatchUserProfileRole2 | undefined;
};

export type PatchUserProfileData2 = {
  id: string;
  type: PatchUserProfileType2;
  attributes?: PatchUserProfileAttributes2 | undefined;
};

export type PatchUserProfileRequestBody2 = {
  data: PatchUserProfileData2;
};

export type PatchUserProfileRequest = {
  id: string;
  requestBody: PatchUserProfileRequestBody2;
};

/**
 * Success
 */
export type PatchUserProfileResponse = {
  data?: models.UserUpdate | undefined;
};

/** @internal */
export const PatchUserProfileType2$inboundSchema: z.ZodNativeEnum<
  typeof PatchUserProfileType2
> = z.nativeEnum(PatchUserProfileType2);

/** @internal */
export const PatchUserProfileType2$outboundSchema: z.ZodNativeEnum<
  typeof PatchUserProfileType2
> = PatchUserProfileType2$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchUserProfileType2$ {
  /** @deprecated use `PatchUserProfileType2$inboundSchema` instead. */
  export const inboundSchema = PatchUserProfileType2$inboundSchema;
  /** @deprecated use `PatchUserProfileType2$outboundSchema` instead. */
  export const outboundSchema = PatchUserProfileType2$outboundSchema;
}

/** @internal */
export const PatchUserProfileRole2$inboundSchema: z.ZodNativeEnum<
  typeof PatchUserProfileRole2
> = z.nativeEnum(PatchUserProfileRole2);

/** @internal */
export const PatchUserProfileRole2$outboundSchema: z.ZodNativeEnum<
  typeof PatchUserProfileRole2
> = PatchUserProfileRole2$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchUserProfileRole2$ {
  /** @deprecated use `PatchUserProfileRole2$inboundSchema` instead. */
  export const inboundSchema = PatchUserProfileRole2$inboundSchema;
  /** @deprecated use `PatchUserProfileRole2$outboundSchema` instead. */
  export const outboundSchema = PatchUserProfileRole2$outboundSchema;
}

/** @internal */
export const PatchUserProfileAttributes2$inboundSchema: z.ZodType<
  PatchUserProfileAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  first_name: z.string().optional(),
  last_name: z.string().optional(),
  role: PatchUserProfileRole2$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "first_name": "firstName",
    "last_name": "lastName",
  });
});

/** @internal */
export type PatchUserProfileAttributes2$Outbound = {
  first_name?: string | undefined;
  last_name?: string | undefined;
  role?: string | undefined;
};

/** @internal */
export const PatchUserProfileAttributes2$outboundSchema: z.ZodType<
  PatchUserProfileAttributes2$Outbound,
  z.ZodTypeDef,
  PatchUserProfileAttributes2
> = z.object({
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  role: PatchUserProfileRole2$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    firstName: "first_name",
    lastName: "last_name",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchUserProfileAttributes2$ {
  /** @deprecated use `PatchUserProfileAttributes2$inboundSchema` instead. */
  export const inboundSchema = PatchUserProfileAttributes2$inboundSchema;
  /** @deprecated use `PatchUserProfileAttributes2$outboundSchema` instead. */
  export const outboundSchema = PatchUserProfileAttributes2$outboundSchema;
  /** @deprecated use `PatchUserProfileAttributes2$Outbound` instead. */
  export type Outbound = PatchUserProfileAttributes2$Outbound;
}

export function patchUserProfileAttributes2ToJSON(
  patchUserProfileAttributes2: PatchUserProfileAttributes2,
): string {
  return JSON.stringify(
    PatchUserProfileAttributes2$outboundSchema.parse(
      patchUserProfileAttributes2,
    ),
  );
}

export function patchUserProfileAttributes2FromJSON(
  jsonString: string,
): SafeParseResult<PatchUserProfileAttributes2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchUserProfileAttributes2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchUserProfileAttributes2' from JSON`,
  );
}

/** @internal */
export const PatchUserProfileData2$inboundSchema: z.ZodType<
  PatchUserProfileData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: PatchUserProfileType2$inboundSchema,
  attributes: z.lazy(() => PatchUserProfileAttributes2$inboundSchema)
    .optional(),
});

/** @internal */
export type PatchUserProfileData2$Outbound = {
  id: string;
  type: string;
  attributes?: PatchUserProfileAttributes2$Outbound | undefined;
};

/** @internal */
export const PatchUserProfileData2$outboundSchema: z.ZodType<
  PatchUserProfileData2$Outbound,
  z.ZodTypeDef,
  PatchUserProfileData2
> = z.object({
  id: z.string(),
  type: PatchUserProfileType2$outboundSchema,
  attributes: z.lazy(() => PatchUserProfileAttributes2$outboundSchema)
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchUserProfileData2$ {
  /** @deprecated use `PatchUserProfileData2$inboundSchema` instead. */
  export const inboundSchema = PatchUserProfileData2$inboundSchema;
  /** @deprecated use `PatchUserProfileData2$outboundSchema` instead. */
  export const outboundSchema = PatchUserProfileData2$outboundSchema;
  /** @deprecated use `PatchUserProfileData2$Outbound` instead. */
  export type Outbound = PatchUserProfileData2$Outbound;
}

export function patchUserProfileData2ToJSON(
  patchUserProfileData2: PatchUserProfileData2,
): string {
  return JSON.stringify(
    PatchUserProfileData2$outboundSchema.parse(patchUserProfileData2),
  );
}

export function patchUserProfileData2FromJSON(
  jsonString: string,
): SafeParseResult<PatchUserProfileData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchUserProfileData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchUserProfileData2' from JSON`,
  );
}

/** @internal */
export const PatchUserProfileRequestBody2$inboundSchema: z.ZodType<
  PatchUserProfileRequestBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => PatchUserProfileData2$inboundSchema),
});

/** @internal */
export type PatchUserProfileRequestBody2$Outbound = {
  data: PatchUserProfileData2$Outbound;
};

/** @internal */
export const PatchUserProfileRequestBody2$outboundSchema: z.ZodType<
  PatchUserProfileRequestBody2$Outbound,
  z.ZodTypeDef,
  PatchUserProfileRequestBody2
> = z.object({
  data: z.lazy(() => PatchUserProfileData2$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchUserProfileRequestBody2$ {
  /** @deprecated use `PatchUserProfileRequestBody2$inboundSchema` instead. */
  export const inboundSchema = PatchUserProfileRequestBody2$inboundSchema;
  /** @deprecated use `PatchUserProfileRequestBody2$outboundSchema` instead. */
  export const outboundSchema = PatchUserProfileRequestBody2$outboundSchema;
  /** @deprecated use `PatchUserProfileRequestBody2$Outbound` instead. */
  export type Outbound = PatchUserProfileRequestBody2$Outbound;
}

export function patchUserProfileRequestBody2ToJSON(
  patchUserProfileRequestBody2: PatchUserProfileRequestBody2,
): string {
  return JSON.stringify(
    PatchUserProfileRequestBody2$outboundSchema.parse(
      patchUserProfileRequestBody2,
    ),
  );
}

export function patchUserProfileRequestBody2FromJSON(
  jsonString: string,
): SafeParseResult<PatchUserProfileRequestBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchUserProfileRequestBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchUserProfileRequestBody2' from JSON`,
  );
}

/** @internal */
export const PatchUserProfileRequest$inboundSchema: z.ZodType<
  PatchUserProfileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  RequestBody: z.lazy(() => PatchUserProfileRequestBody2$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type PatchUserProfileRequest$Outbound = {
  id: string;
  RequestBody: PatchUserProfileRequestBody2$Outbound;
};

/** @internal */
export const PatchUserProfileRequest$outboundSchema: z.ZodType<
  PatchUserProfileRequest$Outbound,
  z.ZodTypeDef,
  PatchUserProfileRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => PatchUserProfileRequestBody2$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchUserProfileRequest$ {
  /** @deprecated use `PatchUserProfileRequest$inboundSchema` instead. */
  export const inboundSchema = PatchUserProfileRequest$inboundSchema;
  /** @deprecated use `PatchUserProfileRequest$outboundSchema` instead. */
  export const outboundSchema = PatchUserProfileRequest$outboundSchema;
  /** @deprecated use `PatchUserProfileRequest$Outbound` instead. */
  export type Outbound = PatchUserProfileRequest$Outbound;
}

export function patchUserProfileRequestToJSON(
  patchUserProfileRequest: PatchUserProfileRequest,
): string {
  return JSON.stringify(
    PatchUserProfileRequest$outboundSchema.parse(patchUserProfileRequest),
  );
}

export function patchUserProfileRequestFromJSON(
  jsonString: string,
): SafeParseResult<PatchUserProfileRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchUserProfileRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchUserProfileRequest' from JSON`,
  );
}

/** @internal */
export const PatchUserProfileResponse$inboundSchema: z.ZodType<
  PatchUserProfileResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.UserUpdate$inboundSchema.optional(),
});

/** @internal */
export type PatchUserProfileResponse$Outbound = {
  data?: models.UserUpdate$Outbound | undefined;
};

/** @internal */
export const PatchUserProfileResponse$outboundSchema: z.ZodType<
  PatchUserProfileResponse$Outbound,
  z.ZodTypeDef,
  PatchUserProfileResponse
> = z.object({
  data: models.UserUpdate$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchUserProfileResponse$ {
  /** @deprecated use `PatchUserProfileResponse$inboundSchema` instead. */
  export const inboundSchema = PatchUserProfileResponse$inboundSchema;
  /** @deprecated use `PatchUserProfileResponse$outboundSchema` instead. */
  export const outboundSchema = PatchUserProfileResponse$outboundSchema;
  /** @deprecated use `PatchUserProfileResponse$Outbound` instead. */
  export type Outbound = PatchUserProfileResponse$Outbound;
}

export function patchUserProfileResponseToJSON(
  patchUserProfileResponse: PatchUserProfileResponse,
): string {
  return JSON.stringify(
    PatchUserProfileResponse$outboundSchema.parse(patchUserProfileResponse),
  );
}

export function patchUserProfileResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchUserProfileResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchUserProfileResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchUserProfileResponse' from JSON`,
  );
}
