/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const PostStorageFilesystemsType2 = {
  Filesystems: "filesystems",
} as const;
export type PostStorageFilesystemsType2 = ClosedEnum<
  typeof PostStorageFilesystemsType2
>;

export type PostStorageFilesystemsAttributes2 = {
  /**
   * Project ID or slug
   */
  project: string;
  /**
   * Storage name
   */
  name: string;
  /**
   * Size in GB (not required, default is 1500)
   */
  sizeInGb?: number | undefined;
};

export type PostStorageFilesystemsData2 = {
  type: PostStorageFilesystemsType2;
  attributes: PostStorageFilesystemsAttributes2;
};

export type PostStorageFilesystemsRequest = {
  data: PostStorageFilesystemsData2;
};

/**
 * Created
 */
export type PostStorageFilesystemsResponse = {
  data?: models.FilesystemData | undefined;
};

/** @internal */
export const PostStorageFilesystemsType2$inboundSchema: z.ZodNativeEnum<
  typeof PostStorageFilesystemsType2
> = z.nativeEnum(PostStorageFilesystemsType2);

/** @internal */
export const PostStorageFilesystemsType2$outboundSchema: z.ZodNativeEnum<
  typeof PostStorageFilesystemsType2
> = PostStorageFilesystemsType2$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostStorageFilesystemsType2$ {
  /** @deprecated use `PostStorageFilesystemsType2$inboundSchema` instead. */
  export const inboundSchema = PostStorageFilesystemsType2$inboundSchema;
  /** @deprecated use `PostStorageFilesystemsType2$outboundSchema` instead. */
  export const outboundSchema = PostStorageFilesystemsType2$outboundSchema;
}

/** @internal */
export const PostStorageFilesystemsAttributes2$inboundSchema: z.ZodType<
  PostStorageFilesystemsAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  project: z.string(),
  name: z.string(),
  size_in_gb: z.number().int().default(1500),
}).transform((v) => {
  return remap$(v, {
    "size_in_gb": "sizeInGb",
  });
});

/** @internal */
export type PostStorageFilesystemsAttributes2$Outbound = {
  project: string;
  name: string;
  size_in_gb: number;
};

/** @internal */
export const PostStorageFilesystemsAttributes2$outboundSchema: z.ZodType<
  PostStorageFilesystemsAttributes2$Outbound,
  z.ZodTypeDef,
  PostStorageFilesystemsAttributes2
> = z.object({
  project: z.string(),
  name: z.string(),
  sizeInGb: z.number().int().default(1500),
}).transform((v) => {
  return remap$(v, {
    sizeInGb: "size_in_gb",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostStorageFilesystemsAttributes2$ {
  /** @deprecated use `PostStorageFilesystemsAttributes2$inboundSchema` instead. */
  export const inboundSchema = PostStorageFilesystemsAttributes2$inboundSchema;
  /** @deprecated use `PostStorageFilesystemsAttributes2$outboundSchema` instead. */
  export const outboundSchema =
    PostStorageFilesystemsAttributes2$outboundSchema;
  /** @deprecated use `PostStorageFilesystemsAttributes2$Outbound` instead. */
  export type Outbound = PostStorageFilesystemsAttributes2$Outbound;
}

export function postStorageFilesystemsAttributes2ToJSON(
  postStorageFilesystemsAttributes2: PostStorageFilesystemsAttributes2,
): string {
  return JSON.stringify(
    PostStorageFilesystemsAttributes2$outboundSchema.parse(
      postStorageFilesystemsAttributes2,
    ),
  );
}

export function postStorageFilesystemsAttributes2FromJSON(
  jsonString: string,
): SafeParseResult<PostStorageFilesystemsAttributes2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostStorageFilesystemsAttributes2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostStorageFilesystemsAttributes2' from JSON`,
  );
}

/** @internal */
export const PostStorageFilesystemsData2$inboundSchema: z.ZodType<
  PostStorageFilesystemsData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PostStorageFilesystemsType2$inboundSchema,
  attributes: z.lazy(() => PostStorageFilesystemsAttributes2$inboundSchema),
});

/** @internal */
export type PostStorageFilesystemsData2$Outbound = {
  type: string;
  attributes: PostStorageFilesystemsAttributes2$Outbound;
};

/** @internal */
export const PostStorageFilesystemsData2$outboundSchema: z.ZodType<
  PostStorageFilesystemsData2$Outbound,
  z.ZodTypeDef,
  PostStorageFilesystemsData2
> = z.object({
  type: PostStorageFilesystemsType2$outboundSchema,
  attributes: z.lazy(() => PostStorageFilesystemsAttributes2$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostStorageFilesystemsData2$ {
  /** @deprecated use `PostStorageFilesystemsData2$inboundSchema` instead. */
  export const inboundSchema = PostStorageFilesystemsData2$inboundSchema;
  /** @deprecated use `PostStorageFilesystemsData2$outboundSchema` instead. */
  export const outboundSchema = PostStorageFilesystemsData2$outboundSchema;
  /** @deprecated use `PostStorageFilesystemsData2$Outbound` instead. */
  export type Outbound = PostStorageFilesystemsData2$Outbound;
}

export function postStorageFilesystemsData2ToJSON(
  postStorageFilesystemsData2: PostStorageFilesystemsData2,
): string {
  return JSON.stringify(
    PostStorageFilesystemsData2$outboundSchema.parse(
      postStorageFilesystemsData2,
    ),
  );
}

export function postStorageFilesystemsData2FromJSON(
  jsonString: string,
): SafeParseResult<PostStorageFilesystemsData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostStorageFilesystemsData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostStorageFilesystemsData2' from JSON`,
  );
}

/** @internal */
export const PostStorageFilesystemsRequest$inboundSchema: z.ZodType<
  PostStorageFilesystemsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => PostStorageFilesystemsData2$inboundSchema),
});

/** @internal */
export type PostStorageFilesystemsRequest$Outbound = {
  data: PostStorageFilesystemsData2$Outbound;
};

/** @internal */
export const PostStorageFilesystemsRequest$outboundSchema: z.ZodType<
  PostStorageFilesystemsRequest$Outbound,
  z.ZodTypeDef,
  PostStorageFilesystemsRequest
> = z.object({
  data: z.lazy(() => PostStorageFilesystemsData2$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostStorageFilesystemsRequest$ {
  /** @deprecated use `PostStorageFilesystemsRequest$inboundSchema` instead. */
  export const inboundSchema = PostStorageFilesystemsRequest$inboundSchema;
  /** @deprecated use `PostStorageFilesystemsRequest$outboundSchema` instead. */
  export const outboundSchema = PostStorageFilesystemsRequest$outboundSchema;
  /** @deprecated use `PostStorageFilesystemsRequest$Outbound` instead. */
  export type Outbound = PostStorageFilesystemsRequest$Outbound;
}

export function postStorageFilesystemsRequestToJSON(
  postStorageFilesystemsRequest: PostStorageFilesystemsRequest,
): string {
  return JSON.stringify(
    PostStorageFilesystemsRequest$outboundSchema.parse(
      postStorageFilesystemsRequest,
    ),
  );
}

export function postStorageFilesystemsRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostStorageFilesystemsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostStorageFilesystemsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostStorageFilesystemsRequest' from JSON`,
  );
}

/** @internal */
export const PostStorageFilesystemsResponse$inboundSchema: z.ZodType<
  PostStorageFilesystemsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.FilesystemData$inboundSchema.optional(),
});

/** @internal */
export type PostStorageFilesystemsResponse$Outbound = {
  data?: models.FilesystemData$Outbound | undefined;
};

/** @internal */
export const PostStorageFilesystemsResponse$outboundSchema: z.ZodType<
  PostStorageFilesystemsResponse$Outbound,
  z.ZodTypeDef,
  PostStorageFilesystemsResponse
> = z.object({
  data: models.FilesystemData$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostStorageFilesystemsResponse$ {
  /** @deprecated use `PostStorageFilesystemsResponse$inboundSchema` instead. */
  export const inboundSchema = PostStorageFilesystemsResponse$inboundSchema;
  /** @deprecated use `PostStorageFilesystemsResponse$outboundSchema` instead. */
  export const outboundSchema = PostStorageFilesystemsResponse$outboundSchema;
  /** @deprecated use `PostStorageFilesystemsResponse$Outbound` instead. */
  export type Outbound = PostStorageFilesystemsResponse$Outbound;
}

export function postStorageFilesystemsResponseToJSON(
  postStorageFilesystemsResponse: PostStorageFilesystemsResponse,
): string {
  return JSON.stringify(
    PostStorageFilesystemsResponse$outboundSchema.parse(
      postStorageFilesystemsResponse,
    ),
  );
}

export function postStorageFilesystemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostStorageFilesystemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostStorageFilesystemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostStorageFilesystemsResponse' from JSON`,
  );
}
