/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export const PostTeamType2 = {
  Teams: "teams",
} as const;
export type PostTeamType2 = ClosedEnum<typeof PostTeamType2>;

export const Currency2 = {
  Usd: "USD",
  Brl: "BRL",
} as const;
export type Currency2 = ClosedEnum<typeof Currency2>;

export type PostTeamAttributes2 = {
  name: string;
  currency: Currency2;
  address?: string | undefined;
  enforceMfa?: boolean | undefined;
  /**
   * Supported only for first team creation
   */
  referredCode?: string | undefined;
};

export type PostTeamData2 = {
  type: PostTeamType2;
  attributes?: PostTeamAttributes2 | undefined;
};

export type PostTeamRequest = {
  data: PostTeamData2;
};

export type PostTeamMeta = {
  /**
   * Create-only session token to authenticate follow-up requests against the new team
   */
  sessionToken?: string | undefined;
};

/**
 * Created
 */
export type PostTeamResponse = {
  data?: models.Team | undefined;
  meta?: PostTeamMeta | undefined;
};

/** @internal */
export const PostTeamType2$inboundSchema: z.ZodNativeEnum<
  typeof PostTeamType2
> = z.nativeEnum(PostTeamType2);
/** @internal */
export const PostTeamType2$outboundSchema: z.ZodNativeEnum<
  typeof PostTeamType2
> = PostTeamType2$inboundSchema;

/** @internal */
export const Currency2$inboundSchema: z.ZodNativeEnum<typeof Currency2> = z
  .nativeEnum(Currency2);
/** @internal */
export const Currency2$outboundSchema: z.ZodNativeEnum<typeof Currency2> =
  Currency2$inboundSchema;

/** @internal */
export const PostTeamAttributes2$inboundSchema: z.ZodType<
  PostTeamAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  currency: Currency2$inboundSchema,
  address: z.string().optional(),
  enforce_mfa: z.boolean().optional(),
  referred_code: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "enforce_mfa": "enforceMfa",
    "referred_code": "referredCode",
  });
});
/** @internal */
export type PostTeamAttributes2$Outbound = {
  name: string;
  currency: string;
  address?: string | undefined;
  enforce_mfa?: boolean | undefined;
  referred_code?: string | undefined;
};

/** @internal */
export const PostTeamAttributes2$outboundSchema: z.ZodType<
  PostTeamAttributes2$Outbound,
  z.ZodTypeDef,
  PostTeamAttributes2
> = z.object({
  name: z.string(),
  currency: Currency2$outboundSchema,
  address: z.string().optional(),
  enforceMfa: z.boolean().optional(),
  referredCode: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    enforceMfa: "enforce_mfa",
    referredCode: "referred_code",
  });
});

export function postTeamAttributes2ToJSON(
  postTeamAttributes2: PostTeamAttributes2,
): string {
  return JSON.stringify(
    PostTeamAttributes2$outboundSchema.parse(postTeamAttributes2),
  );
}
export function postTeamAttributes2FromJSON(
  jsonString: string,
): SafeParseResult<PostTeamAttributes2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTeamAttributes2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTeamAttributes2' from JSON`,
  );
}

/** @internal */
export const PostTeamData2$inboundSchema: z.ZodType<
  PostTeamData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PostTeamType2$inboundSchema,
  attributes: z.lazy(() => PostTeamAttributes2$inboundSchema).optional(),
});
/** @internal */
export type PostTeamData2$Outbound = {
  type: string;
  attributes?: PostTeamAttributes2$Outbound | undefined;
};

/** @internal */
export const PostTeamData2$outboundSchema: z.ZodType<
  PostTeamData2$Outbound,
  z.ZodTypeDef,
  PostTeamData2
> = z.object({
  type: PostTeamType2$outboundSchema,
  attributes: z.lazy(() => PostTeamAttributes2$outboundSchema).optional(),
});

export function postTeamData2ToJSON(postTeamData2: PostTeamData2): string {
  return JSON.stringify(PostTeamData2$outboundSchema.parse(postTeamData2));
}
export function postTeamData2FromJSON(
  jsonString: string,
): SafeParseResult<PostTeamData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTeamData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTeamData2' from JSON`,
  );
}

/** @internal */
export const PostTeamRequest$inboundSchema: z.ZodType<
  PostTeamRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => PostTeamData2$inboundSchema),
});
/** @internal */
export type PostTeamRequest$Outbound = {
  data: PostTeamData2$Outbound;
};

/** @internal */
export const PostTeamRequest$outboundSchema: z.ZodType<
  PostTeamRequest$Outbound,
  z.ZodTypeDef,
  PostTeamRequest
> = z.object({
  data: z.lazy(() => PostTeamData2$outboundSchema),
});

export function postTeamRequestToJSON(
  postTeamRequest: PostTeamRequest,
): string {
  return JSON.stringify(PostTeamRequest$outboundSchema.parse(postTeamRequest));
}
export function postTeamRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostTeamRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTeamRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTeamRequest' from JSON`,
  );
}

/** @internal */
export const PostTeamMeta$inboundSchema: z.ZodType<
  PostTeamMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  session_token: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "session_token": "sessionToken",
  });
});
/** @internal */
export type PostTeamMeta$Outbound = {
  session_token?: string | undefined;
};

/** @internal */
export const PostTeamMeta$outboundSchema: z.ZodType<
  PostTeamMeta$Outbound,
  z.ZodTypeDef,
  PostTeamMeta
> = z.object({
  sessionToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    sessionToken: "session_token",
  });
});

export function postTeamMetaToJSON(postTeamMeta: PostTeamMeta): string {
  return JSON.stringify(PostTeamMeta$outboundSchema.parse(postTeamMeta));
}
export function postTeamMetaFromJSON(
  jsonString: string,
): SafeParseResult<PostTeamMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTeamMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTeamMeta' from JSON`,
  );
}

/** @internal */
export const PostTeamResponse$inboundSchema: z.ZodType<
  PostTeamResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.Team$inboundSchema.optional(),
  meta: z.lazy(() => PostTeamMeta$inboundSchema).optional(),
});
/** @internal */
export type PostTeamResponse$Outbound = {
  data?: models.Team$Outbound | undefined;
  meta?: PostTeamMeta$Outbound | undefined;
};

/** @internal */
export const PostTeamResponse$outboundSchema: z.ZodType<
  PostTeamResponse$Outbound,
  z.ZodTypeDef,
  PostTeamResponse
> = z.object({
  data: models.Team$outboundSchema.optional(),
  meta: z.lazy(() => PostTeamMeta$outboundSchema).optional(),
});

export function postTeamResponseToJSON(
  postTeamResponse: PostTeamResponse,
): string {
  return JSON.stringify(
    PostTeamResponse$outboundSchema.parse(postTeamResponse),
  );
}
export function postTeamResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostTeamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTeamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTeamResponse' from JSON`,
  );
}
