/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const PostVpnSessionType2 = {
  VpnSessions: "vpn_sessions",
} as const;
export type PostVpnSessionType2 = ClosedEnum<typeof PostVpnSessionType2>;

export const PostVpnSessionSite2 = {
  Ash: "ASH",
  Bgt: "BGT",
  Bue: "BUE",
  Chi: "CHI",
  Dal: "DAL",
  Fra: "FRA",
  Lax: "LAX",
  Lon: "LON",
  Mex: "MEX",
  Mex2: "MEX2",
  Mia: "MIA",
  Mia2: "MIA2",
  Nyc: "NYC",
  San: "SAN",
  Sao: "SAO",
  Sao2: "SAO2",
  Syd: "SYD",
  Tyo: "TYO",
  Tyo2: "TYO2",
} as const;
export type PostVpnSessionSite2 = ClosedEnum<typeof PostVpnSessionSite2>;

export type PostVpnSessionAttributes2 = {
  site?: PostVpnSessionSite2 | undefined;
  serverId?: string | undefined;
};

export type PostVpnSessionData2 = {
  type?: PostVpnSessionType2 | undefined;
  attributes?: PostVpnSessionAttributes2 | undefined;
};

export type PostVpnSessionRequest = {
  data?: PostVpnSessionData2 | undefined;
};

/** @internal */
export const PostVpnSessionType2$inboundSchema: z.ZodNativeEnum<
  typeof PostVpnSessionType2
> = z.nativeEnum(PostVpnSessionType2);

/** @internal */
export const PostVpnSessionType2$outboundSchema: z.ZodNativeEnum<
  typeof PostVpnSessionType2
> = PostVpnSessionType2$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVpnSessionType2$ {
  /** @deprecated use `PostVpnSessionType2$inboundSchema` instead. */
  export const inboundSchema = PostVpnSessionType2$inboundSchema;
  /** @deprecated use `PostVpnSessionType2$outboundSchema` instead. */
  export const outboundSchema = PostVpnSessionType2$outboundSchema;
}

/** @internal */
export const PostVpnSessionSite2$inboundSchema: z.ZodNativeEnum<
  typeof PostVpnSessionSite2
> = z.nativeEnum(PostVpnSessionSite2);

/** @internal */
export const PostVpnSessionSite2$outboundSchema: z.ZodNativeEnum<
  typeof PostVpnSessionSite2
> = PostVpnSessionSite2$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVpnSessionSite2$ {
  /** @deprecated use `PostVpnSessionSite2$inboundSchema` instead. */
  export const inboundSchema = PostVpnSessionSite2$inboundSchema;
  /** @deprecated use `PostVpnSessionSite2$outboundSchema` instead. */
  export const outboundSchema = PostVpnSessionSite2$outboundSchema;
}

/** @internal */
export const PostVpnSessionAttributes2$inboundSchema: z.ZodType<
  PostVpnSessionAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  site: PostVpnSessionSite2$inboundSchema.optional(),
  server_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "server_id": "serverId",
  });
});

/** @internal */
export type PostVpnSessionAttributes2$Outbound = {
  site?: string | undefined;
  server_id?: string | undefined;
};

/** @internal */
export const PostVpnSessionAttributes2$outboundSchema: z.ZodType<
  PostVpnSessionAttributes2$Outbound,
  z.ZodTypeDef,
  PostVpnSessionAttributes2
> = z.object({
  site: PostVpnSessionSite2$outboundSchema.optional(),
  serverId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    serverId: "server_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVpnSessionAttributes2$ {
  /** @deprecated use `PostVpnSessionAttributes2$inboundSchema` instead. */
  export const inboundSchema = PostVpnSessionAttributes2$inboundSchema;
  /** @deprecated use `PostVpnSessionAttributes2$outboundSchema` instead. */
  export const outboundSchema = PostVpnSessionAttributes2$outboundSchema;
  /** @deprecated use `PostVpnSessionAttributes2$Outbound` instead. */
  export type Outbound = PostVpnSessionAttributes2$Outbound;
}

export function postVpnSessionAttributes2ToJSON(
  postVpnSessionAttributes2: PostVpnSessionAttributes2,
): string {
  return JSON.stringify(
    PostVpnSessionAttributes2$outboundSchema.parse(postVpnSessionAttributes2),
  );
}

export function postVpnSessionAttributes2FromJSON(
  jsonString: string,
): SafeParseResult<PostVpnSessionAttributes2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostVpnSessionAttributes2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostVpnSessionAttributes2' from JSON`,
  );
}

/** @internal */
export const PostVpnSessionData2$inboundSchema: z.ZodType<
  PostVpnSessionData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PostVpnSessionType2$inboundSchema.optional(),
  attributes: z.lazy(() => PostVpnSessionAttributes2$inboundSchema).optional(),
});

/** @internal */
export type PostVpnSessionData2$Outbound = {
  type?: string | undefined;
  attributes?: PostVpnSessionAttributes2$Outbound | undefined;
};

/** @internal */
export const PostVpnSessionData2$outboundSchema: z.ZodType<
  PostVpnSessionData2$Outbound,
  z.ZodTypeDef,
  PostVpnSessionData2
> = z.object({
  type: PostVpnSessionType2$outboundSchema.optional(),
  attributes: z.lazy(() => PostVpnSessionAttributes2$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVpnSessionData2$ {
  /** @deprecated use `PostVpnSessionData2$inboundSchema` instead. */
  export const inboundSchema = PostVpnSessionData2$inboundSchema;
  /** @deprecated use `PostVpnSessionData2$outboundSchema` instead. */
  export const outboundSchema = PostVpnSessionData2$outboundSchema;
  /** @deprecated use `PostVpnSessionData2$Outbound` instead. */
  export type Outbound = PostVpnSessionData2$Outbound;
}

export function postVpnSessionData2ToJSON(
  postVpnSessionData2: PostVpnSessionData2,
): string {
  return JSON.stringify(
    PostVpnSessionData2$outboundSchema.parse(postVpnSessionData2),
  );
}

export function postVpnSessionData2FromJSON(
  jsonString: string,
): SafeParseResult<PostVpnSessionData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostVpnSessionData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostVpnSessionData2' from JSON`,
  );
}

/** @internal */
export const PostVpnSessionRequest$inboundSchema: z.ZodType<
  PostVpnSessionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => PostVpnSessionData2$inboundSchema).optional(),
});

/** @internal */
export type PostVpnSessionRequest$Outbound = {
  data?: PostVpnSessionData2$Outbound | undefined;
};

/** @internal */
export const PostVpnSessionRequest$outboundSchema: z.ZodType<
  PostVpnSessionRequest$Outbound,
  z.ZodTypeDef,
  PostVpnSessionRequest
> = z.object({
  data: z.lazy(() => PostVpnSessionData2$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostVpnSessionRequest$ {
  /** @deprecated use `PostVpnSessionRequest$inboundSchema` instead. */
  export const inboundSchema = PostVpnSessionRequest$inboundSchema;
  /** @deprecated use `PostVpnSessionRequest$outboundSchema` instead. */
  export const outboundSchema = PostVpnSessionRequest$outboundSchema;
  /** @deprecated use `PostVpnSessionRequest$Outbound` instead. */
  export type Outbound = PostVpnSessionRequest$Outbound;
}

export function postVpnSessionRequestToJSON(
  postVpnSessionRequest: PostVpnSessionRequest,
): string {
  return JSON.stringify(
    PostVpnSessionRequest$outboundSchema.parse(postVpnSessionRequest),
  );
}

export function postVpnSessionRequestFromJSON(
  jsonString: string,
): SafeParseResult<PostVpnSessionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostVpnSessionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostVpnSessionRequest' from JSON`,
  );
}
