/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ServerUnscheduleDeletionRequest = {
  serverId: string;
};

/** @internal */
export const ServerUnscheduleDeletionRequest$inboundSchema: z.ZodType<
  ServerUnscheduleDeletionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  server_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "server_id": "serverId",
  });
});
/** @internal */
export type ServerUnscheduleDeletionRequest$Outbound = {
  server_id: string;
};

/** @internal */
export const ServerUnscheduleDeletionRequest$outboundSchema: z.ZodType<
  ServerUnscheduleDeletionRequest$Outbound,
  z.ZodTypeDef,
  ServerUnscheduleDeletionRequest
> = z.object({
  serverId: z.string(),
}).transform((v) => {
  return remap$(v, {
    serverId: "server_id",
  });
});

export function serverUnscheduleDeletionRequestToJSON(
  serverUnscheduleDeletionRequest: ServerUnscheduleDeletionRequest,
): string {
  return JSON.stringify(
    ServerUnscheduleDeletionRequest$outboundSchema.parse(
      serverUnscheduleDeletionRequest,
    ),
  );
}
export function serverUnscheduleDeletionRequestFromJSON(
  jsonString: string,
): SafeParseResult<ServerUnscheduleDeletionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerUnscheduleDeletionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerUnscheduleDeletionRequest' from JSON`,
  );
}
