/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ServerStartRescueModeRequest = {
  serverId: string;
};

/** @internal */
export const ServerStartRescueModeRequest$inboundSchema: z.ZodType<
  ServerStartRescueModeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  server_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "server_id": "serverId",
  });
});
/** @internal */
export type ServerStartRescueModeRequest$Outbound = {
  server_id: string;
};

/** @internal */
export const ServerStartRescueModeRequest$outboundSchema: z.ZodType<
  ServerStartRescueModeRequest$Outbound,
  z.ZodTypeDef,
  ServerStartRescueModeRequest
> = z.object({
  serverId: z.string(),
}).transform((v) => {
  return remap$(v, {
    serverId: "server_id",
  });
});

export function serverStartRescueModeRequestToJSON(
  serverStartRescueModeRequest: ServerStartRescueModeRequest,
): string {
  return JSON.stringify(
    ServerStartRescueModeRequest$outboundSchema.parse(
      serverStartRescueModeRequest,
    ),
  );
}
export function serverStartRescueModeRequestFromJSON(
  jsonString: string,
): SafeParseResult<ServerStartRescueModeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerStartRescueModeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerStartRescueModeRequest' from JSON`,
  );
}
