/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ShowVirtualMachineRequest = {
  virtualMachineId: string;
};

/** @internal */
export const ShowVirtualMachineRequest$inboundSchema: z.ZodType<
  ShowVirtualMachineRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  virtual_machine_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "virtual_machine_id": "virtualMachineId",
  });
});
/** @internal */
export type ShowVirtualMachineRequest$Outbound = {
  virtual_machine_id: string;
};

/** @internal */
export const ShowVirtualMachineRequest$outboundSchema: z.ZodType<
  ShowVirtualMachineRequest$Outbound,
  z.ZodTypeDef,
  ShowVirtualMachineRequest
> = z.object({
  virtualMachineId: z.string(),
}).transform((v) => {
  return remap$(v, {
    virtualMachineId: "virtual_machine_id",
  });
});

export function showVirtualMachineRequestToJSON(
  showVirtualMachineRequest: ShowVirtualMachineRequest,
): string {
  return JSON.stringify(
    ShowVirtualMachineRequest$outboundSchema.parse(showVirtualMachineRequest),
  );
}
export function showVirtualMachineRequestFromJSON(
  jsonString: string,
): SafeParseResult<ShowVirtualMachineRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ShowVirtualMachineRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ShowVirtualMachineRequest' from JSON`,
  );
}
