/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UpdateKubernetesClusterRequest = {
  /**
   * The cluster ID (format: kc_<hash>) or cluster name. Both formats are accepted for backward compatibility.
   */
  kubernetesClusterId: string;
  updateKubernetesCluster: models.UpdateKubernetesCluster;
};

/** @internal */
export const UpdateKubernetesClusterRequest$inboundSchema: z.ZodType<
  UpdateKubernetesClusterRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  kubernetes_cluster_id: z.string(),
  update_kubernetes_cluster: models.UpdateKubernetesCluster$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "kubernetes_cluster_id": "kubernetesClusterId",
    "update_kubernetes_cluster": "updateKubernetesCluster",
  });
});
/** @internal */
export type UpdateKubernetesClusterRequest$Outbound = {
  kubernetes_cluster_id: string;
  update_kubernetes_cluster: models.UpdateKubernetesCluster$Outbound;
};

/** @internal */
export const UpdateKubernetesClusterRequest$outboundSchema: z.ZodType<
  UpdateKubernetesClusterRequest$Outbound,
  z.ZodTypeDef,
  UpdateKubernetesClusterRequest
> = z.object({
  kubernetesClusterId: z.string(),
  updateKubernetesCluster: models.UpdateKubernetesCluster$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    kubernetesClusterId: "kubernetes_cluster_id",
    updateKubernetesCluster: "update_kubernetes_cluster",
  });
});

export function updateKubernetesClusterRequestToJSON(
  updateKubernetesClusterRequest: UpdateKubernetesClusterRequest,
): string {
  return JSON.stringify(
    UpdateKubernetesClusterRequest$outboundSchema.parse(
      updateKubernetesClusterRequest,
    ),
  );
}
export function updateKubernetesClusterRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateKubernetesClusterRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateKubernetesClusterRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateKubernetesClusterRequest' from JSON`,
  );
}
