/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UpdateApiKeyRequest = {
  apiKeyId: string;
  updateApiKey: models.UpdateApiKey;
};

/**
 * Success - Update name without rotating token
 */
export type UpdateApiKeyResponse = {
  data?: models.ApiKey | undefined;
};

/** @internal */
export const UpdateApiKeyRequest$inboundSchema: z.ZodType<
  UpdateApiKeyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  api_key_id: z.string(),
  update_api_key: models.UpdateApiKey$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "api_key_id": "apiKeyId",
    "update_api_key": "updateApiKey",
  });
});
/** @internal */
export type UpdateApiKeyRequest$Outbound = {
  api_key_id: string;
  update_api_key: models.UpdateApiKey$Outbound;
};

/** @internal */
export const UpdateApiKeyRequest$outboundSchema: z.ZodType<
  UpdateApiKeyRequest$Outbound,
  z.ZodTypeDef,
  UpdateApiKeyRequest
> = z.object({
  apiKeyId: z.string(),
  updateApiKey: models.UpdateApiKey$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    apiKeyId: "api_key_id",
    updateApiKey: "update_api_key",
  });
});

export function updateApiKeyRequestToJSON(
  updateApiKeyRequest: UpdateApiKeyRequest,
): string {
  return JSON.stringify(
    UpdateApiKeyRequest$outboundSchema.parse(updateApiKeyRequest),
  );
}
export function updateApiKeyRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApiKeyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateApiKeyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApiKeyRequest' from JSON`,
  );
}

/** @internal */
export const UpdateApiKeyResponse$inboundSchema: z.ZodType<
  UpdateApiKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: models.ApiKey$inboundSchema.optional(),
});
/** @internal */
export type UpdateApiKeyResponse$Outbound = {
  data?: models.ApiKey$Outbound | undefined;
};

/** @internal */
export const UpdateApiKeyResponse$outboundSchema: z.ZodType<
  UpdateApiKeyResponse$Outbound,
  z.ZodTypeDef,
  UpdateApiKeyResponse
> = z.object({
  data: models.ApiKey$outboundSchema.optional(),
});

export function updateApiKeyResponseToJSON(
  updateApiKeyResponse: UpdateApiKeyResponse,
): string {
  return JSON.stringify(
    UpdateApiKeyResponse$outboundSchema.parse(updateApiKeyResponse),
  );
}
export function updateApiKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateApiKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateApiKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateApiKeyResponse' from JSON`,
  );
}
