/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UpdatePublicNetworkIpRequest = {
  id: string;
  updatePublicNetworkIp: models.UpdatePublicNetworkIp;
};

/** @internal */
export const UpdatePublicNetworkIpRequest$inboundSchema: z.ZodType<
  UpdatePublicNetworkIpRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  update_public_network_ip: models.UpdatePublicNetworkIp$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "update_public_network_ip": "updatePublicNetworkIp",
  });
});
/** @internal */
export type UpdatePublicNetworkIpRequest$Outbound = {
  id: string;
  update_public_network_ip: models.UpdatePublicNetworkIp$Outbound;
};

/** @internal */
export const UpdatePublicNetworkIpRequest$outboundSchema: z.ZodType<
  UpdatePublicNetworkIpRequest$Outbound,
  z.ZodTypeDef,
  UpdatePublicNetworkIpRequest
> = z.object({
  id: z.string(),
  updatePublicNetworkIp: models.UpdatePublicNetworkIp$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updatePublicNetworkIp: "update_public_network_ip",
  });
});

export function updatePublicNetworkIpRequestToJSON(
  updatePublicNetworkIpRequest: UpdatePublicNetworkIpRequest,
): string {
  return JSON.stringify(
    UpdatePublicNetworkIpRequest$outboundSchema.parse(
      updatePublicNetworkIpRequest,
    ),
  );
}
export function updatePublicNetworkIpRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePublicNetworkIpRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePublicNetworkIpRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePublicNetworkIpRequest' from JSON`,
  );
}
