/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const UpdatePlansBandwidthType2 = {
  BandwidthPackages: "bandwidth_packages",
} as const;
export type UpdatePlansBandwidthType2 = ClosedEnum<
  typeof UpdatePlansBandwidthType2
>;

export type UpdatePlansBandwidthAttributes2 = {
  /**
   * The project (ID or Slug) to add bandwidth
   */
  project?: string | undefined;
  /**
   * The total amount you want to have
   */
  quantity?: number | undefined;
  /**
   * The region to add bandwidth
   */
  regionSlug?: string | undefined;
};

export type UpdatePlansBandwidthData2 = {
  type?: UpdatePlansBandwidthType2 | undefined;
  attributes?: UpdatePlansBandwidthAttributes2 | undefined;
};

export type UpdatePlansBandwidthRequest = {
  data?: UpdatePlansBandwidthData2 | undefined;
};

/** @internal */
export const UpdatePlansBandwidthType2$inboundSchema: z.ZodNativeEnum<
  typeof UpdatePlansBandwidthType2
> = z.nativeEnum(UpdatePlansBandwidthType2);
/** @internal */
export const UpdatePlansBandwidthType2$outboundSchema: z.ZodNativeEnum<
  typeof UpdatePlansBandwidthType2
> = UpdatePlansBandwidthType2$inboundSchema;

/** @internal */
export const UpdatePlansBandwidthAttributes2$inboundSchema: z.ZodType<
  UpdatePlansBandwidthAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  project: z.string().optional(),
  quantity: z.number().int().optional(),
  region_slug: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "region_slug": "regionSlug",
  });
});
/** @internal */
export type UpdatePlansBandwidthAttributes2$Outbound = {
  project?: string | undefined;
  quantity?: number | undefined;
  region_slug?: string | undefined;
};

/** @internal */
export const UpdatePlansBandwidthAttributes2$outboundSchema: z.ZodType<
  UpdatePlansBandwidthAttributes2$Outbound,
  z.ZodTypeDef,
  UpdatePlansBandwidthAttributes2
> = z.object({
  project: z.string().optional(),
  quantity: z.number().int().optional(),
  regionSlug: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    regionSlug: "region_slug",
  });
});

export function updatePlansBandwidthAttributes2ToJSON(
  updatePlansBandwidthAttributes2: UpdatePlansBandwidthAttributes2,
): string {
  return JSON.stringify(
    UpdatePlansBandwidthAttributes2$outboundSchema.parse(
      updatePlansBandwidthAttributes2,
    ),
  );
}
export function updatePlansBandwidthAttributes2FromJSON(
  jsonString: string,
): SafeParseResult<UpdatePlansBandwidthAttributes2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePlansBandwidthAttributes2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePlansBandwidthAttributes2' from JSON`,
  );
}

/** @internal */
export const UpdatePlansBandwidthData2$inboundSchema: z.ZodType<
  UpdatePlansBandwidthData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: UpdatePlansBandwidthType2$inboundSchema.optional(),
  attributes: z.lazy(() => UpdatePlansBandwidthAttributes2$inboundSchema)
    .optional(),
});
/** @internal */
export type UpdatePlansBandwidthData2$Outbound = {
  type?: string | undefined;
  attributes?: UpdatePlansBandwidthAttributes2$Outbound | undefined;
};

/** @internal */
export const UpdatePlansBandwidthData2$outboundSchema: z.ZodType<
  UpdatePlansBandwidthData2$Outbound,
  z.ZodTypeDef,
  UpdatePlansBandwidthData2
> = z.object({
  type: UpdatePlansBandwidthType2$outboundSchema.optional(),
  attributes: z.lazy(() => UpdatePlansBandwidthAttributes2$outboundSchema)
    .optional(),
});

export function updatePlansBandwidthData2ToJSON(
  updatePlansBandwidthData2: UpdatePlansBandwidthData2,
): string {
  return JSON.stringify(
    UpdatePlansBandwidthData2$outboundSchema.parse(updatePlansBandwidthData2),
  );
}
export function updatePlansBandwidthData2FromJSON(
  jsonString: string,
): SafeParseResult<UpdatePlansBandwidthData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePlansBandwidthData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePlansBandwidthData2' from JSON`,
  );
}

/** @internal */
export const UpdatePlansBandwidthRequest$inboundSchema: z.ZodType<
  UpdatePlansBandwidthRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => UpdatePlansBandwidthData2$inboundSchema).optional(),
});
/** @internal */
export type UpdatePlansBandwidthRequest$Outbound = {
  data?: UpdatePlansBandwidthData2$Outbound | undefined;
};

/** @internal */
export const UpdatePlansBandwidthRequest$outboundSchema: z.ZodType<
  UpdatePlansBandwidthRequest$Outbound,
  z.ZodTypeDef,
  UpdatePlansBandwidthRequest
> = z.object({
  data: z.lazy(() => UpdatePlansBandwidthData2$outboundSchema).optional(),
});

export function updatePlansBandwidthRequestToJSON(
  updatePlansBandwidthRequest: UpdatePlansBandwidthRequest,
): string {
  return JSON.stringify(
    UpdatePlansBandwidthRequest$outboundSchema.parse(
      updatePlansBandwidthRequest,
    ),
  );
}
export function updatePlansBandwidthRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePlansBandwidthRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePlansBandwidthRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePlansBandwidthRequest' from JSON`,
  );
}
