/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const UpdateVirtualNetworkType2 = {
  VirtualNetworks: "virtual_networks",
} as const;
export type UpdateVirtualNetworkType2 = ClosedEnum<
  typeof UpdateVirtualNetworkType2
>;

export type UpdateVirtualNetworkAttributes2 = {
  tags?: Array<string> | undefined;
  description?: string | undefined;
};

export type UpdateVirtualNetworkData2 = {
  id: string;
  type: UpdateVirtualNetworkType2;
  attributes?: UpdateVirtualNetworkAttributes2 | undefined;
};

export type UpdateVirtualNetworkRequestBody2 = {
  data: UpdateVirtualNetworkData2;
};

export type UpdateVirtualNetworkRequest = {
  /**
   * The Virtual Network ID
   */
  vlanId: string;
  requestBody: UpdateVirtualNetworkRequestBody2;
};

/** @internal */
export const UpdateVirtualNetworkType2$inboundSchema: z.ZodNativeEnum<
  typeof UpdateVirtualNetworkType2
> = z.nativeEnum(UpdateVirtualNetworkType2);
/** @internal */
export const UpdateVirtualNetworkType2$outboundSchema: z.ZodNativeEnum<
  typeof UpdateVirtualNetworkType2
> = UpdateVirtualNetworkType2$inboundSchema;

/** @internal */
export const UpdateVirtualNetworkAttributes2$inboundSchema: z.ZodType<
  UpdateVirtualNetworkAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  tags: z.array(z.string()).optional(),
  description: z.string().default("Test virtual network update"),
});
/** @internal */
export type UpdateVirtualNetworkAttributes2$Outbound = {
  tags?: Array<string> | undefined;
  description: string;
};

/** @internal */
export const UpdateVirtualNetworkAttributes2$outboundSchema: z.ZodType<
  UpdateVirtualNetworkAttributes2$Outbound,
  z.ZodTypeDef,
  UpdateVirtualNetworkAttributes2
> = z.object({
  tags: z.array(z.string()).optional(),
  description: z.string().default("Test virtual network update"),
});

export function updateVirtualNetworkAttributes2ToJSON(
  updateVirtualNetworkAttributes2: UpdateVirtualNetworkAttributes2,
): string {
  return JSON.stringify(
    UpdateVirtualNetworkAttributes2$outboundSchema.parse(
      updateVirtualNetworkAttributes2,
    ),
  );
}
export function updateVirtualNetworkAttributes2FromJSON(
  jsonString: string,
): SafeParseResult<UpdateVirtualNetworkAttributes2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateVirtualNetworkAttributes2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateVirtualNetworkAttributes2' from JSON`,
  );
}

/** @internal */
export const UpdateVirtualNetworkData2$inboundSchema: z.ZodType<
  UpdateVirtualNetworkData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: UpdateVirtualNetworkType2$inboundSchema,
  attributes: z.lazy(() => UpdateVirtualNetworkAttributes2$inboundSchema)
    .optional(),
});
/** @internal */
export type UpdateVirtualNetworkData2$Outbound = {
  id: string;
  type: string;
  attributes?: UpdateVirtualNetworkAttributes2$Outbound | undefined;
};

/** @internal */
export const UpdateVirtualNetworkData2$outboundSchema: z.ZodType<
  UpdateVirtualNetworkData2$Outbound,
  z.ZodTypeDef,
  UpdateVirtualNetworkData2
> = z.object({
  id: z.string(),
  type: UpdateVirtualNetworkType2$outboundSchema,
  attributes: z.lazy(() => UpdateVirtualNetworkAttributes2$outboundSchema)
    .optional(),
});

export function updateVirtualNetworkData2ToJSON(
  updateVirtualNetworkData2: UpdateVirtualNetworkData2,
): string {
  return JSON.stringify(
    UpdateVirtualNetworkData2$outboundSchema.parse(updateVirtualNetworkData2),
  );
}
export function updateVirtualNetworkData2FromJSON(
  jsonString: string,
): SafeParseResult<UpdateVirtualNetworkData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateVirtualNetworkData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateVirtualNetworkData2' from JSON`,
  );
}

/** @internal */
export const UpdateVirtualNetworkRequestBody2$inboundSchema: z.ZodType<
  UpdateVirtualNetworkRequestBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => UpdateVirtualNetworkData2$inboundSchema),
});
/** @internal */
export type UpdateVirtualNetworkRequestBody2$Outbound = {
  data: UpdateVirtualNetworkData2$Outbound;
};

/** @internal */
export const UpdateVirtualNetworkRequestBody2$outboundSchema: z.ZodType<
  UpdateVirtualNetworkRequestBody2$Outbound,
  z.ZodTypeDef,
  UpdateVirtualNetworkRequestBody2
> = z.object({
  data: z.lazy(() => UpdateVirtualNetworkData2$outboundSchema),
});

export function updateVirtualNetworkRequestBody2ToJSON(
  updateVirtualNetworkRequestBody2: UpdateVirtualNetworkRequestBody2,
): string {
  return JSON.stringify(
    UpdateVirtualNetworkRequestBody2$outboundSchema.parse(
      updateVirtualNetworkRequestBody2,
    ),
  );
}
export function updateVirtualNetworkRequestBody2FromJSON(
  jsonString: string,
): SafeParseResult<UpdateVirtualNetworkRequestBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateVirtualNetworkRequestBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateVirtualNetworkRequestBody2' from JSON`,
  );
}

/** @internal */
export const UpdateVirtualNetworkRequest$inboundSchema: z.ZodType<
  UpdateVirtualNetworkRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  vlan_id: z.string(),
  RequestBody: z.lazy(() => UpdateVirtualNetworkRequestBody2$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "vlan_id": "vlanId",
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type UpdateVirtualNetworkRequest$Outbound = {
  vlan_id: string;
  RequestBody: UpdateVirtualNetworkRequestBody2$Outbound;
};

/** @internal */
export const UpdateVirtualNetworkRequest$outboundSchema: z.ZodType<
  UpdateVirtualNetworkRequest$Outbound,
  z.ZodTypeDef,
  UpdateVirtualNetworkRequest
> = z.object({
  vlanId: z.string(),
  requestBody: z.lazy(() => UpdateVirtualNetworkRequestBody2$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    vlanId: "vlan_id",
    requestBody: "RequestBody",
  });
});

export function updateVirtualNetworkRequestToJSON(
  updateVirtualNetworkRequest: UpdateVirtualNetworkRequest,
): string {
  return JSON.stringify(
    UpdateVirtualNetworkRequest$outboundSchema.parse(
      updateVirtualNetworkRequest,
    ),
  );
}
export function updateVirtualNetworkRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateVirtualNetworkRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateVirtualNetworkRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateVirtualNetworkRequest' from JSON`,
  );
}
