/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const UpdateServerType2 = {
  Servers: "servers",
} as const;
export type UpdateServerType2 = ClosedEnum<typeof UpdateServerType2>;

/**
 * The server billing type. Accepts `hourly` and `monthly` for on demand projects and `yearly` for reserved projects.
 */
export const UpdateServerBilling2 = {
  Hourly: "hourly",
  Monthly: "monthly",
  Yearly: "yearly",
} as const;
/**
 * The server billing type. Accepts `hourly` and `monthly` for on demand projects and `yearly` for reserved projects.
 */
export type UpdateServerBilling2 = ClosedEnum<typeof UpdateServerBilling2>;

export type UpdateServerAttributes2 = {
  hostname?: string | undefined;
  /**
   * The server billing type. Accepts `hourly` and `monthly` for on demand projects and `yearly` for reserved projects.
   */
  billing?: UpdateServerBilling2 | null | undefined;
  /**
   * List of Tag IDs
   */
  tags?: Array<string> | null | undefined;
  /**
   * Project ID or slug to move the server to
   */
  project?: string | undefined;
};

export type UpdateServerData2 = {
  id?: string | undefined;
  type?: UpdateServerType2 | undefined;
  attributes?: UpdateServerAttributes2 | undefined;
};

export type UpdateServerRequestBody2 = {
  data?: UpdateServerData2 | undefined;
};

export type UpdateServerRequest = {
  serverId: string;
  requestBody: UpdateServerRequestBody2;
};

/** @internal */
export const UpdateServerType2$inboundSchema: z.ZodNativeEnum<
  typeof UpdateServerType2
> = z.nativeEnum(UpdateServerType2);
/** @internal */
export const UpdateServerType2$outboundSchema: z.ZodNativeEnum<
  typeof UpdateServerType2
> = UpdateServerType2$inboundSchema;

/** @internal */
export const UpdateServerBilling2$inboundSchema: z.ZodNativeEnum<
  typeof UpdateServerBilling2
> = z.nativeEnum(UpdateServerBilling2);
/** @internal */
export const UpdateServerBilling2$outboundSchema: z.ZodNativeEnum<
  typeof UpdateServerBilling2
> = UpdateServerBilling2$inboundSchema;

/** @internal */
export const UpdateServerAttributes2$inboundSchema: z.ZodType<
  UpdateServerAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  hostname: z.string().default("new-hostname"),
  billing: z.nullable(UpdateServerBilling2$inboundSchema).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  project: z.string().optional(),
});
/** @internal */
export type UpdateServerAttributes2$Outbound = {
  hostname: string;
  billing?: string | null | undefined;
  tags?: Array<string> | null | undefined;
  project?: string | undefined;
};

/** @internal */
export const UpdateServerAttributes2$outboundSchema: z.ZodType<
  UpdateServerAttributes2$Outbound,
  z.ZodTypeDef,
  UpdateServerAttributes2
> = z.object({
  hostname: z.string().default("new-hostname"),
  billing: z.nullable(UpdateServerBilling2$outboundSchema).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  project: z.string().optional(),
});

export function updateServerAttributes2ToJSON(
  updateServerAttributes2: UpdateServerAttributes2,
): string {
  return JSON.stringify(
    UpdateServerAttributes2$outboundSchema.parse(updateServerAttributes2),
  );
}
export function updateServerAttributes2FromJSON(
  jsonString: string,
): SafeParseResult<UpdateServerAttributes2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateServerAttributes2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateServerAttributes2' from JSON`,
  );
}

/** @internal */
export const UpdateServerData2$inboundSchema: z.ZodType<
  UpdateServerData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().default("sv_81EVOtR1N4J2Z"),
  type: UpdateServerType2$inboundSchema.optional(),
  attributes: z.lazy(() => UpdateServerAttributes2$inboundSchema).optional(),
});
/** @internal */
export type UpdateServerData2$Outbound = {
  id: string;
  type?: string | undefined;
  attributes?: UpdateServerAttributes2$Outbound | undefined;
};

/** @internal */
export const UpdateServerData2$outboundSchema: z.ZodType<
  UpdateServerData2$Outbound,
  z.ZodTypeDef,
  UpdateServerData2
> = z.object({
  id: z.string().default("sv_81EVOtR1N4J2Z"),
  type: UpdateServerType2$outboundSchema.optional(),
  attributes: z.lazy(() => UpdateServerAttributes2$outboundSchema).optional(),
});

export function updateServerData2ToJSON(
  updateServerData2: UpdateServerData2,
): string {
  return JSON.stringify(
    UpdateServerData2$outboundSchema.parse(updateServerData2),
  );
}
export function updateServerData2FromJSON(
  jsonString: string,
): SafeParseResult<UpdateServerData2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateServerData2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateServerData2' from JSON`,
  );
}

/** @internal */
export const UpdateServerRequestBody2$inboundSchema: z.ZodType<
  UpdateServerRequestBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => UpdateServerData2$inboundSchema).optional(),
});
/** @internal */
export type UpdateServerRequestBody2$Outbound = {
  data?: UpdateServerData2$Outbound | undefined;
};

/** @internal */
export const UpdateServerRequestBody2$outboundSchema: z.ZodType<
  UpdateServerRequestBody2$Outbound,
  z.ZodTypeDef,
  UpdateServerRequestBody2
> = z.object({
  data: z.lazy(() => UpdateServerData2$outboundSchema).optional(),
});

export function updateServerRequestBody2ToJSON(
  updateServerRequestBody2: UpdateServerRequestBody2,
): string {
  return JSON.stringify(
    UpdateServerRequestBody2$outboundSchema.parse(updateServerRequestBody2),
  );
}
export function updateServerRequestBody2FromJSON(
  jsonString: string,
): SafeParseResult<UpdateServerRequestBody2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateServerRequestBody2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateServerRequestBody2' from JSON`,
  );
}

/** @internal */
export const UpdateServerRequest$inboundSchema: z.ZodType<
  UpdateServerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  server_id: z.string(),
  RequestBody: z.lazy(() => UpdateServerRequestBody2$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "server_id": "serverId",
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type UpdateServerRequest$Outbound = {
  server_id: string;
  RequestBody: UpdateServerRequestBody2$Outbound;
};

/** @internal */
export const UpdateServerRequest$outboundSchema: z.ZodType<
  UpdateServerRequest$Outbound,
  z.ZodTypeDef,
  UpdateServerRequest
> = z.object({
  serverId: z.string(),
  requestBody: z.lazy(() => UpdateServerRequestBody2$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    serverId: "server_id",
    requestBody: "RequestBody",
  });
});

export function updateServerRequestToJSON(
  updateServerRequest: UpdateServerRequest,
): string {
  return JSON.stringify(
    UpdateServerRequest$outboundSchema.parse(updateServerRequest),
  );
}
export function updateServerRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateServerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateServerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateServerRequest' from JSON`,
  );
}
