// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomTagMeta struct {
}

type CustomTag struct {
	Data *CustomTagData `json:"data,omitempty"`
	Meta *CustomTagMeta `json:"meta,omitempty"`
}

func (o *CustomTag) GetData() *CustomTagData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *CustomTag) GetMeta() *CustomTagMeta {
	if o == nil {
		return nil
	}
	return o.Meta
}
