// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ProjectIncludeBilling struct {
	SubscriptionID *string `json:"subscription_id,omitempty"`
	Type           *string `json:"type,omitempty"`
	Method         *string `json:"method,omitempty"`
}

func (o *ProjectIncludeBilling) GetSubscriptionID() *string {
	if o == nil {
		return nil
	}
	return o.SubscriptionID
}

func (o *ProjectIncludeBilling) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *ProjectIncludeBilling) GetMethod() *string {
	if o == nil {
		return nil
	}
	return o.Method
}

type ProjectIncludeStats struct {
	IPAddresses *int64 `json:"ip_addresses,omitempty"`
	Prefixes    *int64 `json:"prefixes,omitempty"`
	Servers     *int64 `json:"servers,omitempty"`
	Vlans       *int64 `json:"vlans,omitempty"`
}

func (o *ProjectIncludeStats) GetIPAddresses() *int64 {
	if o == nil {
		return nil
	}
	return o.IPAddresses
}

func (o *ProjectIncludeStats) GetPrefixes() *int64 {
	if o == nil {
		return nil
	}
	return o.Prefixes
}

func (o *ProjectIncludeStats) GetServers() *int64 {
	if o == nil {
		return nil
	}
	return o.Servers
}

func (o *ProjectIncludeStats) GetVlans() *int64 {
	if o == nil {
		return nil
	}
	return o.Vlans
}

type ProjectInclude struct {
	ID               *string                `json:"id,omitempty"`
	Name             *string                `json:"name,omitempty"`
	Slug             *string                `json:"slug,omitempty"`
	Description      *string                `json:"description,omitempty"`
	BillingType      *string                `json:"billing_type,omitempty"`
	ProvisioningType *string                `json:"provisioning_type,omitempty"`
	BillingMethod    *string                `json:"billing_method,omitempty"`
	BandwidthAlert   *bool                  `json:"bandwidth_alert,omitempty"`
	Environment      *string                `json:"environment,omitempty"`
	Billing          *ProjectIncludeBilling `json:"billing,omitempty"`
	Stats            *ProjectIncludeStats   `json:"stats,omitempty"`
}

func (o *ProjectInclude) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *ProjectInclude) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ProjectInclude) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *ProjectInclude) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ProjectInclude) GetBillingType() *string {
	if o == nil {
		return nil
	}
	return o.BillingType
}

func (o *ProjectInclude) GetProvisioningType() *string {
	if o == nil {
		return nil
	}
	return o.ProvisioningType
}

func (o *ProjectInclude) GetBillingMethod() *string {
	if o == nil {
		return nil
	}
	return o.BillingMethod
}

func (o *ProjectInclude) GetBandwidthAlert() *bool {
	if o == nil {
		return nil
	}
	return o.BandwidthAlert
}

func (o *ProjectInclude) GetEnvironment() *string {
	if o == nil {
		return nil
	}
	return o.Environment
}

func (o *ProjectInclude) GetBilling() *ProjectIncludeBilling {
	if o == nil {
		return nil
	}
	return o.Billing
}

func (o *ProjectInclude) GetStats() *ProjectIncludeStats {
	if o == nil {
		return nil
	}
	return o.Stats
}
