// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type UpdateAPIKeyType string

const (
	UpdateAPIKeyTypeAPIKeys UpdateAPIKeyType = "api_keys"
)

func (e UpdateAPIKeyType) ToPointer() *UpdateAPIKeyType {
	return &e
}
func (e *UpdateAPIKeyType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "api_keys":
		*e = UpdateAPIKeyType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateAPIKeyType: %v", v)
	}
}

type UpdateAPIKeyAttributes struct {
	// Name of the API Key
	Name *string `json:"name,omitempty"`
	// Whether the API Key is read-only. Read-only keys can only perform GET requests.
	ReadOnly *bool `json:"read_only,omitempty"`
	// List of allowed IP addresses or CIDR ranges (e.g., "192.168.1.100", "10.0.0.0/24")
	AllowedIps []string `json:"allowed_ips,omitempty"`
}

func (o *UpdateAPIKeyAttributes) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateAPIKeyAttributes) GetReadOnly() *bool {
	if o == nil {
		return nil
	}
	return o.ReadOnly
}

func (o *UpdateAPIKeyAttributes) GetAllowedIps() []string {
	if o == nil {
		return nil
	}
	return o.AllowedIps
}

type UpdateAPIKeyData struct {
	ID         *string                 `json:"id,omitempty"`
	Type       UpdateAPIKeyType        `json:"type"`
	Attributes *UpdateAPIKeyAttributes `json:"attributes,omitempty"`
}

func (o *UpdateAPIKeyData) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UpdateAPIKeyData) GetType() UpdateAPIKeyType {
	if o == nil {
		return UpdateAPIKeyType("")
	}
	return o.Type
}

func (o *UpdateAPIKeyData) GetAttributes() *UpdateAPIKeyAttributes {
	if o == nil {
		return nil
	}
	return o.Attributes
}

type UpdateAPIKey struct {
	Data *UpdateAPIKeyData `json:"data,omitempty"`
}

func (o *UpdateAPIKey) GetData() *UpdateAPIKeyData {
	if o == nil {
		return nil
	}
	return o.Data
}
