/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  BaselineDiskLayoutGroup,
  BaselineDiskLayoutGroup$inboundSchema,
  BaselineDiskLayoutGroup$Outbound,
  BaselineDiskLayoutGroup$outboundSchema,
} from "./baselinedisklayoutgroup.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const BaselineDataType = {
  Baselines: "baselines",
} as const;
export type BaselineDataType = ClosedEnum<typeof BaselineDataType>;

/**
 * The plan this baseline applies to
 */
export type BaselineDataPlan = {
  id?: string | undefined;
  slug?: string | undefined;
  name?: string | undefined;
};

export type BaselineDataSshKey = {
  id?: string | undefined;
  name?: string | undefined;
  fingerprint?: string | undefined;
};

/**
 * User data the baseline expects to run on first boot
 */
export type BaselineDataUserData = {
  id?: string | undefined;
  description?: string | null | undefined;
};

/**
 * Expected BIOS settings, keyed by setting id
 */
export type Bios = {};

export type BaselineDataAttributes = {
  /**
   * Name of the baseline
   */
  name?: string | undefined;
  /**
   * Description of the baseline
   */
  description?: string | null | undefined;
  /**
   * The plan this baseline applies to
   */
  plan?: BaselineDataPlan | null | undefined;
  /**
   * SSH keys the baseline expects on the server
   */
  sshKeys?: Array<BaselineDataSshKey> | undefined;
  /**
   * User data the baseline expects to run on first boot
   */
  userData?: BaselineDataUserData | null | undefined;
  /**
   * Expected disk layout
   */
  diskLayout?: Array<BaselineDiskLayoutGroup> | undefined;
  /**
   * Expected BIOS settings, keyed by setting id
   */
  bios?: Bios | undefined;
  /**
   * Date the baseline was created
   */
  createdAt?: string | null | undefined;
};

export type BaselineData = {
  id?: string | undefined;
  type?: BaselineDataType | undefined;
  attributes?: BaselineDataAttributes | undefined;
};

/** @internal */
export const BaselineDataType$inboundSchema: z.ZodNativeEnum<
  typeof BaselineDataType
> = z.nativeEnum(BaselineDataType);
/** @internal */
export const BaselineDataType$outboundSchema: z.ZodNativeEnum<
  typeof BaselineDataType
> = BaselineDataType$inboundSchema;

/** @internal */
export const BaselineDataPlan$inboundSchema: z.ZodType<
  BaselineDataPlan,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  slug: z.string().optional(),
  name: z.string().optional(),
});
/** @internal */
export type BaselineDataPlan$Outbound = {
  id?: string | undefined;
  slug?: string | undefined;
  name?: string | undefined;
};

/** @internal */
export const BaselineDataPlan$outboundSchema: z.ZodType<
  BaselineDataPlan$Outbound,
  z.ZodTypeDef,
  BaselineDataPlan
> = z.object({
  id: z.string().optional(),
  slug: z.string().optional(),
  name: z.string().optional(),
});

export function baselineDataPlanToJSON(
  baselineDataPlan: BaselineDataPlan,
): string {
  return JSON.stringify(
    BaselineDataPlan$outboundSchema.parse(baselineDataPlan),
  );
}
export function baselineDataPlanFromJSON(
  jsonString: string,
): SafeParseResult<BaselineDataPlan, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaselineDataPlan$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaselineDataPlan' from JSON`,
  );
}

/** @internal */
export const BaselineDataSshKey$inboundSchema: z.ZodType<
  BaselineDataSshKey,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  fingerprint: z.string().optional(),
});
/** @internal */
export type BaselineDataSshKey$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  fingerprint?: string | undefined;
};

/** @internal */
export const BaselineDataSshKey$outboundSchema: z.ZodType<
  BaselineDataSshKey$Outbound,
  z.ZodTypeDef,
  BaselineDataSshKey
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  fingerprint: z.string().optional(),
});

export function baselineDataSshKeyToJSON(
  baselineDataSshKey: BaselineDataSshKey,
): string {
  return JSON.stringify(
    BaselineDataSshKey$outboundSchema.parse(baselineDataSshKey),
  );
}
export function baselineDataSshKeyFromJSON(
  jsonString: string,
): SafeParseResult<BaselineDataSshKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaselineDataSshKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaselineDataSshKey' from JSON`,
  );
}

/** @internal */
export const BaselineDataUserData$inboundSchema: z.ZodType<
  BaselineDataUserData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  description: z.nullable(z.string()).optional(),
});
/** @internal */
export type BaselineDataUserData$Outbound = {
  id?: string | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const BaselineDataUserData$outboundSchema: z.ZodType<
  BaselineDataUserData$Outbound,
  z.ZodTypeDef,
  BaselineDataUserData
> = z.object({
  id: z.string().optional(),
  description: z.nullable(z.string()).optional(),
});

export function baselineDataUserDataToJSON(
  baselineDataUserData: BaselineDataUserData,
): string {
  return JSON.stringify(
    BaselineDataUserData$outboundSchema.parse(baselineDataUserData),
  );
}
export function baselineDataUserDataFromJSON(
  jsonString: string,
): SafeParseResult<BaselineDataUserData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaselineDataUserData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaselineDataUserData' from JSON`,
  );
}

/** @internal */
export const Bios$inboundSchema: z.ZodType<Bios, z.ZodTypeDef, unknown> = z
  .object({});
/** @internal */
export type Bios$Outbound = {};

/** @internal */
export const Bios$outboundSchema: z.ZodType<Bios$Outbound, z.ZodTypeDef, Bios> =
  z.object({});

export function biosToJSON(bios: Bios): string {
  return JSON.stringify(Bios$outboundSchema.parse(bios));
}
export function biosFromJSON(
  jsonString: string,
): SafeParseResult<Bios, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Bios$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Bios' from JSON`,
  );
}

/** @internal */
export const BaselineDataAttributes$inboundSchema: z.ZodType<
  BaselineDataAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  plan: z.nullable(z.lazy(() => BaselineDataPlan$inboundSchema)).optional(),
  ssh_keys: z.array(z.lazy(() => BaselineDataSshKey$inboundSchema)).optional(),
  user_data: z.nullable(z.lazy(() => BaselineDataUserData$inboundSchema))
    .optional(),
  disk_layout: z.array(BaselineDiskLayoutGroup$inboundSchema).optional(),
  bios: z.lazy(() => Bios$inboundSchema).optional(),
  created_at: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "ssh_keys": "sshKeys",
    "user_data": "userData",
    "disk_layout": "diskLayout",
    "created_at": "createdAt",
  });
});
/** @internal */
export type BaselineDataAttributes$Outbound = {
  name?: string | undefined;
  description?: string | null | undefined;
  plan?: BaselineDataPlan$Outbound | null | undefined;
  ssh_keys?: Array<BaselineDataSshKey$Outbound> | undefined;
  user_data?: BaselineDataUserData$Outbound | null | undefined;
  disk_layout?: Array<BaselineDiskLayoutGroup$Outbound> | undefined;
  bios?: Bios$Outbound | undefined;
  created_at?: string | null | undefined;
};

/** @internal */
export const BaselineDataAttributes$outboundSchema: z.ZodType<
  BaselineDataAttributes$Outbound,
  z.ZodTypeDef,
  BaselineDataAttributes
> = z.object({
  name: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  plan: z.nullable(z.lazy(() => BaselineDataPlan$outboundSchema)).optional(),
  sshKeys: z.array(z.lazy(() => BaselineDataSshKey$outboundSchema)).optional(),
  userData: z.nullable(z.lazy(() => BaselineDataUserData$outboundSchema))
    .optional(),
  diskLayout: z.array(BaselineDiskLayoutGroup$outboundSchema).optional(),
  bios: z.lazy(() => Bios$outboundSchema).optional(),
  createdAt: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    sshKeys: "ssh_keys",
    userData: "user_data",
    diskLayout: "disk_layout",
    createdAt: "created_at",
  });
});

export function baselineDataAttributesToJSON(
  baselineDataAttributes: BaselineDataAttributes,
): string {
  return JSON.stringify(
    BaselineDataAttributes$outboundSchema.parse(baselineDataAttributes),
  );
}
export function baselineDataAttributesFromJSON(
  jsonString: string,
): SafeParseResult<BaselineDataAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaselineDataAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaselineDataAttributes' from JSON`,
  );
}

/** @internal */
export const BaselineData$inboundSchema: z.ZodType<
  BaselineData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  type: BaselineDataType$inboundSchema.optional(),
  attributes: z.lazy(() => BaselineDataAttributes$inboundSchema).optional(),
});
/** @internal */
export type BaselineData$Outbound = {
  id?: string | undefined;
  type?: string | undefined;
  attributes?: BaselineDataAttributes$Outbound | undefined;
};

/** @internal */
export const BaselineData$outboundSchema: z.ZodType<
  BaselineData$Outbound,
  z.ZodTypeDef,
  BaselineData
> = z.object({
  id: z.string().optional(),
  type: BaselineDataType$outboundSchema.optional(),
  attributes: z.lazy(() => BaselineDataAttributes$outboundSchema).optional(),
});

export function baselineDataToJSON(baselineData: BaselineData): string {
  return JSON.stringify(BaselineData$outboundSchema.parse(baselineData));
}
export function baselineDataFromJSON(
  jsonString: string,
): SafeParseResult<BaselineData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaselineData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaselineData' from JSON`,
  );
}
