/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * The project in which the returned usage belongs to
 */
export type BillingUsageProject = {
  id?: string | undefined;
  slug?: string | undefined;
  name?: string | undefined;
};

/**
 * The period from the returned billing cycle
 */
export type Period = {
  start?: Date | undefined;
  end?: Date | undefined;
};

/**
 * Type of discount (percentage or fixed amount)
 */
export const BillingUsageType = {
  Percent: "percent",
  Amount: "amount",
} as const;
/**
 * Type of discount (percentage or fixed amount)
 */
export type BillingUsageType = ClosedEnum<typeof BillingUsageType>;

export type Discount = {
  /**
   * Description of the discount
   */
  description: string;
  /**
   * Type of discount (percentage or fixed amount)
   */
  type: BillingUsageType;
  /**
   * Value of the discount (percentage or amount)
   */
  value: number;
};

export const BillingUsageUnit = {
  Quantity: "quantity",
  Hour: "hour",
  Minute: "minute",
} as const;
export type BillingUsageUnit = ClosedEnum<typeof BillingUsageUnit>;

export const UsageType = {
  Licensed: "licensed",
  Metered: "metered",
} as const;
export type UsageType = ClosedEnum<typeof UsageType>;

export type Metadata = {
  id?: string | undefined;
  hostname?: string | undefined;
  plan?: string | undefined;
  tags?: Array<string> | undefined;
};

export type Product = {
  id?: string | undefined;
  resource?: string | undefined;
  name?: string | undefined;
  proration?: boolean | undefined;
  discounts?: Array<Discount> | undefined;
  discountable?: boolean | undefined;
  description?: string | undefined;
  amountWithoutDiscount?: number | undefined;
  start?: Date | undefined;
  end?: Date | undefined;
  unit?: BillingUsageUnit | undefined;
  /**
   * The unit price of the product in cents
   */
  unitPrice?: number | undefined;
  usageType?: UsageType | undefined;
  quantity?: number | undefined;
  /**
   * The total usage price of the product in cents
   */
  price?: number | undefined;
  metadata?: Metadata | undefined;
};

export type BillingUsageAttributes = {
  /**
   * The project in which the returned usage belongs to
   */
  project?: BillingUsageProject | undefined;
  /**
   * The period from the returned billing cycle
   */
  period?: Period | undefined;
  /**
   * The available credit balance in cents
   */
  availableCreditBalance?: number | undefined;
  /**
   * The total usage price in cents
   */
  price?: number | undefined;
  /**
   * The threshold which we use to charge your usage, in cents
   */
  threshold?: number | null | undefined;
  products?: Array<Product> | undefined;
};

export type BillingUsageData = {
  id?: string | undefined;
  attributes?: BillingUsageAttributes | undefined;
};

export type BillingUsage = {
  data?: BillingUsageData | undefined;
};

/** @internal */
export const BillingUsageProject$inboundSchema: z.ZodType<
  BillingUsageProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  slug: z.string().optional(),
  name: z.string().optional(),
});
/** @internal */
export type BillingUsageProject$Outbound = {
  id?: string | undefined;
  slug?: string | undefined;
  name?: string | undefined;
};

/** @internal */
export const BillingUsageProject$outboundSchema: z.ZodType<
  BillingUsageProject$Outbound,
  z.ZodTypeDef,
  BillingUsageProject
> = z.object({
  id: z.string().optional(),
  slug: z.string().optional(),
  name: z.string().optional(),
});

export function billingUsageProjectToJSON(
  billingUsageProject: BillingUsageProject,
): string {
  return JSON.stringify(
    BillingUsageProject$outboundSchema.parse(billingUsageProject),
  );
}
export function billingUsageProjectFromJSON(
  jsonString: string,
): SafeParseResult<BillingUsageProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BillingUsageProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BillingUsageProject' from JSON`,
  );
}

/** @internal */
export const Period$inboundSchema: z.ZodType<Period, z.ZodTypeDef, unknown> = z
  .object({
    start: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    end: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
  });
/** @internal */
export type Period$Outbound = {
  start?: string | undefined;
  end?: string | undefined;
};

/** @internal */
export const Period$outboundSchema: z.ZodType<
  Period$Outbound,
  z.ZodTypeDef,
  Period
> = z.object({
  start: z.date().transform(v => v.toISOString()).optional(),
  end: z.date().transform(v => v.toISOString()).optional(),
});

export function periodToJSON(period: Period): string {
  return JSON.stringify(Period$outboundSchema.parse(period));
}
export function periodFromJSON(
  jsonString: string,
): SafeParseResult<Period, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Period$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Period' from JSON`,
  );
}

/** @internal */
export const BillingUsageType$inboundSchema: z.ZodNativeEnum<
  typeof BillingUsageType
> = z.nativeEnum(BillingUsageType);
/** @internal */
export const BillingUsageType$outboundSchema: z.ZodNativeEnum<
  typeof BillingUsageType
> = BillingUsageType$inboundSchema;

/** @internal */
export const Discount$inboundSchema: z.ZodType<
  Discount,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string(),
  type: BillingUsageType$inboundSchema,
  value: z.number(),
});
/** @internal */
export type Discount$Outbound = {
  description: string;
  type: string;
  value: number;
};

/** @internal */
export const Discount$outboundSchema: z.ZodType<
  Discount$Outbound,
  z.ZodTypeDef,
  Discount
> = z.object({
  description: z.string(),
  type: BillingUsageType$outboundSchema,
  value: z.number(),
});

export function discountToJSON(discount: Discount): string {
  return JSON.stringify(Discount$outboundSchema.parse(discount));
}
export function discountFromJSON(
  jsonString: string,
): SafeParseResult<Discount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Discount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Discount' from JSON`,
  );
}

/** @internal */
export const BillingUsageUnit$inboundSchema: z.ZodNativeEnum<
  typeof BillingUsageUnit
> = z.nativeEnum(BillingUsageUnit);
/** @internal */
export const BillingUsageUnit$outboundSchema: z.ZodNativeEnum<
  typeof BillingUsageUnit
> = BillingUsageUnit$inboundSchema;

/** @internal */
export const UsageType$inboundSchema: z.ZodNativeEnum<typeof UsageType> = z
  .nativeEnum(UsageType);
/** @internal */
export const UsageType$outboundSchema: z.ZodNativeEnum<typeof UsageType> =
  UsageType$inboundSchema;

/** @internal */
export const Metadata$inboundSchema: z.ZodType<
  Metadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  hostname: z.string().optional(),
  plan: z.string().optional(),
  tags: z.array(z.string()).optional(),
});
/** @internal */
export type Metadata$Outbound = {
  id?: string | undefined;
  hostname?: string | undefined;
  plan?: string | undefined;
  tags?: Array<string> | undefined;
};

/** @internal */
export const Metadata$outboundSchema: z.ZodType<
  Metadata$Outbound,
  z.ZodTypeDef,
  Metadata
> = z.object({
  id: z.string().optional(),
  hostname: z.string().optional(),
  plan: z.string().optional(),
  tags: z.array(z.string()).optional(),
});

export function metadataToJSON(metadata: Metadata): string {
  return JSON.stringify(Metadata$outboundSchema.parse(metadata));
}
export function metadataFromJSON(
  jsonString: string,
): SafeParseResult<Metadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Metadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Metadata' from JSON`,
  );
}

/** @internal */
export const Product$inboundSchema: z.ZodType<Product, z.ZodTypeDef, unknown> =
  z.object({
    id: z.string().optional(),
    resource: z.string().optional(),
    name: z.string().optional(),
    proration: z.boolean().optional(),
    discounts: z.array(z.lazy(() => Discount$inboundSchema)).optional(),
    discountable: z.boolean().optional(),
    description: z.string().optional(),
    amount_without_discount: z.number().int().optional(),
    start: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    end: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    unit: BillingUsageUnit$inboundSchema.optional(),
    unit_price: z.number().optional(),
    usage_type: UsageType$inboundSchema.optional(),
    quantity: z.number().optional(),
    price: z.number().optional(),
    metadata: z.lazy(() => Metadata$inboundSchema).optional(),
  }).transform((v) => {
    return remap$(v, {
      "amount_without_discount": "amountWithoutDiscount",
      "unit_price": "unitPrice",
      "usage_type": "usageType",
    });
  });
/** @internal */
export type Product$Outbound = {
  id?: string | undefined;
  resource?: string | undefined;
  name?: string | undefined;
  proration?: boolean | undefined;
  discounts?: Array<Discount$Outbound> | undefined;
  discountable?: boolean | undefined;
  description?: string | undefined;
  amount_without_discount?: number | undefined;
  start?: string | undefined;
  end?: string | undefined;
  unit?: string | undefined;
  unit_price?: number | undefined;
  usage_type?: string | undefined;
  quantity?: number | undefined;
  price?: number | undefined;
  metadata?: Metadata$Outbound | undefined;
};

/** @internal */
export const Product$outboundSchema: z.ZodType<
  Product$Outbound,
  z.ZodTypeDef,
  Product
> = z.object({
  id: z.string().optional(),
  resource: z.string().optional(),
  name: z.string().optional(),
  proration: z.boolean().optional(),
  discounts: z.array(z.lazy(() => Discount$outboundSchema)).optional(),
  discountable: z.boolean().optional(),
  description: z.string().optional(),
  amountWithoutDiscount: z.number().int().optional(),
  start: z.date().transform(v => v.toISOString()).optional(),
  end: z.date().transform(v => v.toISOString()).optional(),
  unit: BillingUsageUnit$outboundSchema.optional(),
  unitPrice: z.number().optional(),
  usageType: UsageType$outboundSchema.optional(),
  quantity: z.number().optional(),
  price: z.number().optional(),
  metadata: z.lazy(() => Metadata$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    amountWithoutDiscount: "amount_without_discount",
    unitPrice: "unit_price",
    usageType: "usage_type",
  });
});

export function productToJSON(product: Product): string {
  return JSON.stringify(Product$outboundSchema.parse(product));
}
export function productFromJSON(
  jsonString: string,
): SafeParseResult<Product, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Product$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Product' from JSON`,
  );
}

/** @internal */
export const BillingUsageAttributes$inboundSchema: z.ZodType<
  BillingUsageAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  project: z.lazy(() => BillingUsageProject$inboundSchema).optional(),
  period: z.lazy(() => Period$inboundSchema).optional(),
  available_credit_balance: z.number().int().optional(),
  price: z.number().optional(),
  threshold: z.nullable(z.number()).optional(),
  products: z.array(z.lazy(() => Product$inboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    "available_credit_balance": "availableCreditBalance",
  });
});
/** @internal */
export type BillingUsageAttributes$Outbound = {
  project?: BillingUsageProject$Outbound | undefined;
  period?: Period$Outbound | undefined;
  available_credit_balance?: number | undefined;
  price?: number | undefined;
  threshold?: number | null | undefined;
  products?: Array<Product$Outbound> | undefined;
};

/** @internal */
export const BillingUsageAttributes$outboundSchema: z.ZodType<
  BillingUsageAttributes$Outbound,
  z.ZodTypeDef,
  BillingUsageAttributes
> = z.object({
  project: z.lazy(() => BillingUsageProject$outboundSchema).optional(),
  period: z.lazy(() => Period$outboundSchema).optional(),
  availableCreditBalance: z.number().int().optional(),
  price: z.number().optional(),
  threshold: z.nullable(z.number()).optional(),
  products: z.array(z.lazy(() => Product$outboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    availableCreditBalance: "available_credit_balance",
  });
});

export function billingUsageAttributesToJSON(
  billingUsageAttributes: BillingUsageAttributes,
): string {
  return JSON.stringify(
    BillingUsageAttributes$outboundSchema.parse(billingUsageAttributes),
  );
}
export function billingUsageAttributesFromJSON(
  jsonString: string,
): SafeParseResult<BillingUsageAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BillingUsageAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BillingUsageAttributes' from JSON`,
  );
}

/** @internal */
export const BillingUsageData$inboundSchema: z.ZodType<
  BillingUsageData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  attributes: z.lazy(() => BillingUsageAttributes$inboundSchema).optional(),
});
/** @internal */
export type BillingUsageData$Outbound = {
  id?: string | undefined;
  attributes?: BillingUsageAttributes$Outbound | undefined;
};

/** @internal */
export const BillingUsageData$outboundSchema: z.ZodType<
  BillingUsageData$Outbound,
  z.ZodTypeDef,
  BillingUsageData
> = z.object({
  id: z.string().optional(),
  attributes: z.lazy(() => BillingUsageAttributes$outboundSchema).optional(),
});

export function billingUsageDataToJSON(
  billingUsageData: BillingUsageData,
): string {
  return JSON.stringify(
    BillingUsageData$outboundSchema.parse(billingUsageData),
  );
}
export function billingUsageDataFromJSON(
  jsonString: string,
): SafeParseResult<BillingUsageData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BillingUsageData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BillingUsageData' from JSON`,
  );
}

/** @internal */
export const BillingUsage$inboundSchema: z.ZodType<
  BillingUsage,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => BillingUsageData$inboundSchema).optional(),
});
/** @internal */
export type BillingUsage$Outbound = {
  data?: BillingUsageData$Outbound | undefined;
};

/** @internal */
export const BillingUsage$outboundSchema: z.ZodType<
  BillingUsage$Outbound,
  z.ZodTypeDef,
  BillingUsage
> = z.object({
  data: z.lazy(() => BillingUsageData$outboundSchema).optional(),
});

export function billingUsageToJSON(billingUsage: BillingUsage): string {
  return JSON.stringify(BillingUsage$outboundSchema.parse(billingUsage));
}
export function billingUsageFromJSON(
  jsonString: string,
): SafeParseResult<BillingUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BillingUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BillingUsage' from JSON`,
  );
}
