/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const CreatePublicNetworkType = {
  PublicNetworks: "public_networks",
} as const;
export type CreatePublicNetworkType = ClosedEnum<
  typeof CreatePublicNetworkType
>;

/**
 * IPv4 prefix length. Determines how many servers the public network can host.
 */
export const CreatePublicNetworkSize = {
  TwentySix: 26,
  TwentySeven: 27,
  TwentyEight: 28,
  TwentyNine: 29,
} as const;
/**
 * IPv4 prefix length. Determines how many servers the public network can host.
 */
export type CreatePublicNetworkSize = ClosedEnum<
  typeof CreatePublicNetworkSize
>;

export type CreatePublicNetworkAttributes = {
  /**
   * The project to create the public network in
   */
  projectId: string;
  /**
   * The site slug the public network is bound to
   */
  site: string;
  /**
   * IPv4 prefix length. Determines how many servers the public network can host.
   */
  size: CreatePublicNetworkSize;
};

export type CreatePublicNetworkData = {
  type: CreatePublicNetworkType;
  attributes?: CreatePublicNetworkAttributes | undefined;
};

export type CreatePublicNetwork = {
  data: CreatePublicNetworkData;
};

/** @internal */
export const CreatePublicNetworkType$inboundSchema: z.ZodNativeEnum<
  typeof CreatePublicNetworkType
> = z.nativeEnum(CreatePublicNetworkType);
/** @internal */
export const CreatePublicNetworkType$outboundSchema: z.ZodNativeEnum<
  typeof CreatePublicNetworkType
> = CreatePublicNetworkType$inboundSchema;

/** @internal */
export const CreatePublicNetworkSize$inboundSchema: z.ZodNativeEnum<
  typeof CreatePublicNetworkSize
> = z.nativeEnum(CreatePublicNetworkSize);
/** @internal */
export const CreatePublicNetworkSize$outboundSchema: z.ZodNativeEnum<
  typeof CreatePublicNetworkSize
> = CreatePublicNetworkSize$inboundSchema;

/** @internal */
export const CreatePublicNetworkAttributes$inboundSchema: z.ZodType<
  CreatePublicNetworkAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  project_id: z.string(),
  site: z.string(),
  size: CreatePublicNetworkSize$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "project_id": "projectId",
  });
});
/** @internal */
export type CreatePublicNetworkAttributes$Outbound = {
  project_id: string;
  site: string;
  size: number;
};

/** @internal */
export const CreatePublicNetworkAttributes$outboundSchema: z.ZodType<
  CreatePublicNetworkAttributes$Outbound,
  z.ZodTypeDef,
  CreatePublicNetworkAttributes
> = z.object({
  projectId: z.string(),
  site: z.string(),
  size: CreatePublicNetworkSize$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    projectId: "project_id",
  });
});

export function createPublicNetworkAttributesToJSON(
  createPublicNetworkAttributes: CreatePublicNetworkAttributes,
): string {
  return JSON.stringify(
    CreatePublicNetworkAttributes$outboundSchema.parse(
      createPublicNetworkAttributes,
    ),
  );
}
export function createPublicNetworkAttributesFromJSON(
  jsonString: string,
): SafeParseResult<CreatePublicNetworkAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePublicNetworkAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePublicNetworkAttributes' from JSON`,
  );
}

/** @internal */
export const CreatePublicNetworkData$inboundSchema: z.ZodType<
  CreatePublicNetworkData,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: CreatePublicNetworkType$inboundSchema,
  attributes: z.lazy(() => CreatePublicNetworkAttributes$inboundSchema)
    .optional(),
});
/** @internal */
export type CreatePublicNetworkData$Outbound = {
  type: string;
  attributes?: CreatePublicNetworkAttributes$Outbound | undefined;
};

/** @internal */
export const CreatePublicNetworkData$outboundSchema: z.ZodType<
  CreatePublicNetworkData$Outbound,
  z.ZodTypeDef,
  CreatePublicNetworkData
> = z.object({
  type: CreatePublicNetworkType$outboundSchema,
  attributes: z.lazy(() => CreatePublicNetworkAttributes$outboundSchema)
    .optional(),
});

export function createPublicNetworkDataToJSON(
  createPublicNetworkData: CreatePublicNetworkData,
): string {
  return JSON.stringify(
    CreatePublicNetworkData$outboundSchema.parse(createPublicNetworkData),
  );
}
export function createPublicNetworkDataFromJSON(
  jsonString: string,
): SafeParseResult<CreatePublicNetworkData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePublicNetworkData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePublicNetworkData' from JSON`,
  );
}

/** @internal */
export const CreatePublicNetwork$inboundSchema: z.ZodType<
  CreatePublicNetwork,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => CreatePublicNetworkData$inboundSchema),
});
/** @internal */
export type CreatePublicNetwork$Outbound = {
  data: CreatePublicNetworkData$Outbound;
};

/** @internal */
export const CreatePublicNetwork$outboundSchema: z.ZodType<
  CreatePublicNetwork$Outbound,
  z.ZodTypeDef,
  CreatePublicNetwork
> = z.object({
  data: z.lazy(() => CreatePublicNetworkData$outboundSchema),
});

export function createPublicNetworkToJSON(
  createPublicNetwork: CreatePublicNetwork,
): string {
  return JSON.stringify(
    CreatePublicNetwork$outboundSchema.parse(createPublicNetwork),
  );
}
export function createPublicNetworkFromJSON(
  jsonString: string,
): SafeParseResult<CreatePublicNetwork, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePublicNetwork$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePublicNetwork' from JSON`,
  );
}
