/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const CreateApiKeyType = {
  ApiKeys: "api_keys",
} as const;
export type CreateApiKeyType = ClosedEnum<typeof CreateApiKeyType>;

export type CreateApiKeyAttributes = {
  /**
   * Name of the API Key
   */
  name?: string | undefined;
  /**
   * Whether the API Key is read-only. Read-only keys can only perform GET, HEAD, and OPTIONS requests.
   */
  readOnly?: boolean | undefined;
  /**
   * List of allowed IP addresses or CIDR ranges. If set, the API key can only be used from these IP addresses.
   */
  allowedIps?: Array<string> | undefined;
};

export type CreateApiKeyData = {
  type: CreateApiKeyType;
  attributes?: CreateApiKeyAttributes | undefined;
};

export type CreateApiKey = {
  data?: CreateApiKeyData | undefined;
};

/** @internal */
export const CreateApiKeyType$inboundSchema: z.ZodNativeEnum<
  typeof CreateApiKeyType
> = z.nativeEnum(CreateApiKeyType);
/** @internal */
export const CreateApiKeyType$outboundSchema: z.ZodNativeEnum<
  typeof CreateApiKeyType
> = CreateApiKeyType$inboundSchema;

/** @internal */
export const CreateApiKeyAttributes$inboundSchema: z.ZodType<
  CreateApiKeyAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().default("Name of the API Key"),
  read_only: z.boolean().optional(),
  allowed_ips: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "read_only": "readOnly",
    "allowed_ips": "allowedIps",
  });
});
/** @internal */
export type CreateApiKeyAttributes$Outbound = {
  name: string;
  read_only?: boolean | undefined;
  allowed_ips?: Array<string> | undefined;
};

/** @internal */
export const CreateApiKeyAttributes$outboundSchema: z.ZodType<
  CreateApiKeyAttributes$Outbound,
  z.ZodTypeDef,
  CreateApiKeyAttributes
> = z.object({
  name: z.string().default("Name of the API Key"),
  readOnly: z.boolean().optional(),
  allowedIps: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    readOnly: "read_only",
    allowedIps: "allowed_ips",
  });
});

export function createApiKeyAttributesToJSON(
  createApiKeyAttributes: CreateApiKeyAttributes,
): string {
  return JSON.stringify(
    CreateApiKeyAttributes$outboundSchema.parse(createApiKeyAttributes),
  );
}
export function createApiKeyAttributesFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiKeyAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiKeyAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiKeyAttributes' from JSON`,
  );
}

/** @internal */
export const CreateApiKeyData$inboundSchema: z.ZodType<
  CreateApiKeyData,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: CreateApiKeyType$inboundSchema,
  attributes: z.lazy(() => CreateApiKeyAttributes$inboundSchema).optional(),
});
/** @internal */
export type CreateApiKeyData$Outbound = {
  type: string;
  attributes?: CreateApiKeyAttributes$Outbound | undefined;
};

/** @internal */
export const CreateApiKeyData$outboundSchema: z.ZodType<
  CreateApiKeyData$Outbound,
  z.ZodTypeDef,
  CreateApiKeyData
> = z.object({
  type: CreateApiKeyType$outboundSchema,
  attributes: z.lazy(() => CreateApiKeyAttributes$outboundSchema).optional(),
});

export function createApiKeyDataToJSON(
  createApiKeyData: CreateApiKeyData,
): string {
  return JSON.stringify(
    CreateApiKeyData$outboundSchema.parse(createApiKeyData),
  );
}
export function createApiKeyDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiKeyData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiKeyData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiKeyData' from JSON`,
  );
}

/** @internal */
export const CreateApiKey$inboundSchema: z.ZodType<
  CreateApiKey,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => CreateApiKeyData$inboundSchema).optional(),
});
/** @internal */
export type CreateApiKey$Outbound = {
  data?: CreateApiKeyData$Outbound | undefined;
};

/** @internal */
export const CreateApiKey$outboundSchema: z.ZodType<
  CreateApiKey$Outbound,
  z.ZodTypeDef,
  CreateApiKey
> = z.object({
  data: z.lazy(() => CreateApiKeyData$outboundSchema).optional(),
});

export function createApiKeyToJSON(createApiKey: CreateApiKey): string {
  return JSON.stringify(CreateApiKey$outboundSchema.parse(createApiKey));
}
export function createApiKeyFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiKey' from JSON`,
  );
}
