/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const CreateElasticIpType = {
  ElasticIps: "elastic_ips",
} as const;
export type CreateElasticIpType = ClosedEnum<typeof CreateElasticIpType>;

/**
 * How the elastic IP is delivered. Defaults to routed
 */
export const CreateElasticIpMode = {
  Routed: "routed",
  Bgp: "bgp",
} as const;
/**
 * How the elastic IP is delivered. Defaults to routed
 */
export type CreateElasticIpMode = ClosedEnum<typeof CreateElasticIpMode>;

export type CreateElasticIpAttributes = {
  /**
   * How the elastic IP is delivered. Defaults to routed
   */
  mode?: CreateElasticIpMode | undefined;
  /**
   * The server to assign the elastic IP to. Required in routed mode and rejected in bgp mode, which uses server_ids
   */
  serverId?: string | undefined;
  /**
   * The project to create the elastic IP in
   */
  projectId: string;
  /**
   * The servers that announce the elastic IP over BGP. Only used in bgp mode, where it may be omitted to allocate a VIP with no sessions
   */
  serverIds?: Array<string> | undefined;
  /**
   * The site slug to allocate the elastic IP in. Only used in bgp mode, where it is required when no server_ids are given
   */
  site?: string | undefined;
};

export type CreateElasticIpData = {
  type: CreateElasticIpType;
  attributes?: CreateElasticIpAttributes | undefined;
};

export type CreateElasticIp = {
  data: CreateElasticIpData;
};

/** @internal */
export const CreateElasticIpType$inboundSchema: z.ZodNativeEnum<
  typeof CreateElasticIpType
> = z.nativeEnum(CreateElasticIpType);
/** @internal */
export const CreateElasticIpType$outboundSchema: z.ZodNativeEnum<
  typeof CreateElasticIpType
> = CreateElasticIpType$inboundSchema;

/** @internal */
export const CreateElasticIpMode$inboundSchema: z.ZodNativeEnum<
  typeof CreateElasticIpMode
> = z.nativeEnum(CreateElasticIpMode);
/** @internal */
export const CreateElasticIpMode$outboundSchema: z.ZodNativeEnum<
  typeof CreateElasticIpMode
> = CreateElasticIpMode$inboundSchema;

/** @internal */
export const CreateElasticIpAttributes$inboundSchema: z.ZodType<
  CreateElasticIpAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  mode: CreateElasticIpMode$inboundSchema.default("routed"),
  server_id: z.string().optional(),
  project_id: z.string(),
  server_ids: z.array(z.string()).optional(),
  site: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "server_id": "serverId",
    "project_id": "projectId",
    "server_ids": "serverIds",
  });
});
/** @internal */
export type CreateElasticIpAttributes$Outbound = {
  mode: string;
  server_id?: string | undefined;
  project_id: string;
  server_ids?: Array<string> | undefined;
  site?: string | undefined;
};

/** @internal */
export const CreateElasticIpAttributes$outboundSchema: z.ZodType<
  CreateElasticIpAttributes$Outbound,
  z.ZodTypeDef,
  CreateElasticIpAttributes
> = z.object({
  mode: CreateElasticIpMode$outboundSchema.default("routed"),
  serverId: z.string().optional(),
  projectId: z.string(),
  serverIds: z.array(z.string()).optional(),
  site: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    serverId: "server_id",
    projectId: "project_id",
    serverIds: "server_ids",
  });
});

export function createElasticIpAttributesToJSON(
  createElasticIpAttributes: CreateElasticIpAttributes,
): string {
  return JSON.stringify(
    CreateElasticIpAttributes$outboundSchema.parse(createElasticIpAttributes),
  );
}
export function createElasticIpAttributesFromJSON(
  jsonString: string,
): SafeParseResult<CreateElasticIpAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateElasticIpAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateElasticIpAttributes' from JSON`,
  );
}

/** @internal */
export const CreateElasticIpData$inboundSchema: z.ZodType<
  CreateElasticIpData,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: CreateElasticIpType$inboundSchema,
  attributes: z.lazy(() => CreateElasticIpAttributes$inboundSchema).optional(),
});
/** @internal */
export type CreateElasticIpData$Outbound = {
  type: string;
  attributes?: CreateElasticIpAttributes$Outbound | undefined;
};

/** @internal */
export const CreateElasticIpData$outboundSchema: z.ZodType<
  CreateElasticIpData$Outbound,
  z.ZodTypeDef,
  CreateElasticIpData
> = z.object({
  type: CreateElasticIpType$outboundSchema,
  attributes: z.lazy(() => CreateElasticIpAttributes$outboundSchema).optional(),
});

export function createElasticIpDataToJSON(
  createElasticIpData: CreateElasticIpData,
): string {
  return JSON.stringify(
    CreateElasticIpData$outboundSchema.parse(createElasticIpData),
  );
}
export function createElasticIpDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateElasticIpData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateElasticIpData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateElasticIpData' from JSON`,
  );
}

/** @internal */
export const CreateElasticIp$inboundSchema: z.ZodType<
  CreateElasticIp,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => CreateElasticIpData$inboundSchema),
});
/** @internal */
export type CreateElasticIp$Outbound = {
  data: CreateElasticIpData$Outbound;
};

/** @internal */
export const CreateElasticIp$outboundSchema: z.ZodType<
  CreateElasticIp$Outbound,
  z.ZodTypeDef,
  CreateElasticIp
> = z.object({
  data: z.lazy(() => CreateElasticIpData$outboundSchema),
});

export function createElasticIpToJSON(
  createElasticIp: CreateElasticIp,
): string {
  return JSON.stringify(CreateElasticIp$outboundSchema.parse(createElasticIp));
}
export function createElasticIpFromJSON(
  jsonString: string,
): SafeParseResult<CreateElasticIp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateElasticIp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateElasticIp' from JSON`,
  );
}
