/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ElasticIpData,
  ElasticIpData$inboundSchema,
  ElasticIpData$Outbound,
  ElasticIpData$outboundSchema,
} from "./elasticipdata.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ElasticIpMeta = {};

export type ElasticIp = {
  data?: ElasticIpData | undefined;
  meta?: ElasticIpMeta | undefined;
};

/** @internal */
export const ElasticIpMeta$inboundSchema: z.ZodType<
  ElasticIpMeta,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type ElasticIpMeta$Outbound = {};

/** @internal */
export const ElasticIpMeta$outboundSchema: z.ZodType<
  ElasticIpMeta$Outbound,
  z.ZodTypeDef,
  ElasticIpMeta
> = z.object({});

export function elasticIpMetaToJSON(elasticIpMeta: ElasticIpMeta): string {
  return JSON.stringify(ElasticIpMeta$outboundSchema.parse(elasticIpMeta));
}
export function elasticIpMetaFromJSON(
  jsonString: string,
): SafeParseResult<ElasticIpMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ElasticIpMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ElasticIpMeta' from JSON`,
  );
}

/** @internal */
export const ElasticIp$inboundSchema: z.ZodType<
  ElasticIp,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: ElasticIpData$inboundSchema.optional(),
  meta: z.lazy(() => ElasticIpMeta$inboundSchema).optional(),
});
/** @internal */
export type ElasticIp$Outbound = {
  data?: ElasticIpData$Outbound | undefined;
  meta?: ElasticIpMeta$Outbound | undefined;
};

/** @internal */
export const ElasticIp$outboundSchema: z.ZodType<
  ElasticIp$Outbound,
  z.ZodTypeDef,
  ElasticIp
> = z.object({
  data: ElasticIpData$outboundSchema.optional(),
  meta: z.lazy(() => ElasticIpMeta$outboundSchema).optional(),
});

export function elasticIpToJSON(elasticIp: ElasticIp): string {
  return JSON.stringify(ElasticIp$outboundSchema.parse(elasticIp));
}
export function elasticIpFromJSON(
  jsonString: string,
): SafeParseResult<ElasticIp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ElasticIp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ElasticIp' from JSON`,
  );
}
