/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ElasticIpDataType = {
  ElasticIps: "elastic_ips",
} as const;
export type ElasticIpDataType = ClosedEnum<typeof ElasticIpDataType>;

/**
 * The IP address family
 */
export const ElasticIpDataFamily = {
  IPv4: "IPv4",
} as const;
/**
 * The IP address family
 */
export type ElasticIpDataFamily = ClosedEnum<typeof ElasticIpDataFamily>;

/**
 * The routing mode for this Elastic IP
 */
export const Mode = {
  Routed: "routed",
} as const;
/**
 * The routing mode for this Elastic IP
 */
export type Mode = ClosedEnum<typeof Mode>;

/**
 * The current status of the Elastic IP
 */
export const ElasticIpDataStatus = {
  Provisioning: "provisioning",
  Active: "active",
  Releasing: "releasing",
  Error: "error",
} as const;
/**
 * The current status of the Elastic IP
 */
export type ElasticIpDataStatus = ClosedEnum<typeof ElasticIpDataStatus>;

/**
 * The server this Elastic IP is assigned to
 */
export type ElasticIpDataServer = {
  id?: string | undefined;
  hostname?: string | undefined;
  primaryIpv4?: string | undefined;
};

/**
 * The project this Elastic IP belongs to
 */
export type ElasticIpDataProject = {
  id?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
};

export type ElasticIpDataSite = {
  slug?: string | undefined;
};

/**
 * The region where this Elastic IP is located
 */
export type ElasticIpDataRegion = {
  city?: string | undefined;
  site?: ElasticIpDataSite | undefined;
};

export type ElasticIpDataAttributes = {
  /**
   * The IP address
   */
  address?: string | undefined;
  /**
   * The IP address family
   */
  family?: ElasticIpDataFamily | undefined;
  /**
   * The prefix length (e.g., 32 for a single IP)
   */
  prefixLength?: number | undefined;
  /**
   * The routing mode for this Elastic IP
   */
  mode?: Mode | undefined;
  /**
   * The current status of the Elastic IP
   */
  status?: ElasticIpDataStatus | undefined;
  /**
   * The timestamp when the Elastic IP was created
   */
  createdAt?: Date | undefined;
  /**
   * The server this Elastic IP is assigned to
   */
  server?: ElasticIpDataServer | null | undefined;
  /**
   * The project this Elastic IP belongs to
   */
  project?: ElasticIpDataProject | undefined;
  /**
   * The region where this Elastic IP is located
   */
  region?: ElasticIpDataRegion | null | undefined;
};

export type ElasticIpData = {
  /**
   * The Elastic IP ID. May be null during initial provisioning.
   */
  id?: string | null | undefined;
  type?: ElasticIpDataType | undefined;
  attributes?: ElasticIpDataAttributes | undefined;
};

/** @internal */
export const ElasticIpDataType$inboundSchema: z.ZodNativeEnum<
  typeof ElasticIpDataType
> = z.nativeEnum(ElasticIpDataType);
/** @internal */
export const ElasticIpDataType$outboundSchema: z.ZodNativeEnum<
  typeof ElasticIpDataType
> = ElasticIpDataType$inboundSchema;

/** @internal */
export const ElasticIpDataFamily$inboundSchema: z.ZodNativeEnum<
  typeof ElasticIpDataFamily
> = z.nativeEnum(ElasticIpDataFamily);
/** @internal */
export const ElasticIpDataFamily$outboundSchema: z.ZodNativeEnum<
  typeof ElasticIpDataFamily
> = ElasticIpDataFamily$inboundSchema;

/** @internal */
export const Mode$inboundSchema: z.ZodNativeEnum<typeof Mode> = z.nativeEnum(
  Mode,
);
/** @internal */
export const Mode$outboundSchema: z.ZodNativeEnum<typeof Mode> =
  Mode$inboundSchema;

/** @internal */
export const ElasticIpDataStatus$inboundSchema: z.ZodNativeEnum<
  typeof ElasticIpDataStatus
> = z.nativeEnum(ElasticIpDataStatus);
/** @internal */
export const ElasticIpDataStatus$outboundSchema: z.ZodNativeEnum<
  typeof ElasticIpDataStatus
> = ElasticIpDataStatus$inboundSchema;

/** @internal */
export const ElasticIpDataServer$inboundSchema: z.ZodType<
  ElasticIpDataServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  hostname: z.string().optional(),
  primary_ipv4: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "primary_ipv4": "primaryIpv4",
  });
});
/** @internal */
export type ElasticIpDataServer$Outbound = {
  id?: string | undefined;
  hostname?: string | undefined;
  primary_ipv4?: string | undefined;
};

/** @internal */
export const ElasticIpDataServer$outboundSchema: z.ZodType<
  ElasticIpDataServer$Outbound,
  z.ZodTypeDef,
  ElasticIpDataServer
> = z.object({
  id: z.string().optional(),
  hostname: z.string().optional(),
  primaryIpv4: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    primaryIpv4: "primary_ipv4",
  });
});

export function elasticIpDataServerToJSON(
  elasticIpDataServer: ElasticIpDataServer,
): string {
  return JSON.stringify(
    ElasticIpDataServer$outboundSchema.parse(elasticIpDataServer),
  );
}
export function elasticIpDataServerFromJSON(
  jsonString: string,
): SafeParseResult<ElasticIpDataServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ElasticIpDataServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ElasticIpDataServer' from JSON`,
  );
}

/** @internal */
export const ElasticIpDataProject$inboundSchema: z.ZodType<
  ElasticIpDataProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
});
/** @internal */
export type ElasticIpDataProject$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
};

/** @internal */
export const ElasticIpDataProject$outboundSchema: z.ZodType<
  ElasticIpDataProject$Outbound,
  z.ZodTypeDef,
  ElasticIpDataProject
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
});

export function elasticIpDataProjectToJSON(
  elasticIpDataProject: ElasticIpDataProject,
): string {
  return JSON.stringify(
    ElasticIpDataProject$outboundSchema.parse(elasticIpDataProject),
  );
}
export function elasticIpDataProjectFromJSON(
  jsonString: string,
): SafeParseResult<ElasticIpDataProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ElasticIpDataProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ElasticIpDataProject' from JSON`,
  );
}

/** @internal */
export const ElasticIpDataSite$inboundSchema: z.ZodType<
  ElasticIpDataSite,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string().optional(),
});
/** @internal */
export type ElasticIpDataSite$Outbound = {
  slug?: string | undefined;
};

/** @internal */
export const ElasticIpDataSite$outboundSchema: z.ZodType<
  ElasticIpDataSite$Outbound,
  z.ZodTypeDef,
  ElasticIpDataSite
> = z.object({
  slug: z.string().optional(),
});

export function elasticIpDataSiteToJSON(
  elasticIpDataSite: ElasticIpDataSite,
): string {
  return JSON.stringify(
    ElasticIpDataSite$outboundSchema.parse(elasticIpDataSite),
  );
}
export function elasticIpDataSiteFromJSON(
  jsonString: string,
): SafeParseResult<ElasticIpDataSite, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ElasticIpDataSite$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ElasticIpDataSite' from JSON`,
  );
}

/** @internal */
export const ElasticIpDataRegion$inboundSchema: z.ZodType<
  ElasticIpDataRegion,
  z.ZodTypeDef,
  unknown
> = z.object({
  city: z.string().optional(),
  site: z.lazy(() => ElasticIpDataSite$inboundSchema).optional(),
});
/** @internal */
export type ElasticIpDataRegion$Outbound = {
  city?: string | undefined;
  site?: ElasticIpDataSite$Outbound | undefined;
};

/** @internal */
export const ElasticIpDataRegion$outboundSchema: z.ZodType<
  ElasticIpDataRegion$Outbound,
  z.ZodTypeDef,
  ElasticIpDataRegion
> = z.object({
  city: z.string().optional(),
  site: z.lazy(() => ElasticIpDataSite$outboundSchema).optional(),
});

export function elasticIpDataRegionToJSON(
  elasticIpDataRegion: ElasticIpDataRegion,
): string {
  return JSON.stringify(
    ElasticIpDataRegion$outboundSchema.parse(elasticIpDataRegion),
  );
}
export function elasticIpDataRegionFromJSON(
  jsonString: string,
): SafeParseResult<ElasticIpDataRegion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ElasticIpDataRegion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ElasticIpDataRegion' from JSON`,
  );
}

/** @internal */
export const ElasticIpDataAttributes$inboundSchema: z.ZodType<
  ElasticIpDataAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: z.string().optional(),
  family: ElasticIpDataFamily$inboundSchema.optional(),
  prefix_length: z.number().int().optional(),
  mode: Mode$inboundSchema.optional(),
  status: ElasticIpDataStatus$inboundSchema.optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  server: z.nullable(z.lazy(() => ElasticIpDataServer$inboundSchema))
    .optional(),
  project: z.lazy(() => ElasticIpDataProject$inboundSchema).optional(),
  region: z.nullable(z.lazy(() => ElasticIpDataRegion$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "prefix_length": "prefixLength",
    "created_at": "createdAt",
  });
});
/** @internal */
export type ElasticIpDataAttributes$Outbound = {
  address?: string | undefined;
  family?: string | undefined;
  prefix_length?: number | undefined;
  mode?: string | undefined;
  status?: string | undefined;
  created_at?: string | undefined;
  server?: ElasticIpDataServer$Outbound | null | undefined;
  project?: ElasticIpDataProject$Outbound | undefined;
  region?: ElasticIpDataRegion$Outbound | null | undefined;
};

/** @internal */
export const ElasticIpDataAttributes$outboundSchema: z.ZodType<
  ElasticIpDataAttributes$Outbound,
  z.ZodTypeDef,
  ElasticIpDataAttributes
> = z.object({
  address: z.string().optional(),
  family: ElasticIpDataFamily$outboundSchema.optional(),
  prefixLength: z.number().int().optional(),
  mode: Mode$outboundSchema.optional(),
  status: ElasticIpDataStatus$outboundSchema.optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  server: z.nullable(z.lazy(() => ElasticIpDataServer$outboundSchema))
    .optional(),
  project: z.lazy(() => ElasticIpDataProject$outboundSchema).optional(),
  region: z.nullable(z.lazy(() => ElasticIpDataRegion$outboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    prefixLength: "prefix_length",
    createdAt: "created_at",
  });
});

export function elasticIpDataAttributesToJSON(
  elasticIpDataAttributes: ElasticIpDataAttributes,
): string {
  return JSON.stringify(
    ElasticIpDataAttributes$outboundSchema.parse(elasticIpDataAttributes),
  );
}
export function elasticIpDataAttributesFromJSON(
  jsonString: string,
): SafeParseResult<ElasticIpDataAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ElasticIpDataAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ElasticIpDataAttributes' from JSON`,
  );
}

/** @internal */
export const ElasticIpData$inboundSchema: z.ZodType<
  ElasticIpData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  type: ElasticIpDataType$inboundSchema.optional(),
  attributes: z.lazy(() => ElasticIpDataAttributes$inboundSchema).optional(),
});
/** @internal */
export type ElasticIpData$Outbound = {
  id?: string | null | undefined;
  type?: string | undefined;
  attributes?: ElasticIpDataAttributes$Outbound | undefined;
};

/** @internal */
export const ElasticIpData$outboundSchema: z.ZodType<
  ElasticIpData$Outbound,
  z.ZodTypeDef,
  ElasticIpData
> = z.object({
  id: z.nullable(z.string()).optional(),
  type: ElasticIpDataType$outboundSchema.optional(),
  attributes: z.lazy(() => ElasticIpDataAttributes$outboundSchema).optional(),
});

export function elasticIpDataToJSON(elasticIpData: ElasticIpData): string {
  return JSON.stringify(ElasticIpData$outboundSchema.parse(elasticIpData));
}
export function elasticIpDataFromJSON(
  jsonString: string,
): SafeParseResult<ElasticIpData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ElasticIpData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ElasticIpData' from JSON`,
  );
}
