/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Source = {
  pointer?: string | undefined;
};

export type ErrorObjectMeta = {};

export type ErrorT = {
  code?: string | null | undefined;
  status?: string | undefined;
  title?: string | undefined;
  detail?: string | undefined;
  source?: Source | undefined;
  meta?: ErrorObjectMeta | undefined;
};

/** @internal */
export const Source$inboundSchema: z.ZodType<Source, z.ZodTypeDef, unknown> = z
  .object({
    pointer: z.string().optional(),
  });
/** @internal */
export type Source$Outbound = {
  pointer?: string | undefined;
};

/** @internal */
export const Source$outboundSchema: z.ZodType<
  Source$Outbound,
  z.ZodTypeDef,
  Source
> = z.object({
  pointer: z.string().optional(),
});

export function sourceToJSON(source: Source): string {
  return JSON.stringify(Source$outboundSchema.parse(source));
}
export function sourceFromJSON(
  jsonString: string,
): SafeParseResult<Source, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Source$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Source' from JSON`,
  );
}

/** @internal */
export const ErrorObjectMeta$inboundSchema: z.ZodType<
  ErrorObjectMeta,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type ErrorObjectMeta$Outbound = {};

/** @internal */
export const ErrorObjectMeta$outboundSchema: z.ZodType<
  ErrorObjectMeta$Outbound,
  z.ZodTypeDef,
  ErrorObjectMeta
> = z.object({});

export function errorObjectMetaToJSON(
  errorObjectMeta: ErrorObjectMeta,
): string {
  return JSON.stringify(ErrorObjectMeta$outboundSchema.parse(errorObjectMeta));
}
export function errorObjectMetaFromJSON(
  jsonString: string,
): SafeParseResult<ErrorObjectMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorObjectMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorObjectMeta' from JSON`,
  );
}

/** @internal */
export const ErrorT$inboundSchema: z.ZodType<ErrorT, z.ZodTypeDef, unknown> = z
  .object({
    code: z.nullable(z.string()).optional(),
    status: z.string().optional(),
    title: z.string().optional(),
    detail: z.string().optional(),
    source: z.lazy(() => Source$inboundSchema).optional(),
    meta: z.lazy(() => ErrorObjectMeta$inboundSchema).optional(),
  });
/** @internal */
export type ErrorT$Outbound = {
  code?: string | null | undefined;
  status?: string | undefined;
  title?: string | undefined;
  detail?: string | undefined;
  source?: Source$Outbound | undefined;
  meta?: ErrorObjectMeta$Outbound | undefined;
};

/** @internal */
export const ErrorT$outboundSchema: z.ZodType<
  ErrorT$Outbound,
  z.ZodTypeDef,
  ErrorT
> = z.object({
  code: z.nullable(z.string()).optional(),
  status: z.string().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
  source: z.lazy(() => Source$outboundSchema).optional(),
  meta: z.lazy(() => ErrorObjectMeta$outboundSchema).optional(),
});

export function errorToJSON(errorT: ErrorT): string {
  return JSON.stringify(ErrorT$outboundSchema.parse(errorT));
}
export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}
