/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const FirewallDataType = {
  Firewalls: "firewalls",
} as const;
export type FirewallDataType = ClosedEnum<typeof FirewallDataType>;

export type Rule = {
  /**
   * Source IP address, IP range in CIDR notation, or 'ANY' (e.g., "192.168.1.1", "192.168.1.0/24", "ANY")
   */
  from?: string | undefined;
  /**
   * Destination IP address, IP range in CIDR notation, or 'ANY' (e.g., "192.168.1.1", "192.168.1.0/24", "ANY")
   */
  to?: string | undefined;
  port?: string | undefined;
  protocol?: string | undefined;
};

export type FirewallDataProject = {
  id?: string | undefined;
  slug?: string | undefined;
  name?: string | undefined;
};

export type FirewallDataAttributes = {
  name?: string | undefined;
  rules?: Array<Rule> | undefined;
  project?: FirewallDataProject | undefined;
};

export type FirewallData = {
  id?: string | undefined;
  type?: FirewallDataType | undefined;
  attributes?: FirewallDataAttributes | undefined;
};

/** @internal */
export const FirewallDataType$inboundSchema: z.ZodNativeEnum<
  typeof FirewallDataType
> = z.nativeEnum(FirewallDataType);

/** @internal */
export const FirewallDataType$outboundSchema: z.ZodNativeEnum<
  typeof FirewallDataType
> = FirewallDataType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FirewallDataType$ {
  /** @deprecated use `FirewallDataType$inboundSchema` instead. */
  export const inboundSchema = FirewallDataType$inboundSchema;
  /** @deprecated use `FirewallDataType$outboundSchema` instead. */
  export const outboundSchema = FirewallDataType$outboundSchema;
}

/** @internal */
export const Rule$inboundSchema: z.ZodType<Rule, z.ZodTypeDef, unknown> = z
  .object({
    from: z.string().optional(),
    to: z.string().optional(),
    port: z.string().optional(),
    protocol: z.string().optional(),
  });

/** @internal */
export type Rule$Outbound = {
  from?: string | undefined;
  to?: string | undefined;
  port?: string | undefined;
  protocol?: string | undefined;
};

/** @internal */
export const Rule$outboundSchema: z.ZodType<Rule$Outbound, z.ZodTypeDef, Rule> =
  z.object({
    from: z.string().optional(),
    to: z.string().optional(),
    port: z.string().optional(),
    protocol: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Rule$ {
  /** @deprecated use `Rule$inboundSchema` instead. */
  export const inboundSchema = Rule$inboundSchema;
  /** @deprecated use `Rule$outboundSchema` instead. */
  export const outboundSchema = Rule$outboundSchema;
  /** @deprecated use `Rule$Outbound` instead. */
  export type Outbound = Rule$Outbound;
}

export function ruleToJSON(rule: Rule): string {
  return JSON.stringify(Rule$outboundSchema.parse(rule));
}

export function ruleFromJSON(
  jsonString: string,
): SafeParseResult<Rule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Rule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Rule' from JSON`,
  );
}

/** @internal */
export const FirewallDataProject$inboundSchema: z.ZodType<
  FirewallDataProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  slug: z.string().optional(),
  name: z.string().optional(),
});

/** @internal */
export type FirewallDataProject$Outbound = {
  id?: string | undefined;
  slug?: string | undefined;
  name?: string | undefined;
};

/** @internal */
export const FirewallDataProject$outboundSchema: z.ZodType<
  FirewallDataProject$Outbound,
  z.ZodTypeDef,
  FirewallDataProject
> = z.object({
  id: z.string().optional(),
  slug: z.string().optional(),
  name: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FirewallDataProject$ {
  /** @deprecated use `FirewallDataProject$inboundSchema` instead. */
  export const inboundSchema = FirewallDataProject$inboundSchema;
  /** @deprecated use `FirewallDataProject$outboundSchema` instead. */
  export const outboundSchema = FirewallDataProject$outboundSchema;
  /** @deprecated use `FirewallDataProject$Outbound` instead. */
  export type Outbound = FirewallDataProject$Outbound;
}

export function firewallDataProjectToJSON(
  firewallDataProject: FirewallDataProject,
): string {
  return JSON.stringify(
    FirewallDataProject$outboundSchema.parse(firewallDataProject),
  );
}

export function firewallDataProjectFromJSON(
  jsonString: string,
): SafeParseResult<FirewallDataProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FirewallDataProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FirewallDataProject' from JSON`,
  );
}

/** @internal */
export const FirewallDataAttributes$inboundSchema: z.ZodType<
  FirewallDataAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  rules: z.array(z.lazy(() => Rule$inboundSchema)).optional(),
  project: z.lazy(() => FirewallDataProject$inboundSchema).optional(),
});

/** @internal */
export type FirewallDataAttributes$Outbound = {
  name?: string | undefined;
  rules?: Array<Rule$Outbound> | undefined;
  project?: FirewallDataProject$Outbound | undefined;
};

/** @internal */
export const FirewallDataAttributes$outboundSchema: z.ZodType<
  FirewallDataAttributes$Outbound,
  z.ZodTypeDef,
  FirewallDataAttributes
> = z.object({
  name: z.string().optional(),
  rules: z.array(z.lazy(() => Rule$outboundSchema)).optional(),
  project: z.lazy(() => FirewallDataProject$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FirewallDataAttributes$ {
  /** @deprecated use `FirewallDataAttributes$inboundSchema` instead. */
  export const inboundSchema = FirewallDataAttributes$inboundSchema;
  /** @deprecated use `FirewallDataAttributes$outboundSchema` instead. */
  export const outboundSchema = FirewallDataAttributes$outboundSchema;
  /** @deprecated use `FirewallDataAttributes$Outbound` instead. */
  export type Outbound = FirewallDataAttributes$Outbound;
}

export function firewallDataAttributesToJSON(
  firewallDataAttributes: FirewallDataAttributes,
): string {
  return JSON.stringify(
    FirewallDataAttributes$outboundSchema.parse(firewallDataAttributes),
  );
}

export function firewallDataAttributesFromJSON(
  jsonString: string,
): SafeParseResult<FirewallDataAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FirewallDataAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FirewallDataAttributes' from JSON`,
  );
}

/** @internal */
export const FirewallData$inboundSchema: z.ZodType<
  FirewallData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  type: FirewallDataType$inboundSchema.optional(),
  attributes: z.lazy(() => FirewallDataAttributes$inboundSchema).optional(),
});

/** @internal */
export type FirewallData$Outbound = {
  id?: string | undefined;
  type?: string | undefined;
  attributes?: FirewallDataAttributes$Outbound | undefined;
};

/** @internal */
export const FirewallData$outboundSchema: z.ZodType<
  FirewallData$Outbound,
  z.ZodTypeDef,
  FirewallData
> = z.object({
  id: z.string().optional(),
  type: FirewallDataType$outboundSchema.optional(),
  attributes: z.lazy(() => FirewallDataAttributes$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FirewallData$ {
  /** @deprecated use `FirewallData$inboundSchema` instead. */
  export const inboundSchema = FirewallData$inboundSchema;
  /** @deprecated use `FirewallData$outboundSchema` instead. */
  export const outboundSchema = FirewallData$outboundSchema;
  /** @deprecated use `FirewallData$Outbound` instead. */
  export type Outbound = FirewallData$Outbound;
}

export function firewallDataToJSON(firewallData: FirewallData): string {
  return JSON.stringify(FirewallData$outboundSchema.parse(firewallData));
}

export function firewallDataFromJSON(
  jsonString: string,
): SafeParseResult<FirewallData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FirewallData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FirewallData' from JSON`,
  );
}
