/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FirewallAssignmentData,
  FirewallAssignmentData$inboundSchema,
  FirewallAssignmentData$Outbound,
  FirewallAssignmentData$outboundSchema,
} from "./firewallassignmentdata.js";

export type FirewallAssignmentsMeta = {};

export type FirewallAssignments = {
  data?: Array<FirewallAssignmentData> | undefined;
  meta?: FirewallAssignmentsMeta | undefined;
};

/** @internal */
export const FirewallAssignmentsMeta$inboundSchema: z.ZodType<
  FirewallAssignmentsMeta,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type FirewallAssignmentsMeta$Outbound = {};

/** @internal */
export const FirewallAssignmentsMeta$outboundSchema: z.ZodType<
  FirewallAssignmentsMeta$Outbound,
  z.ZodTypeDef,
  FirewallAssignmentsMeta
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FirewallAssignmentsMeta$ {
  /** @deprecated use `FirewallAssignmentsMeta$inboundSchema` instead. */
  export const inboundSchema = FirewallAssignmentsMeta$inboundSchema;
  /** @deprecated use `FirewallAssignmentsMeta$outboundSchema` instead. */
  export const outboundSchema = FirewallAssignmentsMeta$outboundSchema;
  /** @deprecated use `FirewallAssignmentsMeta$Outbound` instead. */
  export type Outbound = FirewallAssignmentsMeta$Outbound;
}

export function firewallAssignmentsMetaToJSON(
  firewallAssignmentsMeta: FirewallAssignmentsMeta,
): string {
  return JSON.stringify(
    FirewallAssignmentsMeta$outboundSchema.parse(firewallAssignmentsMeta),
  );
}

export function firewallAssignmentsMetaFromJSON(
  jsonString: string,
): SafeParseResult<FirewallAssignmentsMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FirewallAssignmentsMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FirewallAssignmentsMeta' from JSON`,
  );
}

/** @internal */
export const FirewallAssignments$inboundSchema: z.ZodType<
  FirewallAssignments,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(FirewallAssignmentData$inboundSchema).optional(),
  meta: z.lazy(() => FirewallAssignmentsMeta$inboundSchema).optional(),
});

/** @internal */
export type FirewallAssignments$Outbound = {
  data?: Array<FirewallAssignmentData$Outbound> | undefined;
  meta?: FirewallAssignmentsMeta$Outbound | undefined;
};

/** @internal */
export const FirewallAssignments$outboundSchema: z.ZodType<
  FirewallAssignments$Outbound,
  z.ZodTypeDef,
  FirewallAssignments
> = z.object({
  data: z.array(FirewallAssignmentData$outboundSchema).optional(),
  meta: z.lazy(() => FirewallAssignmentsMeta$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FirewallAssignments$ {
  /** @deprecated use `FirewallAssignments$inboundSchema` instead. */
  export const inboundSchema = FirewallAssignments$inboundSchema;
  /** @deprecated use `FirewallAssignments$outboundSchema` instead. */
  export const outboundSchema = FirewallAssignments$outboundSchema;
  /** @deprecated use `FirewallAssignments$Outbound` instead. */
  export type Outbound = FirewallAssignments$Outbound;
}

export function firewallAssignmentsToJSON(
  firewallAssignments: FirewallAssignments,
): string {
  return JSON.stringify(
    FirewallAssignments$outboundSchema.parse(firewallAssignments),
  );
}

export function firewallAssignmentsFromJSON(
  jsonString: string,
): SafeParseResult<FirewallAssignments, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FirewallAssignments$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FirewallAssignments' from JSON`,
  );
}
