/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FirewallData,
  FirewallData$inboundSchema,
  FirewallData$Outbound,
  FirewallData$outboundSchema,
} from "./firewalldata.js";

export type FirewallsMeta = {};

export type Firewalls = {
  data?: Array<FirewallData> | undefined;
  meta?: FirewallsMeta | undefined;
};

/** @internal */
export const FirewallsMeta$inboundSchema: z.ZodType<
  FirewallsMeta,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type FirewallsMeta$Outbound = {};

/** @internal */
export const FirewallsMeta$outboundSchema: z.ZodType<
  FirewallsMeta$Outbound,
  z.ZodTypeDef,
  FirewallsMeta
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FirewallsMeta$ {
  /** @deprecated use `FirewallsMeta$inboundSchema` instead. */
  export const inboundSchema = FirewallsMeta$inboundSchema;
  /** @deprecated use `FirewallsMeta$outboundSchema` instead. */
  export const outboundSchema = FirewallsMeta$outboundSchema;
  /** @deprecated use `FirewallsMeta$Outbound` instead. */
  export type Outbound = FirewallsMeta$Outbound;
}

export function firewallsMetaToJSON(firewallsMeta: FirewallsMeta): string {
  return JSON.stringify(FirewallsMeta$outboundSchema.parse(firewallsMeta));
}

export function firewallsMetaFromJSON(
  jsonString: string,
): SafeParseResult<FirewallsMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FirewallsMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FirewallsMeta' from JSON`,
  );
}

/** @internal */
export const Firewalls$inboundSchema: z.ZodType<
  Firewalls,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(FirewallData$inboundSchema).optional(),
  meta: z.lazy(() => FirewallsMeta$inboundSchema).optional(),
});

/** @internal */
export type Firewalls$Outbound = {
  data?: Array<FirewallData$Outbound> | undefined;
  meta?: FirewallsMeta$Outbound | undefined;
};

/** @internal */
export const Firewalls$outboundSchema: z.ZodType<
  Firewalls$Outbound,
  z.ZodTypeDef,
  Firewalls
> = z.object({
  data: z.array(FirewallData$outboundSchema).optional(),
  meta: z.lazy(() => FirewallsMeta$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Firewalls$ {
  /** @deprecated use `Firewalls$inboundSchema` instead. */
  export const inboundSchema = Firewalls$inboundSchema;
  /** @deprecated use `Firewalls$outboundSchema` instead. */
  export const outboundSchema = Firewalls$outboundSchema;
  /** @deprecated use `Firewalls$Outbound` instead. */
  export type Outbound = Firewalls$Outbound;
}

export function firewallsToJSON(firewalls: Firewalls): string {
  return JSON.stringify(Firewalls$outboundSchema.parse(firewalls));
}

export function firewallsFromJSON(
  jsonString: string,
): SafeParseResult<Firewalls, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Firewalls$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Firewalls' from JSON`,
  );
}
