/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  IpAddressData,
  IpAddressData$inboundSchema,
  IpAddressData$Outbound,
  IpAddressData$outboundSchema,
} from "./ipaddressdata.js";

export type IpAddressMeta = {};

export type IpAddress = {
  data?: IpAddressData | undefined;
  meta?: IpAddressMeta | undefined;
};

/** @internal */
export const IpAddressMeta$inboundSchema: z.ZodType<
  IpAddressMeta,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type IpAddressMeta$Outbound = {};

/** @internal */
export const IpAddressMeta$outboundSchema: z.ZodType<
  IpAddressMeta$Outbound,
  z.ZodTypeDef,
  IpAddressMeta
> = z.object({});

export function ipAddressMetaToJSON(ipAddressMeta: IpAddressMeta): string {
  return JSON.stringify(IpAddressMeta$outboundSchema.parse(ipAddressMeta));
}
export function ipAddressMetaFromJSON(
  jsonString: string,
): SafeParseResult<IpAddressMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IpAddressMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IpAddressMeta' from JSON`,
  );
}

/** @internal */
export const IpAddress$inboundSchema: z.ZodType<
  IpAddress,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: IpAddressData$inboundSchema.optional(),
  meta: z.lazy(() => IpAddressMeta$inboundSchema).optional(),
});
/** @internal */
export type IpAddress$Outbound = {
  data?: IpAddressData$Outbound | undefined;
  meta?: IpAddressMeta$Outbound | undefined;
};

/** @internal */
export const IpAddress$outboundSchema: z.ZodType<
  IpAddress$Outbound,
  z.ZodTypeDef,
  IpAddress
> = z.object({
  data: IpAddressData$outboundSchema.optional(),
  meta: z.lazy(() => IpAddressMeta$outboundSchema).optional(),
});

export function ipAddressToJSON(ipAddress: IpAddress): string {
  return JSON.stringify(IpAddress$outboundSchema.parse(ipAddress));
}
export function ipAddressFromJSON(
  jsonString: string,
): SafeParseResult<IpAddress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IpAddress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IpAddress' from JSON`,
  );
}
