/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const TypeIPAddresses = {
  IpAddresses: "ip_addresses",
} as const;
export type TypeIPAddresses = ClosedEnum<typeof TypeIPAddresses>;

export const IpAddressDataFamily = {
  IPv4: "IPv4",
  IPv6: "IPv6",
} as const;
export type IpAddressDataFamily = ClosedEnum<typeof IpAddressDataFamily>;

export const IpAddressDataAttributesType = {
  Public: "Public",
  Private: "Private",
  Elastic: "Elastic",
} as const;
export type IpAddressDataAttributesType = ClosedEnum<
  typeof IpAddressDataAttributesType
>;

export type IpAddressDataProject = {
  id?: string | undefined;
  name?: string | undefined;
};

export type IpAddressDataLocation = {
  id?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
};

export type IpAddressDataRegion = {
  id?: string | undefined;
  name?: string | undefined;
  location?: IpAddressDataLocation | undefined;
};

/**
 * Server assignment information. Returns an empty object when the IP is not assigned to an active server (e.g., when the server is decommissioning or deleted). The hostname is null when the assigned server has no hostname set.
 */
export type Assignment = {
  serverId?: string | undefined;
  hostname?: string | null | undefined;
  assignedAt?: string | undefined;
};

/**
 * Elastic IP details. Returns an empty object when the IP is not an Elastic IP.
 */
export type Elastic = {
  id?: string | undefined;
  mode?: string | undefined;
  status?: string | undefined;
};

export type IpAddressDataAttributes = {
  address?: string | undefined;
  cidr?: string | null | undefined;
  family?: IpAddressDataFamily | undefined;
  gateway?: string | null | undefined;
  netmask?: string | undefined;
  type?: IpAddressDataAttributesType | undefined;
  public?: boolean | undefined;
  management?: boolean | undefined;
  additional?: boolean | undefined;
  project?: IpAddressDataProject | undefined;
  region?: IpAddressDataRegion | undefined;
  available?: boolean | undefined;
  /**
   * Server assignment information. Returns an empty object when the IP is not assigned to an active server (e.g., when the server is decommissioning or deleted). The hostname is null when the assigned server has no hostname set.
   */
  assignment?: Assignment | undefined;
  /**
   * Elastic IP details. Returns an empty object when the IP is not an Elastic IP.
   */
  elastic?: Elastic | undefined;
  createdAt?: Date | null | undefined;
};

export type IpAddressData = {
  id?: string | undefined;
  type?: TypeIPAddresses | undefined;
  attributes?: IpAddressDataAttributes | undefined;
};

/** @internal */
export const TypeIPAddresses$inboundSchema: z.ZodNativeEnum<
  typeof TypeIPAddresses
> = z.nativeEnum(TypeIPAddresses);
/** @internal */
export const TypeIPAddresses$outboundSchema: z.ZodNativeEnum<
  typeof TypeIPAddresses
> = TypeIPAddresses$inboundSchema;

/** @internal */
export const IpAddressDataFamily$inboundSchema: z.ZodNativeEnum<
  typeof IpAddressDataFamily
> = z.nativeEnum(IpAddressDataFamily);
/** @internal */
export const IpAddressDataFamily$outboundSchema: z.ZodNativeEnum<
  typeof IpAddressDataFamily
> = IpAddressDataFamily$inboundSchema;

/** @internal */
export const IpAddressDataAttributesType$inboundSchema: z.ZodNativeEnum<
  typeof IpAddressDataAttributesType
> = z.nativeEnum(IpAddressDataAttributesType);
/** @internal */
export const IpAddressDataAttributesType$outboundSchema: z.ZodNativeEnum<
  typeof IpAddressDataAttributesType
> = IpAddressDataAttributesType$inboundSchema;

/** @internal */
export const IpAddressDataProject$inboundSchema: z.ZodType<
  IpAddressDataProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
});
/** @internal */
export type IpAddressDataProject$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
};

/** @internal */
export const IpAddressDataProject$outboundSchema: z.ZodType<
  IpAddressDataProject$Outbound,
  z.ZodTypeDef,
  IpAddressDataProject
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
});

export function ipAddressDataProjectToJSON(
  ipAddressDataProject: IpAddressDataProject,
): string {
  return JSON.stringify(
    IpAddressDataProject$outboundSchema.parse(ipAddressDataProject),
  );
}
export function ipAddressDataProjectFromJSON(
  jsonString: string,
): SafeParseResult<IpAddressDataProject, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IpAddressDataProject$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IpAddressDataProject' from JSON`,
  );
}

/** @internal */
export const IpAddressDataLocation$inboundSchema: z.ZodType<
  IpAddressDataLocation,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
});
/** @internal */
export type IpAddressDataLocation$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
};

/** @internal */
export const IpAddressDataLocation$outboundSchema: z.ZodType<
  IpAddressDataLocation$Outbound,
  z.ZodTypeDef,
  IpAddressDataLocation
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
});

export function ipAddressDataLocationToJSON(
  ipAddressDataLocation: IpAddressDataLocation,
): string {
  return JSON.stringify(
    IpAddressDataLocation$outboundSchema.parse(ipAddressDataLocation),
  );
}
export function ipAddressDataLocationFromJSON(
  jsonString: string,
): SafeParseResult<IpAddressDataLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IpAddressDataLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IpAddressDataLocation' from JSON`,
  );
}

/** @internal */
export const IpAddressDataRegion$inboundSchema: z.ZodType<
  IpAddressDataRegion,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  location: z.lazy(() => IpAddressDataLocation$inboundSchema).optional(),
});
/** @internal */
export type IpAddressDataRegion$Outbound = {
  id?: string | undefined;
  name?: string | undefined;
  location?: IpAddressDataLocation$Outbound | undefined;
};

/** @internal */
export const IpAddressDataRegion$outboundSchema: z.ZodType<
  IpAddressDataRegion$Outbound,
  z.ZodTypeDef,
  IpAddressDataRegion
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  location: z.lazy(() => IpAddressDataLocation$outboundSchema).optional(),
});

export function ipAddressDataRegionToJSON(
  ipAddressDataRegion: IpAddressDataRegion,
): string {
  return JSON.stringify(
    IpAddressDataRegion$outboundSchema.parse(ipAddressDataRegion),
  );
}
export function ipAddressDataRegionFromJSON(
  jsonString: string,
): SafeParseResult<IpAddressDataRegion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IpAddressDataRegion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IpAddressDataRegion' from JSON`,
  );
}

/** @internal */
export const Assignment$inboundSchema: z.ZodType<
  Assignment,
  z.ZodTypeDef,
  unknown
> = z.object({
  server_id: z.string().optional(),
  hostname: z.nullable(z.string()).optional(),
  assigned_at: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "server_id": "serverId",
    "assigned_at": "assignedAt",
  });
});
/** @internal */
export type Assignment$Outbound = {
  server_id?: string | undefined;
  hostname?: string | null | undefined;
  assigned_at?: string | undefined;
};

/** @internal */
export const Assignment$outboundSchema: z.ZodType<
  Assignment$Outbound,
  z.ZodTypeDef,
  Assignment
> = z.object({
  serverId: z.string().optional(),
  hostname: z.nullable(z.string()).optional(),
  assignedAt: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    serverId: "server_id",
    assignedAt: "assigned_at",
  });
});

export function assignmentToJSON(assignment: Assignment): string {
  return JSON.stringify(Assignment$outboundSchema.parse(assignment));
}
export function assignmentFromJSON(
  jsonString: string,
): SafeParseResult<Assignment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Assignment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Assignment' from JSON`,
  );
}

/** @internal */
export const Elastic$inboundSchema: z.ZodType<Elastic, z.ZodTypeDef, unknown> =
  z.object({
    id: z.string().optional(),
    mode: z.string().optional(),
    status: z.string().optional(),
  });
/** @internal */
export type Elastic$Outbound = {
  id?: string | undefined;
  mode?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const Elastic$outboundSchema: z.ZodType<
  Elastic$Outbound,
  z.ZodTypeDef,
  Elastic
> = z.object({
  id: z.string().optional(),
  mode: z.string().optional(),
  status: z.string().optional(),
});

export function elasticToJSON(elastic: Elastic): string {
  return JSON.stringify(Elastic$outboundSchema.parse(elastic));
}
export function elasticFromJSON(
  jsonString: string,
): SafeParseResult<Elastic, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Elastic$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Elastic' from JSON`,
  );
}

/** @internal */
export const IpAddressDataAttributes$inboundSchema: z.ZodType<
  IpAddressDataAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: z.string().optional(),
  cidr: z.nullable(z.string()).optional(),
  family: IpAddressDataFamily$inboundSchema.optional(),
  gateway: z.nullable(z.string()).optional(),
  netmask: z.string().optional(),
  type: IpAddressDataAttributesType$inboundSchema.optional(),
  public: z.boolean().optional(),
  management: z.boolean().optional(),
  additional: z.boolean().optional(),
  project: z.lazy(() => IpAddressDataProject$inboundSchema).optional(),
  region: z.lazy(() => IpAddressDataRegion$inboundSchema).optional(),
  available: z.boolean().optional(),
  assignment: z.lazy(() => Assignment$inboundSchema).optional(),
  elastic: z.lazy(() => Elastic$inboundSchema).optional(),
  created_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type IpAddressDataAttributes$Outbound = {
  address?: string | undefined;
  cidr?: string | null | undefined;
  family?: string | undefined;
  gateway?: string | null | undefined;
  netmask?: string | undefined;
  type?: string | undefined;
  public?: boolean | undefined;
  management?: boolean | undefined;
  additional?: boolean | undefined;
  project?: IpAddressDataProject$Outbound | undefined;
  region?: IpAddressDataRegion$Outbound | undefined;
  available?: boolean | undefined;
  assignment?: Assignment$Outbound | undefined;
  elastic?: Elastic$Outbound | undefined;
  created_at?: string | null | undefined;
};

/** @internal */
export const IpAddressDataAttributes$outboundSchema: z.ZodType<
  IpAddressDataAttributes$Outbound,
  z.ZodTypeDef,
  IpAddressDataAttributes
> = z.object({
  address: z.string().optional(),
  cidr: z.nullable(z.string()).optional(),
  family: IpAddressDataFamily$outboundSchema.optional(),
  gateway: z.nullable(z.string()).optional(),
  netmask: z.string().optional(),
  type: IpAddressDataAttributesType$outboundSchema.optional(),
  public: z.boolean().optional(),
  management: z.boolean().optional(),
  additional: z.boolean().optional(),
  project: z.lazy(() => IpAddressDataProject$outboundSchema).optional(),
  region: z.lazy(() => IpAddressDataRegion$outboundSchema).optional(),
  available: z.boolean().optional(),
  assignment: z.lazy(() => Assignment$outboundSchema).optional(),
  elastic: z.lazy(() => Elastic$outboundSchema).optional(),
  createdAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function ipAddressDataAttributesToJSON(
  ipAddressDataAttributes: IpAddressDataAttributes,
): string {
  return JSON.stringify(
    IpAddressDataAttributes$outboundSchema.parse(ipAddressDataAttributes),
  );
}
export function ipAddressDataAttributesFromJSON(
  jsonString: string,
): SafeParseResult<IpAddressDataAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IpAddressDataAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IpAddressDataAttributes' from JSON`,
  );
}

/** @internal */
export const IpAddressData$inboundSchema: z.ZodType<
  IpAddressData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  type: TypeIPAddresses$inboundSchema.optional(),
  attributes: z.lazy(() => IpAddressDataAttributes$inboundSchema).optional(),
});
/** @internal */
export type IpAddressData$Outbound = {
  id?: string | undefined;
  type?: string | undefined;
  attributes?: IpAddressDataAttributes$Outbound | undefined;
};

/** @internal */
export const IpAddressData$outboundSchema: z.ZodType<
  IpAddressData$Outbound,
  z.ZodTypeDef,
  IpAddressData
> = z.object({
  id: z.string().optional(),
  type: TypeIPAddresses$outboundSchema.optional(),
  attributes: z.lazy(() => IpAddressDataAttributes$outboundSchema).optional(),
});

export function ipAddressDataToJSON(ipAddressData: IpAddressData): string {
  return JSON.stringify(IpAddressData$outboundSchema.parse(ipAddressData));
}
export function ipAddressDataFromJSON(
  jsonString: string,
): SafeParseResult<IpAddressData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IpAddressData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IpAddressData' from JSON`,
  );
}
