/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type KubernetesAvailableVersionsData = {
  /**
   * The latest full Kubernetes version string for this minor version (e.g., v1.35.3+rke2r1)
   */
  latest?: string | undefined;
  /**
   * The minor version number (e.g., 1.35)
   */
  minor?: string | undefined;
};

/**
 * Response schema for available Kubernetes versions
 */
export type KubernetesAvailableVersions = {
  data?: Array<KubernetesAvailableVersionsData> | undefined;
};

/** @internal */
export const KubernetesAvailableVersionsData$inboundSchema: z.ZodType<
  KubernetesAvailableVersionsData,
  z.ZodTypeDef,
  unknown
> = z.object({
  latest: z.string().optional(),
  minor: z.string().optional(),
});
/** @internal */
export type KubernetesAvailableVersionsData$Outbound = {
  latest?: string | undefined;
  minor?: string | undefined;
};

/** @internal */
export const KubernetesAvailableVersionsData$outboundSchema: z.ZodType<
  KubernetesAvailableVersionsData$Outbound,
  z.ZodTypeDef,
  KubernetesAvailableVersionsData
> = z.object({
  latest: z.string().optional(),
  minor: z.string().optional(),
});

export function kubernetesAvailableVersionsDataToJSON(
  kubernetesAvailableVersionsData: KubernetesAvailableVersionsData,
): string {
  return JSON.stringify(
    KubernetesAvailableVersionsData$outboundSchema.parse(
      kubernetesAvailableVersionsData,
    ),
  );
}
export function kubernetesAvailableVersionsDataFromJSON(
  jsonString: string,
): SafeParseResult<KubernetesAvailableVersionsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KubernetesAvailableVersionsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KubernetesAvailableVersionsData' from JSON`,
  );
}

/** @internal */
export const KubernetesAvailableVersions$inboundSchema: z.ZodType<
  KubernetesAvailableVersions,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(z.lazy(() => KubernetesAvailableVersionsData$inboundSchema))
    .optional(),
});
/** @internal */
export type KubernetesAvailableVersions$Outbound = {
  data?: Array<KubernetesAvailableVersionsData$Outbound> | undefined;
};

/** @internal */
export const KubernetesAvailableVersions$outboundSchema: z.ZodType<
  KubernetesAvailableVersions$Outbound,
  z.ZodTypeDef,
  KubernetesAvailableVersions
> = z.object({
  data: z.array(z.lazy(() => KubernetesAvailableVersionsData$outboundSchema))
    .optional(),
});

export function kubernetesAvailableVersionsToJSON(
  kubernetesAvailableVersions: KubernetesAvailableVersions,
): string {
  return JSON.stringify(
    KubernetesAvailableVersions$outboundSchema.parse(
      kubernetesAvailableVersions,
    ),
  );
}
export function kubernetesAvailableVersionsFromJSON(
  jsonString: string,
): SafeParseResult<KubernetesAvailableVersions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KubernetesAvailableVersions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KubernetesAvailableVersions' from JSON`,
  );
}
