/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type KubernetesClusterKubeconfigAttributes = {
  /**
   * The cluster name
   */
  clusterName?: string | undefined;
  /**
   * The kubeconfig YAML content for connecting to the cluster
   */
  kubeconfig?: string | undefined;
};

export type KubernetesClusterKubeconfigData = {
  /**
   * The cluster name
   */
  id?: string | undefined;
  type?: string | undefined;
  attributes?: KubernetesClusterKubeconfigAttributes | undefined;
};

export type KubernetesClusterKubeconfig = {
  data?: KubernetesClusterKubeconfigData | undefined;
};

/** @internal */
export const KubernetesClusterKubeconfigAttributes$inboundSchema: z.ZodType<
  KubernetesClusterKubeconfigAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  cluster_name: z.string().optional(),
  kubeconfig: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cluster_name": "clusterName",
  });
});
/** @internal */
export type KubernetesClusterKubeconfigAttributes$Outbound = {
  cluster_name?: string | undefined;
  kubeconfig?: string | undefined;
};

/** @internal */
export const KubernetesClusterKubeconfigAttributes$outboundSchema: z.ZodType<
  KubernetesClusterKubeconfigAttributes$Outbound,
  z.ZodTypeDef,
  KubernetesClusterKubeconfigAttributes
> = z.object({
  clusterName: z.string().optional(),
  kubeconfig: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    clusterName: "cluster_name",
  });
});

export function kubernetesClusterKubeconfigAttributesToJSON(
  kubernetesClusterKubeconfigAttributes: KubernetesClusterKubeconfigAttributes,
): string {
  return JSON.stringify(
    KubernetesClusterKubeconfigAttributes$outboundSchema.parse(
      kubernetesClusterKubeconfigAttributes,
    ),
  );
}
export function kubernetesClusterKubeconfigAttributesFromJSON(
  jsonString: string,
): SafeParseResult<KubernetesClusterKubeconfigAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      KubernetesClusterKubeconfigAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KubernetesClusterKubeconfigAttributes' from JSON`,
  );
}

/** @internal */
export const KubernetesClusterKubeconfigData$inboundSchema: z.ZodType<
  KubernetesClusterKubeconfigData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  type: z.string().optional(),
  attributes: z.lazy(() => KubernetesClusterKubeconfigAttributes$inboundSchema)
    .optional(),
});
/** @internal */
export type KubernetesClusterKubeconfigData$Outbound = {
  id?: string | undefined;
  type?: string | undefined;
  attributes?: KubernetesClusterKubeconfigAttributes$Outbound | undefined;
};

/** @internal */
export const KubernetesClusterKubeconfigData$outboundSchema: z.ZodType<
  KubernetesClusterKubeconfigData$Outbound,
  z.ZodTypeDef,
  KubernetesClusterKubeconfigData
> = z.object({
  id: z.string().optional(),
  type: z.string().optional(),
  attributes: z.lazy(() => KubernetesClusterKubeconfigAttributes$outboundSchema)
    .optional(),
});

export function kubernetesClusterKubeconfigDataToJSON(
  kubernetesClusterKubeconfigData: KubernetesClusterKubeconfigData,
): string {
  return JSON.stringify(
    KubernetesClusterKubeconfigData$outboundSchema.parse(
      kubernetesClusterKubeconfigData,
    ),
  );
}
export function kubernetesClusterKubeconfigDataFromJSON(
  jsonString: string,
): SafeParseResult<KubernetesClusterKubeconfigData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KubernetesClusterKubeconfigData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KubernetesClusterKubeconfigData' from JSON`,
  );
}

/** @internal */
export const KubernetesClusterKubeconfig$inboundSchema: z.ZodType<
  KubernetesClusterKubeconfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => KubernetesClusterKubeconfigData$inboundSchema).optional(),
});
/** @internal */
export type KubernetesClusterKubeconfig$Outbound = {
  data?: KubernetesClusterKubeconfigData$Outbound | undefined;
};

/** @internal */
export const KubernetesClusterKubeconfig$outboundSchema: z.ZodType<
  KubernetesClusterKubeconfig$Outbound,
  z.ZodTypeDef,
  KubernetesClusterKubeconfig
> = z.object({
  data: z.lazy(() => KubernetesClusterKubeconfigData$outboundSchema).optional(),
});

export function kubernetesClusterKubeconfigToJSON(
  kubernetesClusterKubeconfig: KubernetesClusterKubeconfig,
): string {
  return JSON.stringify(
    KubernetesClusterKubeconfig$outboundSchema.parse(
      kubernetesClusterKubeconfig,
    ),
  );
}
export function kubernetesClusterKubeconfigFromJSON(
  jsonString: string,
): SafeParseResult<KubernetesClusterKubeconfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KubernetesClusterKubeconfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KubernetesClusterKubeconfig' from JSON`,
  );
}
