/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  KubernetesClusterSummaryData,
  KubernetesClusterSummaryData$inboundSchema,
  KubernetesClusterSummaryData$Outbound,
  KubernetesClusterSummaryData$outboundSchema,
} from "./kubernetesclustersummarydata.js";

/**
 * Response schema for listing clusters (uses summary representation)
 */
export type KubernetesClusters = {
  data?: Array<KubernetesClusterSummaryData> | undefined;
};

/** @internal */
export const KubernetesClusters$inboundSchema: z.ZodType<
  KubernetesClusters,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(KubernetesClusterSummaryData$inboundSchema).optional(),
});
/** @internal */
export type KubernetesClusters$Outbound = {
  data?: Array<KubernetesClusterSummaryData$Outbound> | undefined;
};

/** @internal */
export const KubernetesClusters$outboundSchema: z.ZodType<
  KubernetesClusters$Outbound,
  z.ZodTypeDef,
  KubernetesClusters
> = z.object({
  data: z.array(KubernetesClusterSummaryData$outboundSchema).optional(),
});

export function kubernetesClustersToJSON(
  kubernetesClusters: KubernetesClusters,
): string {
  return JSON.stringify(
    KubernetesClusters$outboundSchema.parse(kubernetesClusters),
  );
}
export function kubernetesClustersFromJSON(
  jsonString: string,
): SafeParseResult<KubernetesClusters, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KubernetesClusters$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KubernetesClusters' from JSON`,
  );
}
