/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OperatingSystemData,
  OperatingSystemData$inboundSchema,
  OperatingSystemData$Outbound,
  OperatingSystemData$outboundSchema,
} from "./operatingsystemdata.js";

export type OperatingSystemsMeta = {};

export type OperatingSystems = {
  data?: Array<OperatingSystemData> | undefined;
  meta?: OperatingSystemsMeta | undefined;
};

/** @internal */
export const OperatingSystemsMeta$inboundSchema: z.ZodType<
  OperatingSystemsMeta,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type OperatingSystemsMeta$Outbound = {};

/** @internal */
export const OperatingSystemsMeta$outboundSchema: z.ZodType<
  OperatingSystemsMeta$Outbound,
  z.ZodTypeDef,
  OperatingSystemsMeta
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OperatingSystemsMeta$ {
  /** @deprecated use `OperatingSystemsMeta$inboundSchema` instead. */
  export const inboundSchema = OperatingSystemsMeta$inboundSchema;
  /** @deprecated use `OperatingSystemsMeta$outboundSchema` instead. */
  export const outboundSchema = OperatingSystemsMeta$outboundSchema;
  /** @deprecated use `OperatingSystemsMeta$Outbound` instead. */
  export type Outbound = OperatingSystemsMeta$Outbound;
}

export function operatingSystemsMetaToJSON(
  operatingSystemsMeta: OperatingSystemsMeta,
): string {
  return JSON.stringify(
    OperatingSystemsMeta$outboundSchema.parse(operatingSystemsMeta),
  );
}

export function operatingSystemsMetaFromJSON(
  jsonString: string,
): SafeParseResult<OperatingSystemsMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OperatingSystemsMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OperatingSystemsMeta' from JSON`,
  );
}

/** @internal */
export const OperatingSystems$inboundSchema: z.ZodType<
  OperatingSystems,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(OperatingSystemData$inboundSchema).optional(),
  meta: z.lazy(() => OperatingSystemsMeta$inboundSchema).optional(),
});

/** @internal */
export type OperatingSystems$Outbound = {
  data?: Array<OperatingSystemData$Outbound> | undefined;
  meta?: OperatingSystemsMeta$Outbound | undefined;
};

/** @internal */
export const OperatingSystems$outboundSchema: z.ZodType<
  OperatingSystems$Outbound,
  z.ZodTypeDef,
  OperatingSystems
> = z.object({
  data: z.array(OperatingSystemData$outboundSchema).optional(),
  meta: z.lazy(() => OperatingSystemsMeta$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OperatingSystems$ {
  /** @deprecated use `OperatingSystems$inboundSchema` instead. */
  export const inboundSchema = OperatingSystems$inboundSchema;
  /** @deprecated use `OperatingSystems$outboundSchema` instead. */
  export const outboundSchema = OperatingSystems$outboundSchema;
  /** @deprecated use `OperatingSystems$Outbound` instead. */
  export type Outbound = OperatingSystems$Outbound;
}

export function operatingSystemsToJSON(
  operatingSystems: OperatingSystems,
): string {
  return JSON.stringify(
    OperatingSystems$outboundSchema.parse(operatingSystems),
  );
}

export function operatingSystemsFromJSON(
  jsonString: string,
): SafeParseResult<OperatingSystems, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OperatingSystems$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OperatingSystems' from JSON`,
  );
}
