/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PublicNetworkData,
  PublicNetworkData$inboundSchema,
  PublicNetworkData$Outbound,
  PublicNetworkData$outboundSchema,
} from "./publicnetworkdata.js";

export type PublicNetwork = {
  data?: PublicNetworkData | undefined;
};

/** @internal */
export const PublicNetwork$inboundSchema: z.ZodType<
  PublicNetwork,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: PublicNetworkData$inboundSchema.optional(),
});
/** @internal */
export type PublicNetwork$Outbound = {
  data?: PublicNetworkData$Outbound | undefined;
};

/** @internal */
export const PublicNetwork$outboundSchema: z.ZodType<
  PublicNetwork$Outbound,
  z.ZodTypeDef,
  PublicNetwork
> = z.object({
  data: PublicNetworkData$outboundSchema.optional(),
});

export function publicNetworkToJSON(publicNetwork: PublicNetwork): string {
  return JSON.stringify(PublicNetwork$outboundSchema.parse(publicNetwork));
}
export function publicNetworkFromJSON(
  jsonString: string,
): SafeParseResult<PublicNetwork, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublicNetwork$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublicNetwork' from JSON`,
  );
}
