/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type RegionsCountry = {
  slug?: string | undefined;
  name?: string | undefined;
};

export type RegionsAttributes = {
  slug?: string | undefined;
  name?: string | undefined;
  country?: RegionsCountry | undefined;
};

export type RegionsData = {
  id?: string | undefined;
  attributes?: RegionsAttributes | undefined;
};

export type Regions = {
  data?: Array<RegionsData> | undefined;
};

/** @internal */
export const RegionsCountry$inboundSchema: z.ZodType<
  RegionsCountry,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string().optional(),
  name: z.string().optional(),
});
/** @internal */
export type RegionsCountry$Outbound = {
  slug?: string | undefined;
  name?: string | undefined;
};

/** @internal */
export const RegionsCountry$outboundSchema: z.ZodType<
  RegionsCountry$Outbound,
  z.ZodTypeDef,
  RegionsCountry
> = z.object({
  slug: z.string().optional(),
  name: z.string().optional(),
});

export function regionsCountryToJSON(regionsCountry: RegionsCountry): string {
  return JSON.stringify(RegionsCountry$outboundSchema.parse(regionsCountry));
}
export function regionsCountryFromJSON(
  jsonString: string,
): SafeParseResult<RegionsCountry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RegionsCountry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegionsCountry' from JSON`,
  );
}

/** @internal */
export const RegionsAttributes$inboundSchema: z.ZodType<
  RegionsAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string().optional(),
  name: z.string().optional(),
  country: z.lazy(() => RegionsCountry$inboundSchema).optional(),
});
/** @internal */
export type RegionsAttributes$Outbound = {
  slug?: string | undefined;
  name?: string | undefined;
  country?: RegionsCountry$Outbound | undefined;
};

/** @internal */
export const RegionsAttributes$outboundSchema: z.ZodType<
  RegionsAttributes$Outbound,
  z.ZodTypeDef,
  RegionsAttributes
> = z.object({
  slug: z.string().optional(),
  name: z.string().optional(),
  country: z.lazy(() => RegionsCountry$outboundSchema).optional(),
});

export function regionsAttributesToJSON(
  regionsAttributes: RegionsAttributes,
): string {
  return JSON.stringify(
    RegionsAttributes$outboundSchema.parse(regionsAttributes),
  );
}
export function regionsAttributesFromJSON(
  jsonString: string,
): SafeParseResult<RegionsAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RegionsAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegionsAttributes' from JSON`,
  );
}

/** @internal */
export const RegionsData$inboundSchema: z.ZodType<
  RegionsData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  attributes: z.lazy(() => RegionsAttributes$inboundSchema).optional(),
});
/** @internal */
export type RegionsData$Outbound = {
  id?: string | undefined;
  attributes?: RegionsAttributes$Outbound | undefined;
};

/** @internal */
export const RegionsData$outboundSchema: z.ZodType<
  RegionsData$Outbound,
  z.ZodTypeDef,
  RegionsData
> = z.object({
  id: z.string().optional(),
  attributes: z.lazy(() => RegionsAttributes$outboundSchema).optional(),
});

export function regionsDataToJSON(regionsData: RegionsData): string {
  return JSON.stringify(RegionsData$outboundSchema.parse(regionsData));
}
export function regionsDataFromJSON(
  jsonString: string,
): SafeParseResult<RegionsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RegionsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RegionsData' from JSON`,
  );
}

/** @internal */
export const Regions$inboundSchema: z.ZodType<Regions, z.ZodTypeDef, unknown> =
  z.object({
    data: z.array(z.lazy(() => RegionsData$inboundSchema)).optional(),
  });
/** @internal */
export type Regions$Outbound = {
  data?: Array<RegionsData$Outbound> | undefined;
};

/** @internal */
export const Regions$outboundSchema: z.ZodType<
  Regions$Outbound,
  z.ZodTypeDef,
  Regions
> = z.object({
  data: z.array(z.lazy(() => RegionsData$outboundSchema)).optional(),
});

export function regionsToJSON(regions: Regions): string {
  return JSON.stringify(Regions$outboundSchema.parse(regions));
}
export function regionsFromJSON(
  jsonString: string,
): SafeParseResult<Regions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Regions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Regions' from JSON`,
  );
}
