/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const StoragePlanDataType = {
  StoragePlans: "storage_plans",
} as const;
export type StoragePlanDataType = ClosedEnum<typeof StoragePlanDataType>;

export type StoragePlanDataPricing = {
  month?: number | undefined;
};

export type StoragePlanDataAttributes = {
  name?: string | undefined;
  locations?: Array<string> | undefined;
  pricing?: StoragePlanDataPricing | undefined;
};

export type StoragePlanData = {
  id?: string | undefined;
  type?: StoragePlanDataType | undefined;
  attributes?: StoragePlanDataAttributes | undefined;
};

/** @internal */
export const StoragePlanDataType$inboundSchema: z.ZodNativeEnum<
  typeof StoragePlanDataType
> = z.nativeEnum(StoragePlanDataType);

/** @internal */
export const StoragePlanDataType$outboundSchema: z.ZodNativeEnum<
  typeof StoragePlanDataType
> = StoragePlanDataType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StoragePlanDataType$ {
  /** @deprecated use `StoragePlanDataType$inboundSchema` instead. */
  export const inboundSchema = StoragePlanDataType$inboundSchema;
  /** @deprecated use `StoragePlanDataType$outboundSchema` instead. */
  export const outboundSchema = StoragePlanDataType$outboundSchema;
}

/** @internal */
export const StoragePlanDataPricing$inboundSchema: z.ZodType<
  StoragePlanDataPricing,
  z.ZodTypeDef,
  unknown
> = z.object({
  month: z.number().optional(),
});

/** @internal */
export type StoragePlanDataPricing$Outbound = {
  month?: number | undefined;
};

/** @internal */
export const StoragePlanDataPricing$outboundSchema: z.ZodType<
  StoragePlanDataPricing$Outbound,
  z.ZodTypeDef,
  StoragePlanDataPricing
> = z.object({
  month: z.number().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StoragePlanDataPricing$ {
  /** @deprecated use `StoragePlanDataPricing$inboundSchema` instead. */
  export const inboundSchema = StoragePlanDataPricing$inboundSchema;
  /** @deprecated use `StoragePlanDataPricing$outboundSchema` instead. */
  export const outboundSchema = StoragePlanDataPricing$outboundSchema;
  /** @deprecated use `StoragePlanDataPricing$Outbound` instead. */
  export type Outbound = StoragePlanDataPricing$Outbound;
}

export function storagePlanDataPricingToJSON(
  storagePlanDataPricing: StoragePlanDataPricing,
): string {
  return JSON.stringify(
    StoragePlanDataPricing$outboundSchema.parse(storagePlanDataPricing),
  );
}

export function storagePlanDataPricingFromJSON(
  jsonString: string,
): SafeParseResult<StoragePlanDataPricing, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StoragePlanDataPricing$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StoragePlanDataPricing' from JSON`,
  );
}

/** @internal */
export const StoragePlanDataAttributes$inboundSchema: z.ZodType<
  StoragePlanDataAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  locations: z.array(z.string()).optional(),
  pricing: z.lazy(() => StoragePlanDataPricing$inboundSchema).optional(),
});

/** @internal */
export type StoragePlanDataAttributes$Outbound = {
  name?: string | undefined;
  locations?: Array<string> | undefined;
  pricing?: StoragePlanDataPricing$Outbound | undefined;
};

/** @internal */
export const StoragePlanDataAttributes$outboundSchema: z.ZodType<
  StoragePlanDataAttributes$Outbound,
  z.ZodTypeDef,
  StoragePlanDataAttributes
> = z.object({
  name: z.string().optional(),
  locations: z.array(z.string()).optional(),
  pricing: z.lazy(() => StoragePlanDataPricing$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StoragePlanDataAttributes$ {
  /** @deprecated use `StoragePlanDataAttributes$inboundSchema` instead. */
  export const inboundSchema = StoragePlanDataAttributes$inboundSchema;
  /** @deprecated use `StoragePlanDataAttributes$outboundSchema` instead. */
  export const outboundSchema = StoragePlanDataAttributes$outboundSchema;
  /** @deprecated use `StoragePlanDataAttributes$Outbound` instead. */
  export type Outbound = StoragePlanDataAttributes$Outbound;
}

export function storagePlanDataAttributesToJSON(
  storagePlanDataAttributes: StoragePlanDataAttributes,
): string {
  return JSON.stringify(
    StoragePlanDataAttributes$outboundSchema.parse(storagePlanDataAttributes),
  );
}

export function storagePlanDataAttributesFromJSON(
  jsonString: string,
): SafeParseResult<StoragePlanDataAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StoragePlanDataAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StoragePlanDataAttributes' from JSON`,
  );
}

/** @internal */
export const StoragePlanData$inboundSchema: z.ZodType<
  StoragePlanData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  type: StoragePlanDataType$inboundSchema.optional(),
  attributes: z.lazy(() => StoragePlanDataAttributes$inboundSchema).optional(),
});

/** @internal */
export type StoragePlanData$Outbound = {
  id?: string | undefined;
  type?: string | undefined;
  attributes?: StoragePlanDataAttributes$Outbound | undefined;
};

/** @internal */
export const StoragePlanData$outboundSchema: z.ZodType<
  StoragePlanData$Outbound,
  z.ZodTypeDef,
  StoragePlanData
> = z.object({
  id: z.string().optional(),
  type: StoragePlanDataType$outboundSchema.optional(),
  attributes: z.lazy(() => StoragePlanDataAttributes$outboundSchema).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StoragePlanData$ {
  /** @deprecated use `StoragePlanData$inboundSchema` instead. */
  export const inboundSchema = StoragePlanData$inboundSchema;
  /** @deprecated use `StoragePlanData$outboundSchema` instead. */
  export const outboundSchema = StoragePlanData$outboundSchema;
  /** @deprecated use `StoragePlanData$Outbound` instead. */
  export type Outbound = StoragePlanData$Outbound;
}

export function storagePlanDataToJSON(
  storagePlanData: StoragePlanData,
): string {
  return JSON.stringify(StoragePlanData$outboundSchema.parse(storagePlanData));
}

export function storagePlanDataFromJSON(
  jsonString: string,
): SafeParseResult<StoragePlanData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StoragePlanData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StoragePlanData' from JSON`,
  );
}
