/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ProjectInclude,
  ProjectInclude$inboundSchema,
  ProjectInclude$Outbound,
  ProjectInclude$outboundSchema,
} from "./projectinclude.js";
import {
  UserInclude,
  UserInclude$inboundSchema,
  UserInclude$Outbound,
  UserInclude$outboundSchema,
} from "./userinclude.js";

export type TeamBilling = {
  id?: string | undefined;
  customerBillingId?: string | undefined;
};

export type TeamLimits = {
  bareMetal?: number | null | undefined;
  bareMetalGpu?: number | null | undefined;
  virtualMachine?: number | null | undefined;
  virtualMachineGpu?: number | null | undefined;
  elasticIp?: number | null | undefined;
  prefix?: number | null | undefined;
  virtualNetwork?: number | null | undefined;
  database?: number | null | undefined;
  filesystem?: number | null | undefined;
  blockStorage?: number | null | undefined;
};

export type TeamAttributes = {
  name?: string | undefined;
  slug?: string | undefined;
  description?: string | null | undefined;
  address?: string | null | undefined;
  currency?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  status?: string | null | undefined;
  enforceMfa?: boolean | undefined;
  token?: string | null | undefined;
  customerBillingId?: string | null | undefined;
  referredCode?: string | null | undefined;
  users?: Array<UserInclude> | undefined;
  projects?: Array<ProjectInclude> | undefined;
  owner?: UserInclude | undefined;
  billing?: TeamBilling | undefined;
  featureFlags?: Array<string> | undefined;
  limits?: TeamLimits | undefined;
};

export type Team = {
  id?: string | undefined;
  attributes?: TeamAttributes | undefined;
};

/** @internal */
export const TeamBilling$inboundSchema: z.ZodType<
  TeamBilling,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  customer_billing_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "customer_billing_id": "customerBillingId",
  });
});
/** @internal */
export type TeamBilling$Outbound = {
  id?: string | undefined;
  customer_billing_id?: string | undefined;
};

/** @internal */
export const TeamBilling$outboundSchema: z.ZodType<
  TeamBilling$Outbound,
  z.ZodTypeDef,
  TeamBilling
> = z.object({
  id: z.string().optional(),
  customerBillingId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    customerBillingId: "customer_billing_id",
  });
});

export function teamBillingToJSON(teamBilling: TeamBilling): string {
  return JSON.stringify(TeamBilling$outboundSchema.parse(teamBilling));
}
export function teamBillingFromJSON(
  jsonString: string,
): SafeParseResult<TeamBilling, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TeamBilling$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TeamBilling' from JSON`,
  );
}

/** @internal */
export const TeamLimits$inboundSchema: z.ZodType<
  TeamLimits,
  z.ZodTypeDef,
  unknown
> = z.object({
  bare_metal: z.nullable(z.number().int()).optional(),
  bare_metal_gpu: z.nullable(z.number().int()).optional(),
  virtual_machine: z.nullable(z.number().int()).optional(),
  virtual_machine_gpu: z.nullable(z.number().int()).optional(),
  elastic_ip: z.nullable(z.number().int()).optional(),
  prefix: z.nullable(z.number().int()).optional(),
  virtual_network: z.nullable(z.number().int()).optional(),
  database: z.nullable(z.number().int()).optional(),
  filesystem: z.nullable(z.number().int()).optional(),
  block_storage: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "bare_metal": "bareMetal",
    "bare_metal_gpu": "bareMetalGpu",
    "virtual_machine": "virtualMachine",
    "virtual_machine_gpu": "virtualMachineGpu",
    "elastic_ip": "elasticIp",
    "virtual_network": "virtualNetwork",
    "block_storage": "blockStorage",
  });
});
/** @internal */
export type TeamLimits$Outbound = {
  bare_metal?: number | null | undefined;
  bare_metal_gpu?: number | null | undefined;
  virtual_machine?: number | null | undefined;
  virtual_machine_gpu?: number | null | undefined;
  elastic_ip?: number | null | undefined;
  prefix?: number | null | undefined;
  virtual_network?: number | null | undefined;
  database?: number | null | undefined;
  filesystem?: number | null | undefined;
  block_storage?: number | null | undefined;
};

/** @internal */
export const TeamLimits$outboundSchema: z.ZodType<
  TeamLimits$Outbound,
  z.ZodTypeDef,
  TeamLimits
> = z.object({
  bareMetal: z.nullable(z.number().int()).optional(),
  bareMetalGpu: z.nullable(z.number().int()).optional(),
  virtualMachine: z.nullable(z.number().int()).optional(),
  virtualMachineGpu: z.nullable(z.number().int()).optional(),
  elasticIp: z.nullable(z.number().int()).optional(),
  prefix: z.nullable(z.number().int()).optional(),
  virtualNetwork: z.nullable(z.number().int()).optional(),
  database: z.nullable(z.number().int()).optional(),
  filesystem: z.nullable(z.number().int()).optional(),
  blockStorage: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    bareMetal: "bare_metal",
    bareMetalGpu: "bare_metal_gpu",
    virtualMachine: "virtual_machine",
    virtualMachineGpu: "virtual_machine_gpu",
    elasticIp: "elastic_ip",
    virtualNetwork: "virtual_network",
    blockStorage: "block_storage",
  });
});

export function teamLimitsToJSON(teamLimits: TeamLimits): string {
  return JSON.stringify(TeamLimits$outboundSchema.parse(teamLimits));
}
export function teamLimitsFromJSON(
  jsonString: string,
): SafeParseResult<TeamLimits, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TeamLimits$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TeamLimits' from JSON`,
  );
}

/** @internal */
export const TeamAttributes$inboundSchema: z.ZodType<
  TeamAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  slug: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  address: z.nullable(z.string()).optional(),
  currency: z.string().optional(),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  status: z.nullable(z.string()).optional(),
  enforce_mfa: z.boolean().optional(),
  token: z.nullable(z.string()).optional(),
  customer_billing_id: z.nullable(z.string()).optional(),
  referred_code: z.nullable(z.string()).optional(),
  users: z.array(UserInclude$inboundSchema).optional(),
  projects: z.array(ProjectInclude$inboundSchema).optional(),
  owner: UserInclude$inboundSchema.optional(),
  billing: z.lazy(() => TeamBilling$inboundSchema).optional(),
  feature_flags: z.array(z.string()).optional(),
  limits: z.lazy(() => TeamLimits$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "enforce_mfa": "enforceMfa",
    "customer_billing_id": "customerBillingId",
    "referred_code": "referredCode",
    "feature_flags": "featureFlags",
  });
});
/** @internal */
export type TeamAttributes$Outbound = {
  name?: string | undefined;
  slug?: string | undefined;
  description?: string | null | undefined;
  address?: string | null | undefined;
  currency?: string | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
  status?: string | null | undefined;
  enforce_mfa?: boolean | undefined;
  token?: string | null | undefined;
  customer_billing_id?: string | null | undefined;
  referred_code?: string | null | undefined;
  users?: Array<UserInclude$Outbound> | undefined;
  projects?: Array<ProjectInclude$Outbound> | undefined;
  owner?: UserInclude$Outbound | undefined;
  billing?: TeamBilling$Outbound | undefined;
  feature_flags?: Array<string> | undefined;
  limits?: TeamLimits$Outbound | undefined;
};

/** @internal */
export const TeamAttributes$outboundSchema: z.ZodType<
  TeamAttributes$Outbound,
  z.ZodTypeDef,
  TeamAttributes
> = z.object({
  name: z.string().optional(),
  slug: z.string().optional(),
  description: z.nullable(z.string()).optional(),
  address: z.nullable(z.string()).optional(),
  currency: z.string().optional(),
  createdAt: z.string().optional(),
  updatedAt: z.string().optional(),
  status: z.nullable(z.string()).optional(),
  enforceMfa: z.boolean().optional(),
  token: z.nullable(z.string()).optional(),
  customerBillingId: z.nullable(z.string()).optional(),
  referredCode: z.nullable(z.string()).optional(),
  users: z.array(UserInclude$outboundSchema).optional(),
  projects: z.array(ProjectInclude$outboundSchema).optional(),
  owner: UserInclude$outboundSchema.optional(),
  billing: z.lazy(() => TeamBilling$outboundSchema).optional(),
  featureFlags: z.array(z.string()).optional(),
  limits: z.lazy(() => TeamLimits$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    updatedAt: "updated_at",
    enforceMfa: "enforce_mfa",
    customerBillingId: "customer_billing_id",
    referredCode: "referred_code",
    featureFlags: "feature_flags",
  });
});

export function teamAttributesToJSON(teamAttributes: TeamAttributes): string {
  return JSON.stringify(TeamAttributes$outboundSchema.parse(teamAttributes));
}
export function teamAttributesFromJSON(
  jsonString: string,
): SafeParseResult<TeamAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TeamAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TeamAttributes' from JSON`,
  );
}

/** @internal */
export const Team$inboundSchema: z.ZodType<Team, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string().optional(),
    attributes: z.lazy(() => TeamAttributes$inboundSchema).optional(),
  });
/** @internal */
export type Team$Outbound = {
  id?: string | undefined;
  attributes?: TeamAttributes$Outbound | undefined;
};

/** @internal */
export const Team$outboundSchema: z.ZodType<Team$Outbound, z.ZodTypeDef, Team> =
  z.object({
    id: z.string().optional(),
    attributes: z.lazy(() => TeamAttributes$outboundSchema).optional(),
  });

export function teamToJSON(team: Team): string {
  return JSON.stringify(Team$outboundSchema.parse(team));
}
export function teamFromJSON(
  jsonString: string,
): SafeParseResult<Team, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Team$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Team' from JSON`,
  );
}
