/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const VirtualMachineRestorePayloadType = {
  VirtualMachineRestores: "virtual_machine_restores",
} as const;
export type VirtualMachineRestorePayloadType = ClosedEnum<
  typeof VirtualMachineRestorePayloadType
>;

export type VirtualMachineRestorePayloadAttributes = {
  /**
   * Source backup id. Required on the flat `POST /virtual_machine_restores`; taken from the path when nested under a backup.
   */
  backup?: string | undefined;
  /**
   * Optional name for the restored VM. Auto-generated from the source VM when omitted.
   */
  name?: string | null | undefined;
  /**
   * Optional target site slug. Restores into that region (migration) instead of the backup's own region. Defaults to the backup's site.
   */
  site?: string | null | undefined;
};

export type VirtualMachineRestorePayloadData = {
  type?: VirtualMachineRestorePayloadType | undefined;
  attributes?: VirtualMachineRestorePayloadAttributes | undefined;
};

export type VirtualMachineRestorePayload = {
  data?: VirtualMachineRestorePayloadData | undefined;
};

/** @internal */
export const VirtualMachineRestorePayloadType$inboundSchema: z.ZodNativeEnum<
  typeof VirtualMachineRestorePayloadType
> = z.nativeEnum(VirtualMachineRestorePayloadType);
/** @internal */
export const VirtualMachineRestorePayloadType$outboundSchema: z.ZodNativeEnum<
  typeof VirtualMachineRestorePayloadType
> = VirtualMachineRestorePayloadType$inboundSchema;

/** @internal */
export const VirtualMachineRestorePayloadAttributes$inboundSchema: z.ZodType<
  VirtualMachineRestorePayloadAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  backup: z.string().optional(),
  name: z.nullable(z.string()).optional(),
  site: z.nullable(z.string()).optional(),
});
/** @internal */
export type VirtualMachineRestorePayloadAttributes$Outbound = {
  backup?: string | undefined;
  name?: string | null | undefined;
  site?: string | null | undefined;
};

/** @internal */
export const VirtualMachineRestorePayloadAttributes$outboundSchema: z.ZodType<
  VirtualMachineRestorePayloadAttributes$Outbound,
  z.ZodTypeDef,
  VirtualMachineRestorePayloadAttributes
> = z.object({
  backup: z.string().optional(),
  name: z.nullable(z.string()).optional(),
  site: z.nullable(z.string()).optional(),
});

export function virtualMachineRestorePayloadAttributesToJSON(
  virtualMachineRestorePayloadAttributes:
    VirtualMachineRestorePayloadAttributes,
): string {
  return JSON.stringify(
    VirtualMachineRestorePayloadAttributes$outboundSchema.parse(
      virtualMachineRestorePayloadAttributes,
    ),
  );
}
export function virtualMachineRestorePayloadAttributesFromJSON(
  jsonString: string,
): SafeParseResult<VirtualMachineRestorePayloadAttributes, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      VirtualMachineRestorePayloadAttributes$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VirtualMachineRestorePayloadAttributes' from JSON`,
  );
}

/** @internal */
export const VirtualMachineRestorePayloadData$inboundSchema: z.ZodType<
  VirtualMachineRestorePayloadData,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: VirtualMachineRestorePayloadType$inboundSchema.optional(),
  attributes: z.lazy(() => VirtualMachineRestorePayloadAttributes$inboundSchema)
    .optional(),
});
/** @internal */
export type VirtualMachineRestorePayloadData$Outbound = {
  type?: string | undefined;
  attributes?: VirtualMachineRestorePayloadAttributes$Outbound | undefined;
};

/** @internal */
export const VirtualMachineRestorePayloadData$outboundSchema: z.ZodType<
  VirtualMachineRestorePayloadData$Outbound,
  z.ZodTypeDef,
  VirtualMachineRestorePayloadData
> = z.object({
  type: VirtualMachineRestorePayloadType$outboundSchema.optional(),
  attributes: z.lazy(() =>
    VirtualMachineRestorePayloadAttributes$outboundSchema
  ).optional(),
});

export function virtualMachineRestorePayloadDataToJSON(
  virtualMachineRestorePayloadData: VirtualMachineRestorePayloadData,
): string {
  return JSON.stringify(
    VirtualMachineRestorePayloadData$outboundSchema.parse(
      virtualMachineRestorePayloadData,
    ),
  );
}
export function virtualMachineRestorePayloadDataFromJSON(
  jsonString: string,
): SafeParseResult<VirtualMachineRestorePayloadData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VirtualMachineRestorePayloadData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VirtualMachineRestorePayloadData' from JSON`,
  );
}

/** @internal */
export const VirtualMachineRestorePayload$inboundSchema: z.ZodType<
  VirtualMachineRestorePayload,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => VirtualMachineRestorePayloadData$inboundSchema).optional(),
});
/** @internal */
export type VirtualMachineRestorePayload$Outbound = {
  data?: VirtualMachineRestorePayloadData$Outbound | undefined;
};

/** @internal */
export const VirtualMachineRestorePayload$outboundSchema: z.ZodType<
  VirtualMachineRestorePayload$Outbound,
  z.ZodTypeDef,
  VirtualMachineRestorePayload
> = z.object({
  data: z.lazy(() => VirtualMachineRestorePayloadData$outboundSchema)
    .optional(),
});

export function virtualMachineRestorePayloadToJSON(
  virtualMachineRestorePayload: VirtualMachineRestorePayload,
): string {
  return JSON.stringify(
    VirtualMachineRestorePayload$outboundSchema.parse(
      virtualMachineRestorePayload,
    ),
  );
}
export function virtualMachineRestorePayloadFromJSON(
  jsonString: string,
): SafeParseResult<VirtualMachineRestorePayload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VirtualMachineRestorePayload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VirtualMachineRestorePayload' from JSON`,
  );
}
