/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
  PaginationMeta$Outbound,
  PaginationMeta$outboundSchema,
} from "./paginationmeta.js";
import {
  VirtualNetworkAssignmentData,
  VirtualNetworkAssignmentData$inboundSchema,
  VirtualNetworkAssignmentData$Outbound,
  VirtualNetworkAssignmentData$outboundSchema,
} from "./virtualnetworkassignmentdata.js";

export type VirtualNetworkAssignments = {
  data?: Array<VirtualNetworkAssignmentData> | undefined;
  meta?: PaginationMeta | undefined;
};

/** @internal */
export const VirtualNetworkAssignments$inboundSchema: z.ZodType<
  VirtualNetworkAssignments,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(VirtualNetworkAssignmentData$inboundSchema).optional(),
  meta: PaginationMeta$inboundSchema.optional(),
});
/** @internal */
export type VirtualNetworkAssignments$Outbound = {
  data?: Array<VirtualNetworkAssignmentData$Outbound> | undefined;
  meta?: PaginationMeta$Outbound | undefined;
};

/** @internal */
export const VirtualNetworkAssignments$outboundSchema: z.ZodType<
  VirtualNetworkAssignments$Outbound,
  z.ZodTypeDef,
  VirtualNetworkAssignments
> = z.object({
  data: z.array(VirtualNetworkAssignmentData$outboundSchema).optional(),
  meta: PaginationMeta$outboundSchema.optional(),
});

export function virtualNetworkAssignmentsToJSON(
  virtualNetworkAssignments: VirtualNetworkAssignments,
): string {
  return JSON.stringify(
    VirtualNetworkAssignments$outboundSchema.parse(virtualNetworkAssignments),
  );
}
export function virtualNetworkAssignmentsFromJSON(
  jsonString: string,
): SafeParseResult<VirtualNetworkAssignments, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VirtualNetworkAssignments$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VirtualNetworkAssignments' from JSON`,
  );
}
