/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  VirtualMachineRestoreAttributes,
  VirtualMachineRestoreAttributes$inboundSchema,
  VirtualMachineRestoreAttributes$Outbound,
  VirtualMachineRestoreAttributes$outboundSchema,
} from "./virtualmachinerestoreattributes.js";

export type VirtualMachineRestoresMeta = {};

export type VirtualMachineRestores = {
  data?: Array<VirtualMachineRestoreAttributes> | undefined;
  meta?: VirtualMachineRestoresMeta | undefined;
};

/** @internal */
export const VirtualMachineRestoresMeta$inboundSchema: z.ZodType<
  VirtualMachineRestoresMeta,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type VirtualMachineRestoresMeta$Outbound = {};

/** @internal */
export const VirtualMachineRestoresMeta$outboundSchema: z.ZodType<
  VirtualMachineRestoresMeta$Outbound,
  z.ZodTypeDef,
  VirtualMachineRestoresMeta
> = z.object({});

export function virtualMachineRestoresMetaToJSON(
  virtualMachineRestoresMeta: VirtualMachineRestoresMeta,
): string {
  return JSON.stringify(
    VirtualMachineRestoresMeta$outboundSchema.parse(virtualMachineRestoresMeta),
  );
}
export function virtualMachineRestoresMetaFromJSON(
  jsonString: string,
): SafeParseResult<VirtualMachineRestoresMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VirtualMachineRestoresMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VirtualMachineRestoresMeta' from JSON`,
  );
}

/** @internal */
export const VirtualMachineRestores$inboundSchema: z.ZodType<
  VirtualMachineRestores,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(VirtualMachineRestoreAttributes$inboundSchema).optional(),
  meta: z.lazy(() => VirtualMachineRestoresMeta$inboundSchema).optional(),
});
/** @internal */
export type VirtualMachineRestores$Outbound = {
  data?: Array<VirtualMachineRestoreAttributes$Outbound> | undefined;
  meta?: VirtualMachineRestoresMeta$Outbound | undefined;
};

/** @internal */
export const VirtualMachineRestores$outboundSchema: z.ZodType<
  VirtualMachineRestores$Outbound,
  z.ZodTypeDef,
  VirtualMachineRestores
> = z.object({
  data: z.array(VirtualMachineRestoreAttributes$outboundSchema).optional(),
  meta: z.lazy(() => VirtualMachineRestoresMeta$outboundSchema).optional(),
});

export function virtualMachineRestoresToJSON(
  virtualMachineRestores: VirtualMachineRestores,
): string {
  return JSON.stringify(
    VirtualMachineRestores$outboundSchema.parse(virtualMachineRestores),
  );
}
export function virtualMachineRestoresFromJSON(
  jsonString: string,
): SafeParseResult<VirtualMachineRestores, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VirtualMachineRestores$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VirtualMachineRestores' from JSON`,
  );
}
