/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  VpnSessionDataWithPassword,
  VpnSessionDataWithPassword$inboundSchema,
  VpnSessionDataWithPassword$Outbound,
  VpnSessionDataWithPassword$outboundSchema,
} from "./vpnsessiondatawithpassword.js";

export type VpnSessionWithPassword = {
  data?: VpnSessionDataWithPassword | undefined;
};

/** @internal */
export const VpnSessionWithPassword$inboundSchema: z.ZodType<
  VpnSessionWithPassword,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: VpnSessionDataWithPassword$inboundSchema.optional(),
});

/** @internal */
export type VpnSessionWithPassword$Outbound = {
  data?: VpnSessionDataWithPassword$Outbound | undefined;
};

/** @internal */
export const VpnSessionWithPassword$outboundSchema: z.ZodType<
  VpnSessionWithPassword$Outbound,
  z.ZodTypeDef,
  VpnSessionWithPassword
> = z.object({
  data: VpnSessionDataWithPassword$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VpnSessionWithPassword$ {
  /** @deprecated use `VpnSessionWithPassword$inboundSchema` instead. */
  export const inboundSchema = VpnSessionWithPassword$inboundSchema;
  /** @deprecated use `VpnSessionWithPassword$outboundSchema` instead. */
  export const outboundSchema = VpnSessionWithPassword$outboundSchema;
  /** @deprecated use `VpnSessionWithPassword$Outbound` instead. */
  export type Outbound = VpnSessionWithPassword$Outbound;
}

export function vpnSessionWithPasswordToJSON(
  vpnSessionWithPassword: VpnSessionWithPassword,
): string {
  return JSON.stringify(
    VpnSessionWithPassword$outboundSchema.parse(vpnSessionWithPassword),
  );
}

export function vpnSessionWithPasswordFromJSON(
  jsonString: string,
): SafeParseResult<VpnSessionWithPassword, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VpnSessionWithPassword$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VpnSessionWithPassword' from JSON`,
  );
}
